"""Shared helpers for dedicated-crew demos.

Background
----------
`ag_ui_crewai.endpoint.add_crewai_crew_fastapi_endpoint` composes its system
prompt via `crewai.cli.crew_chat.build_system_message(crew_chat_inputs)`,
where `crew_chat_inputs` is generated by `generate_crew_chat_inputs` (which
itself runs secondary AI calls to describe the crew and its inputs).

For per-demo crews in this showcase we want **full control** over the system
prompt — e.g. the BYOC demos need pure-JSON output, while the A2UI demos need
tool-selection guidance. We also want to skip the startup secondary AI calls
so that boot stays fast and the first request is not gated on an LLM probe.

Strategy
--------
We pre-seed `ag_ui_crewai.crews._CREW_INPUTS_CACHE[crew_name]` with a hand-built
`ChatInputs(crew_description=<our prompt>, inputs=[])` BEFORE the endpoint's
deferred flow construction runs. `build_system_message` then embeds our
description verbatim (surrounded by the fixed CrewAI platform boilerplate,
which the LLM is capable of working around when the description is strong
enough — and which we can partially neutralise by phrasing the description
as an override).

The pre-seed also skips the secondary AI calls in
`generate_crew_chat_inputs`, so crew construction is synchronous and cheap.

This is the least-invasive path that keeps us on the supported
`add_crewai_crew_fastapi_endpoint` surface without monkey-patching
`build_system_message` itself.
"""

from __future__ import annotations

from typing import Any

def preseed_system_prompt(crew_name: str, description: str) -> None:
    """Install `description` as `crew_description` for `crew_name`.

    Subsequent `ChatWithCrewFlow(crew=<our crew>)` construction will find the
    cached entry and skip the secondary AI description calls entirely.

    Safe to call before OR after `add_crewai_crew_fastapi_endpoint` — the
    endpoint construction is deferred to first request, so as long as we
    preseed before the first POST we are fine.
    """
    from ag_ui_crewai.crews import _CREW_INPUTS_CACHE
    from crewai.cli.crew_chat import ChatInputs

    _CREW_INPUTS_CACHE[crew_name] = ChatInputs(
        crew_name=crew_name,
        crew_description=description,
        inputs=[],
    )

def install_custom_system_message(crew_name: str, full_system_message: str) -> None:
    """Hard-override the system message for a specific crew.

    Some demos (notably BYOC) need the chat LLM to emit a very specific output
    shape that the stock `build_system_message` boilerplate actively fights
    (it tells the LLM to introduce itself, to ask clarifying questions, etc.).
    For those demos we patch `ChatWithCrewFlow.__init__` to stash our custom
    system message on the instance right after construction, overriding the
    one the upstream code assembled.

    Implementation: subclass `Flow` isn't exposed cleanly, so we monkey-patch
    at the module level. The hook is keyed by `crew_name`, so crews that
    don't register a custom message fall through to the stock behaviour.
    """
    import ag_ui_crewai.crews as _crews_module

    if not getattr(_crews_module, "_CUSTOM_SYSTEM_MESSAGES", None):
        _crews_module._CUSTOM_SYSTEM_MESSAGES = {}

        original_init = _crews_module.ChatWithCrewFlow.__init__

        def patched_init(self: Any, *, crew: Any) -> None:
            original_init(self, crew=crew)
            override = _crews_module._CUSTOM_SYSTEM_MESSAGES.get(
                getattr(self, "crew_name", None)
            )
            if override:
                self.system_message = override

        _crews_module.ChatWithCrewFlow.__init__ = patched_init  # type: ignore[method-assign]

    _crews_module._CUSTOM_SYSTEM_MESSAGES[crew_name] = full_system_message
