import type { Lead, Segment } from "./types";

// Trimmed sample dataset used as a fallback when a tool is invoked without
// a `leads` array. Mirrors the shape returned by the agent's Notion sync so
// the same widgets work for both real and demo data.
export const SAMPLE_LEADS: Lead[] = [
  {
    id: "sample-1",
    name: "Devon Price",
    email: "devon.price@example.com",
    role: "Product engineer",
    company: "Nimbus Legal",
    workshop: "RAG & Data Chat",
    technical_level: "Developer",
    tools: ["LlamaIndex", "OpenAI"],
    status: "Not started",
    opt_in: true,
  },
  {
    id: "sample-2",
    name: "Nina Petrova",
    email: "nina.petrova@example.com",
    role: "Educator",
    company: "BrightPath Learning",
    workshop: "MCP Apps / Tooling",
    technical_level: "Some technical",
    tools: ["CopilotKit", "Other"],
    status: "Not started",
    opt_in: true,
  },
  {
    id: "sample-3",
    name: "Sergey Volkov",
    email: "sergey.volkov@example.com",
    role: "Data platform engineer",
    company: "Polar Insight",
    workshop: "RAG & Data Chat",
    technical_level: "Developer",
    tools: ["LlamaIndex", "LangChain", "OpenAI"],
    status: "Not started",
    opt_in: true,
  },
  {
    id: "sample-4",
    name: "Grace Liu",
    email: "grace.liu@example.com",
    role: "Founder",
    company: "Mossy Ridge",
    workshop: "MCP Apps / Tooling",
    technical_level: "Some technical",
    tools: ["OpenAI", "Vercel AI SDK"],
    status: "Not started",
    opt_in: true,
  },
  {
    id: "sample-5",
    name: "Noah Brooks",
    email: "noah.brooks@example.com",
    role: "Engineering manager",
    company: "Helio Commerce",
    workshop: "Deploying Agents (prod)",
    technical_level: "Some technical",
    tools: ["LangChain", "OpenAI", "Vercel AI SDK"],
    status: "Not started",
    opt_in: true,
  },
  {
    id: "sample-6",
    name: "Priya Desai",
    email: "priya.desai@example.com",
    role: "Workshop facilitator",
    company: "Signal Grove",
    workshop: "MCP Apps / Tooling",
    technical_level: "Developer",
    tools: ["CopilotKit", "Anthropic", "Vercel AI SDK"],
    status: "Not started",
    opt_in: true,
  },
  {
    id: "sample-7",
    name: "Fatima Rahman",
    email: "fatima.rahman@example.com",
    role: "Community lead",
    company: "Pulse Media",
    workshop: "Not sure yet",
    technical_level: "Non-technical",
    tools: ["OpenAI", "Anthropic"],
    status: "Not started",
    opt_in: true,
  },
  {
    id: "sample-8",
    name: "Mei Tan",
    email: "mei.tan@example.com",
    role: "Designer",
    company: "Crescent Studio",
    workshop: "Agentic UI (AG-UI)",
    technical_level: "Some technical",
    tools: ["CopilotKit", "Other"],
    status: "Not started",
    opt_in: true,
  },
  {
    id: "sample-9",
    name: "Gabe Alvarez",
    email: "gabe.alvarez@example.com",
    role: "ML engineer",
    company: "Rivermint",
    workshop: "Evaluations & Guardrails",
    technical_level: "Advanced / expert",
    tools: ["LangChain", "Anthropic", "OpenAI"],
    status: "Not started",
    opt_in: false,
  },
  {
    id: "sample-10",
    name: "Miles Johnson",
    email: "miles.johnson@example.com",
    role: "Security engineer",
    company: "Keystone Security",
    workshop: "Evaluations & Guardrails",
    technical_level: "Advanced / expert",
    tools: ["OpenAI", "LangChain"],
    status: "Not started",
    opt_in: true,
  },
  {
    id: "sample-11",
    name: "Hugo Fernandes",
    email: "hugo.fernandes@example.com",
    role: "CTO",
    company: "RioStack",
    workshop: "Deploying Agents (prod)",
    technical_level: "Advanced / expert",
    tools: ["OpenAI", "LangChain", "Vercel AI SDK"],
    status: "Not started",
    opt_in: true,
  },
  {
    id: "sample-12",
    name: "Ethan Moore",
    email: "ethan.moore@example.com",
    role: "Data engineer",
    company: "Granite Retail",
    workshop: "RAG & Data Chat",
    technical_level: "Advanced / expert",
    tools: ["LlamaIndex", "LangChain", "OpenAI"],
    status: "In progress",
    opt_in: false,
  },
];

export const SAMPLE_SEGMENTS: Segment[] = [];
