/**
 * Generates the alias .mdx files and docs.json from integrations.config.ts.
 *
 * Run via `npm run gen-routing`. Hooked into `predev` and `prebuild`.
 *
 * What it generates:
 *   - For each non-default integration × each universal/reference page (subject
 *     to per-page `only` / `except` gating): a stub MDX file at
 *     docs/<integration>/<page>.mdx that re-renders the canonical content.
 *   - docs/docs.json with the full nav structure split into two tabs (Docs
 *     and Reference). The Docs tab carries `universalPages` (bucketed by
 *     `group`) plus the per-integration "<X> features" groups for
 *     integration-only pages. The Reference tab carries `referencePages`
 *     bucketed by `group` (Hooks, Components, Runtime, Agents, Handlers,
 *     Middleware).
 *
 * What it leaves alone:
 *   - Canonical pages (docs/<page>.mdx) — author content lives here
 *   - Integration-only pages (docs/<integration>/<slug>.mdx that aren't in
 *     universalPages or referencePages) — author content lives here too
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  integrations,
  defaultIntegration,
  universalPages,
  referencePages,
  integrationOnlyPages,
  getSupportedIntegrations,
  isCanonicalSupported,
  type PageDef,
  type IntegrationSlug,
} from '../integrations.config.ts';

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = path.resolve(SCRIPT_DIR, '..');
const DOCS_DIR = path.join(PROJECT_ROOT, 'docs');
const STYLES_DIR = path.join(PROJECT_ROOT, 'src', 'styles');

const HEADER =
  '<!-- AUTO-GENERATED by scripts/generate-routing.ts. Do not edit. Edit integrations.config.ts and run `npm run gen-routing`. -->';

// All slugs the generator owns (for orphan cleanup). A page being "owned"
// means the generator may write an alias for it under any integration prefix.
const universalSlugs = new Set(universalPages.map((p) => p.slug));
const referenceSlugs = new Set(referencePages.map((p) => p.slug));
const ownedSlugs = new Set<string>([...universalSlugs, ...referenceSlugs]);

// Combined list of pages that the generator emits aliases for.
const aliasablePages: readonly PageDef[] = [...universalPages, ...referencePages];

function aliasContent(page: PageDef): string {
  // AUTO-GENERATED marker lives as a YAML comment in the frontmatter so it's
  // visible in the file but doesn't disrupt MDX import parsing (Mintlify won't
  // treat any imports as imports if a body element appears before them).
  // The import path's `../` count depends on how nested the slug is — for slug
  // `generative-ui/tool-rendering` the alias lives at
  // `docs/<integration>/generative-ui/tool-rendering.mdx` and needs to reach
  // `docs/generative-ui/tool-rendering.mdx`, i.e. `../../`.
  const depth = page.slug.split('/').length;
  const upDirs = '../'.repeat(depth);
  const lines: string[] = [];
  lines.push('---');
  lines.push('# AUTO-GENERATED by scripts/generate-routing.ts. Do not edit.');
  lines.push('# Edit integrations.config.ts and run `npm run gen-routing`.');
  lines.push(`title: "${page.title}"`);
  if (page.description) lines.push(`description: "${page.description}"`);
  lines.push('---');
  lines.push('');
  lines.push(`import Page from '${upDirs}${page.slug}.mdx';`);
  lines.push('');
  lines.push('<Page />');
  lines.push('');
  return lines.join('\n');
}

function generateAliases() {
  const prefixed = integrations.filter((i) => i.slug !== defaultIntegration);
  const knownIntegrationSlugs = new Set(integrations.map((i) => i.slug));
  let written = 0;
  let cleaned = 0;
  let skippedByGating = 0;

  // Clean up orphaned integration directories (config removed an integration).
  for (const entry of fs.readdirSync(DOCS_DIR, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    if (knownIntegrationSlugs.has(entry.name)) continue;
    if (entry.name === 'images' || entry.name === 'logo') continue;
    if (entry.name === 'reference') continue;

    const dir = path.join(DOCS_DIR, entry.name);
    let dirHasAuthorContent = false;
    for (const file of fs.readdirSync(dir)) {
      if (!file.endsWith('.mdx')) continue;
      const content = fs.readFileSync(path.join(dir, file), 'utf-8');
      if (content.includes('# AUTO-GENERATED by scripts/generate-routing.ts')) {
        fs.unlinkSync(path.join(dir, file));
        cleaned++;
      } else {
        dirHasAuthorContent = true;
      }
    }
    if (!dirHasAuthorContent) {
      try {
        fs.rmdirSync(dir);
      } catch {
        // Directory may have non-mdx files (rare); leave it
      }
    }
  }

  let overridden = 0;
  for (const integration of prefixed) {
    const dir = path.join(DOCS_DIR, integration.slug);
    fs.mkdirSync(dir, { recursive: true });

    // Write fresh aliases for each page (universal + reference), respecting
    // per-page `only` / `except` gating. Creates nested dirs as needed for
    // slugs like `generative-ui/tool-rendering`. If a file already exists at
    // the alias path WITHOUT the AUTO-GENERATED marker, treat it as an
    // authored per-integration override and leave it alone — this is how an
    // integration ships its own version of a universal page (e.g. a
    // LangGraph-specific shared-state guide that diverges from canonical).
    for (const page of aliasablePages) {
      const supported = getSupportedIntegrations(page);
      if (!supported.includes(integration.slug as IntegrationSlug)) {
        skippedByGating++;
        continue;
      }
      const filepath = path.join(dir, `${page.slug}.mdx`);
      if (fs.existsSync(filepath)) {
        const existing = fs.readFileSync(filepath, 'utf-8');
        if (!existing.includes('# AUTO-GENERATED by scripts/generate-routing.ts')) {
          overridden++;
          continue;
        }
      }
      fs.mkdirSync(path.dirname(filepath), { recursive: true });
      fs.writeFileSync(filepath, aliasContent(page));
      written++;
    }

    // Remove stale aliases (alias files for slugs no longer in
    // universalPages/referencePages, or for slugs that gating now excludes
    // from this integration). Walk every .mdx file under the integration dir
    // (recursively, to cover nested reference/* paths).
    const integrationOnlySlugs = new Set(
      (integrationOnlyPages[integration.slug as keyof typeof integrationOnlyPages] ?? []).map(
        (p) => p.slug,
      ),
    );

    function walkAndClean(currentDir: string, relPrefix = ''): void {
      for (const entry of fs.readdirSync(currentDir, { withFileTypes: true })) {
        const abs = path.join(currentDir, entry.name);
        const rel = relPrefix ? `${relPrefix}/${entry.name}` : entry.name;
        if (entry.isDirectory()) {
          walkAndClean(abs, rel);
          // Remove now-empty directories left behind by stale alias files
          try {
            const remaining = fs.readdirSync(abs);
            if (remaining.length === 0) fs.rmdirSync(abs);
          } catch {
            // ignore
          }
          continue;
        }
        if (!entry.name.endsWith('.mdx')) continue;
        const slug = rel.replace(/\.mdx$/, '');
        // Keep if a config entry still owns this slug AND gating allows the
        // integration. Keep if it's an integration-only page.
        const ownedPage = aliasablePages.find((p) => p.slug === slug);
        if (ownedPage) {
          const supported = getSupportedIntegrations(ownedPage);
          if (supported.includes(integration.slug as IntegrationSlug)) continue;
        } else if (integrationOnlySlugs.has(slug)) {
          continue;
        }

        const content = fs.readFileSync(abs, 'utf-8');
        if (content.includes('# AUTO-GENERATED by scripts/generate-routing.ts')) {
          fs.unlinkSync(abs);
          cleaned++;
        }
      }
    }
    walkAndClean(dir);
  }

  console.log(`✓ Wrote ${written} alias .mdx file(s) across ${prefixed.length} integration(s)`);
  if (overridden > 0) console.log(`  Skipped ${overridden} alias write(s) (authored override exists)`);
  if (skippedByGating > 0) console.log(`  Skipped ${skippedByGating} alias write(s) (gated via only/except)`);
  if (cleaned > 0) console.log(`  Cleaned ${cleaned} stale alias file(s)`);
}

/**
 * For one page, emit the per-integration sidebar slugs in a stable order:
 * canonical (built-in) first if supported, then each non-default supported
 * integration. Each emitted slug is unique to one integration so the existing
 * single-value `data-item-integration` CSS still works.
 */
function pageSidebarSlugs(page: PageDef): string[] {
  const supported = getSupportedIntegrations(page);
  const slugs: string[] = [];
  if (supported.includes(defaultIntegration as IntegrationSlug)) {
    slugs.push(page.slug);
  }
  for (const integration of integrations) {
    if (integration.slug === defaultIntegration) continue;
    if (!supported.includes(integration.slug as IntegrationSlug)) continue;
    slugs.push(`${integration.slug}/${page.slug}`);
  }
  return slugs;
}

function buildDocsTabGroups(): Array<{ group: string; pages: string[] }> {
  // Bucket universalPages by their declared `group` field (defaulting to
  // 'Concepts'). Order of groups follows first occurrence in the array.
  const pagesByGroup = new Map<string, PageDef[]>();
  for (const page of universalPages) {
    const groupName = page.group ?? 'Concepts';
    if (!pagesByGroup.has(groupName)) pagesByGroup.set(groupName, []);
    pagesByGroup.get(groupName)!.push(page);
  }

  const groups: Array<{ group: string; pages: string[] }> = [];

  for (const [groupName, pages] of pagesByGroup) {
    const slugsForGroup: string[] = [];

    // 'Get started' is special: includes the index page (canonical home).
    if (groupName === 'Get started') {
      slugsForGroup.push('index');
    }

    for (const page of pages) {
      slugsForGroup.push(...pageSidebarSlugs(page));
    }

    groups.push({ group: groupName, pages: slugsForGroup });
  }

  // Per-integration "X features" groups for integration-only pages.
  // Filter out anything that collides with a universal slug — those are
  // handled via authored overrides under the canonical group, so listing
  // them here too would produce a duplicate sidebar entry.
  for (const integration of integrations) {
    if (integration.slug === defaultIntegration) continue;
    const onlyPages = integrationOnlyPages[integration.slug as keyof typeof integrationOnlyPages];
    if (!onlyPages || onlyPages.length === 0) continue;
    const filtered = onlyPages.filter((p) => !universalSlugs.has(p.slug));
    if (filtered.length === 0) continue;
    groups.push({
      group: `[${integration.slug}] ${integration.label} features`,
      pages: filtered.map((p) => `${integration.slug}/${p.slug}`),
    });
  }

  return groups;
}

function buildReferenceTabGroups(): Array<{ group: string; pages: string[] }> {
  // Bucket referencePages by their declared `group` field. Order of groups
  // follows first occurrence in the array.
  const pagesByGroup = new Map<string, PageDef[]>();
  for (const page of referencePages) {
    const groupName = page.group ?? 'Reference';
    if (!pagesByGroup.has(groupName)) pagesByGroup.set(groupName, []);
    pagesByGroup.get(groupName)!.push(page);
  }

  const groups: Array<{ group: string; pages: string[] }> = [];
  for (const [groupName, pages] of pagesByGroup) {
    const slugsForGroup: string[] = [];
    for (const page of pages) {
      slugsForGroup.push(...pageSidebarSlugs(page));
    }
    groups.push({ group: groupName, pages: slugsForGroup });
  }
  return groups;
}

function generateDocsJson() {
  const docsGroups = buildDocsTabGroups();
  const referenceGroups = buildReferenceTabGroups();

  const docsJson = {
    $schema: 'https://mintlify.com/docs.json',
    name: 'CopilotKit Docs',
    theme: 'mint',
    colors: {
      primary: '#757CF2',
      light: '#BEC2FF',
      dark: '#5A60D9',
    },
    logo: { light: '/logo/light.svg', dark: '/logo/dark.svg' },
    favicon: '/favicon.ico',
    navigation: {
      tabs: [
        { tab: 'Docs', groups: docsGroups },
        { tab: 'Reference', groups: referenceGroups },
      ],
    },
  };

  fs.writeFileSync(
    path.join(DOCS_DIR, 'docs.json'),
    JSON.stringify(docsJson, null, 2) + '\n',
  );
  console.log(
    `✓ Wrote docs.json — Docs tab: ${docsGroups.length} group(s), Reference tab: ${referenceGroups.length} group(s)`,
  );
}

/**
 * Convert a docs-tab group label (e.g. "Models & providers") into the slug that
 * `SidebarGroupItem.tsx` emits as `data-group-name`. Keep this in sync with the
 * slug derivation there: lowercase, non-alphanum → single dash, trim dashes.
 */
function groupNameToSlug(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

/**
 * For each universalPages group, list the integrations for which the group has
 * zero supported pages. Per-integration "X features" groups for
 * integration-only pages are excluded — those already use `data-group-integration`
 * gating and never appear empty for their owning integration.
 */
function computeEmptyGroupIntegrations(): Map<string, IntegrationSlug[]> {
  const empty = new Map<string, IntegrationSlug[]>();

  // Bucket pages by group, in declaration order.
  const pagesByGroup = new Map<string, PageDef[]>();
  for (const page of universalPages) {
    const groupName = page.group ?? 'Concepts';
    if (!pagesByGroup.has(groupName)) pagesByGroup.set(groupName, []);
    pagesByGroup.get(groupName)!.push(page);
  }

  for (const [groupName, pages] of pagesByGroup) {
    const integrationsWithNoSupportedPage: IntegrationSlug[] = [];
    for (const integration of integrations) {
      const slug = integration.slug as IntegrationSlug;
      const anySupported = pages.some((p) =>
        getSupportedIntegrations(p).includes(slug),
      );
      if (!anySupported) integrationsWithNoSupportedPage.push(slug);
    }
    if (integrationsWithNoSupportedPage.length > 0) {
      empty.set(groupNameToSlug(groupName), integrationsWithNoSupportedPage);
    }
  }
  return empty;
}

function generateIntegrationsCss() {
  const lines: string[] = [];
  lines.push('/* AUTO-GENERATED by scripts/generate-routing.ts. Do not edit. */');
  lines.push('/* Edit integrations.config.ts and run `npm run gen-routing`. */');
  lines.push('');
  lines.push('/* ─── Variant blocks: hide by default, show when body integration matches ── */');
  lines.push('[data-variant-for] {');
  lines.push('  display: none;');
  lines.push('}');
  for (const integration of integrations) {
    lines.push(
      `body[data-integration='${integration.slug}'] [data-variant-for~='${integration.slug}'] {`,
    );
    lines.push('  display: block;');
    lines.push('}');
  }
  lines.push('');
  lines.push('/* ─── Sidebar groups gated by integration ──────────────────────────────── */');
  for (const integration of integrations) {
    if (integration.slug === defaultIntegration) continue;
    lines.push(`[data-group-integration='${integration.slug}'] {`);
    lines.push('  display: none;');
    lines.push('}');
    lines.push(
      `body[data-integration='${integration.slug}'] [data-group-integration='${integration.slug}'] {`,
    );
    lines.push('  display: block;');
    lines.push('}');
  }
  lines.push('');
  lines.push('/* ─── Sidebar items gated by integration (one item visible per integration) ─ */');
  for (const integration of integrations) {
    lines.push(`[data-item-integration='${integration.slug}'] {`);
    lines.push('  display: none;');
    lines.push('}');
  }
  for (const integration of integrations) {
    lines.push(
      `body[data-integration='${integration.slug}'] [data-item-integration='${integration.slug}'] {`,
    );
    lines.push('  display: block;');
    lines.push('}');
  }
  lines.push('');
  lines.push('/* ─── Hide group labels when all pages in the group are gated out ───────── */');
  // For each (group, integration) pair where every page in the group is gated
  // out of that integration, hide the group label/container under that body.
  // Sidebar groups are identified by their kebab-cased name via the
  // `data-group-name` attribute emitted by SidebarGroupItem.
  const emptyByGroup = computeEmptyGroupIntegrations();
  for (const [groupSlug, slugs] of emptyByGroup) {
    for (const intSlug of slugs) {
      lines.push(
        `body[data-integration='${intSlug}'] [data-group-name='${groupSlug}'] {`,
      );
      lines.push('  display: none;');
      lines.push('}');
    }
  }
  lines.push('');

  const filepath = path.join(STYLES_DIR, 'integrations.css');
  fs.writeFileSync(filepath, lines.join('\n'));
  console.log(`✓ Wrote integrations.css with rules for ${integrations.length} integration(s)`);
  if (emptyByGroup.size > 0) {
    const totalRules = Array.from(emptyByGroup.values()).reduce(
      (acc, s) => acc + s.length,
      0,
    );
    console.log(
      `  Hiding ${totalRules} empty (group, integration) pair(s) where gating leaves no supported pages`,
    );
  }
}

console.log('Generating routing from integrations.config.ts...');
generateAliases();
generateDocsJson();
generateIntegrationsCss();
console.log('Done.');
