export {
  type ErrorHandlerResult,
  type BaseErrorContext,
  type CopilotRuntimeError,
  type AgentError,
  type LLMProviderError,
  type ActionExecutionError,
  type NetworkError,
  type RuntimeError,
  type ComponentError,
  type ConcurrencyError,
  type SecurityError,
  type DataProcessingError,
  type ResourceError,
  type IntegrationError,
  isAgentError,
  isLLMProviderError,
  isActionExecutionError,
  isNetworkError,
  isRuntimeError,
  categorizeError,
  createLLMProviderError,
  type ErrorHandler,
  type ErrorCategorizer,
  errorCategorizerRegistry,
} from "@copilotkit/shared";
