import * as path from "node:path";
import type { ComponentWithHooks } from "../types";

export interface RenderAggregatorOptions {
  /** Absolute directory the generated aggregator.tsx will be written to. */
  outDir: string;
  /** Specifier used to import MountCard from the error-boundary module. */
  errorBoundaryModule: string;
}

/**
 * Produces an aggregator.tsx source string that imports every user component
 * carrying CopilotKit hooks and renders each inside a MountCard.
 *
 * Components whose exportName is null are emitted as a skipped comment — the
 * scanner reports them but the aggregator can't import an unexported symbol.
 * Plan #4 can surface these as warnings in the diagnostics panel.
 */
export function renderAggregator(
  components: ComponentWithHooks[],
  opts: RenderAggregatorOptions,
): string {
  const lines: string[] = [
    '/* @generated by packages/vscode-extension/src/extension/playground/codegen. Do not edit. */',
    'import * as React from "react";',
    `import { MountCard } from ${JSON.stringify(opts.errorBoundaryModule)};`,
  ];

  interface Entry {
    component: ComponentWithHooks;
    // Deduped local identifier used inside the aggregator JSX.
    localName: string;
  }
  const entries: Entry[] = [];
  const skipped: ComponentWithHooks[] = [];
  const usedNames = new Set<string>(["MountCard", "React"]);

  for (const c of components) {
    if (c.exportName == null) {
      skipped.push(c);
      continue;
    }
    let local = c.componentName;
    let suffix = 2;
    while (usedNames.has(local)) {
      local = `${c.componentName}_${suffix++}`;
    }
    usedNames.add(local);
    entries.push({ component: c, localName: local });
  }

  for (const { component, localName } of entries) {
    const specifier = toImportSpecifier(opts.outDir, component.filePath);
    if (component.exportName === "default") {
      lines.push(`import ${localName} from ${JSON.stringify(specifier)};`);
    } else if (component.exportName === component.componentName) {
      lines.push(
        `import { ${component.componentName}${
          localName !== component.componentName ? ` as ${localName}` : ""
        } } from ${JSON.stringify(specifier)};`,
      );
    } else {
      // exportName differs from componentName (renamed re-export) —
      // import by the export name and alias to localName.
      lines.push(
        `import { ${component.exportName} as ${localName} } from ${JSON.stringify(
          specifier,
        )};`,
      );
    }
  }

  lines.push("");
  lines.push("export function HooksAggregator(): React.ReactElement {");
  lines.push("  return (");
  lines.push("    <>");

  for (const { component, localName } of entries) {
    const fileEsc = JSON.stringify(component.filePath);
    lines.push(
      `      <MountCard componentName=${JSON.stringify(
        component.componentName,
      )} filePath=${fileEsc}>`,
    );
    lines.push(`        <${localName} />`);
    lines.push(`      </MountCard>`);
  }

  for (const s of skipped) {
    const fileEsc = JSON.stringify(s.filePath);
    lines.push(
      `      {/* skipped: ${s.componentName} (unexported) at ${fileEsc} */}`,
    );
  }

  lines.push("    </>");
  lines.push("  );");
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

/**
 * Produces an ES-module-valid relative specifier (forward slashes, starts with
 * "./" or "../", drops the .tsx/.ts extension — rolldown resolves both forms).
 */
function toImportSpecifier(fromDir: string, toFile: string): string {
  const rel = path.relative(fromDir, toFile).replace(/\\/g, "/");
  const noExt = rel.replace(/\.tsx?$/, "");
  return noExt.startsWith(".") ? noExt : `./${noExt}`;
}
