import * as path from "node:path";
import type {
  CopilotKitProviderLocation,
  CopilotKitProps,
  ProviderChainEntry,
  UnserializableRef,
} from "../types";

export interface RenderEntryOptions {
  provider: CopilotKitProviderLocation;
  ancestors: ProviderChainEntry[];
  /** Specifier used to import the HooksAggregator. */
  aggregatorModule: string;
  /** Absolute directory where the generated entry.tsx will be written. */
  outDir: string;
}

/**
 * Emits the playground entry module. Imports every ancestor provider from
 * the same file as <CopilotKit>, plus CopilotKit(Provider) itself from the
 * user's package, and renders the reconstructed chain wrapping HooksAggregator.
 *
 * Scope: Plan #2 assumes all ancestors live in the same file as <CopilotKit>.
 * Cross-file expansion is a deferred follow-up.
 */
export function renderEntry(opts: RenderEntryOptions): string {
  const { provider, ancestors, aggregatorModule, outDir } = opts;
  const lines: string[] = [
    "/* @generated by packages/vscode-extension/src/extension/playground/codegen. Do not edit. */",
    'import * as React from "react";',
    `import { HooksAggregator } from ${JSON.stringify(aggregatorModule)};`,
    `import { ${provider.importedName} } from ${JSON.stringify(
      provider.importSource,
    )};`,
  ];

  // Same-file ancestors: all share the provider.filePath by construction in
  // Plan #1. Group their tag names into a single import from that file.
  const ancestorNames = Array.from(
    new Set(ancestors.map((a) => a.tagName).filter((n) => /^[A-Z]/.test(n))),
  );
  if (ancestorNames.length > 0) {
    const specifier = toImportSpecifier(outDir, provider.filePath);
    lines.push(
      `import { ${ancestorNames.join(", ")} } from ${JSON.stringify(
        specifier,
      )};`,
    );
  }

  lines.push("");
  lines.push("export function PlaygroundEntry(): React.ReactElement {");
  lines.push("  return (");

  const closeTags: string[] = [];
  let indent = "    ";

  for (const a of ancestors) {
    const props = renderProps(a.props);
    lines.push(`${indent}<${a.tagName}${props}>`);
    closeTags.push(`</${a.tagName}>`);
    indent += "  ";
  }

  const providerProps = renderProps(provider.props);
  lines.push(`${indent}<${provider.importedName}${providerProps}>`);
  indent += "  ";
  lines.push(`${indent}<HooksAggregator />`);
  indent = indent.slice(2);
  lines.push(`${indent}</${provider.importedName}>`);

  for (let i = closeTags.length - 1; i >= 0; i--) {
    indent = indent.slice(2);
    lines.push(`${indent}${closeTags[i]}`);
  }

  lines.push("  );");
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

function renderProps(props: CopilotKitProps): string {
  const parts: string[] = [];
  for (const [name, value] of Object.entries(props)) {
    if (name === "__spread") continue; // skip: spread captured as unserializable
    if (name === "children") continue; // JSX element wraps its own children
    parts.push(" " + renderProp(name, value));
  }
  return parts.join("");
}

function renderProp(
  name: string,
  value:
    | string
    | number
    | boolean
    | null
    | CopilotKitProps
    | CopilotKitProps[]
    | UnserializableRef,
): string {
  if (isUnserializable(value)) {
    return `${name}={${value.source}}`;
  }
  if (value === null) return `${name}={null}`;
  if (typeof value === "string") return `${name}=${JSON.stringify(value)}`;
  if (typeof value === "number" || typeof value === "boolean") {
    return `${name}={${JSON.stringify(value)}}`;
  }
  // Object or array — stringify as-is. JSX expression slot accepts any
  // valid JS expression; JSON is a valid JS literal for primitives + objects.
  return `${name}={${JSON.stringify(value)}}`;
}

function isUnserializable(v: unknown): v is UnserializableRef {
  return (
    typeof v === "object" &&
    v !== null &&
    "__unserializable" in v &&
    (v as { __unserializable: unknown }).__unserializable === true
  );
}

/**
 * Produces an ES-module-valid specifier (forward slashes, drops the .tsx/.ts
 * extension — rolldown resolves both forms).
 *
 * On Windows, `path.relative()` cannot express a cross-drive path as a
 * relative specifier (e.g. from C:\Temp to F:\project). In that case we fall
 * back to an absolute POSIX-style specifier so rolldown can still resolve the
 * file by its on-disk location.
 */
function toImportSpecifier(fromDir: string, toFile: string): string {
  const rel = path.relative(fromDir, toFile);
  // path.relative returns the absolute toFile unchanged when it cannot be
  // expressed as a relative path (cross-drive on Windows). Detect this by
  // checking whether the result is still absolute.
  if (path.isAbsolute(rel)) {
    // Use the absolute path directly, normalised to forward slashes.
    return rel.replace(/\\/g, "/").replace(/\.tsx?$/, "");
  }
  const noExt = rel.replace(/\\/g, "/").replace(/\.tsx?$/, "");
  return noExt.startsWith(".") ? noExt : `./${noExt}`;
}
