import * as path from "node:path";
import type {
  CopilotKitProviderLocation,
  CopilotKitProps,
  ProviderChainEntry,
  UnserializableRef,
} from "../types";

export interface RenderEntryOptions {
  provider: CopilotKitProviderLocation;
  ancestors: ProviderChainEntry[];
  /** Specifier used to import the HooksAggregator. */
  aggregatorModule: string;
  /** Absolute directory where the generated entry.tsx will be written. */
  outDir: string;
}

/**
 * Emits the playground entry module. Imports every ancestor provider using
 * the real import source resolved from the user's file, plus CopilotKit(Provider)
 * itself from the user's package, and renders the reconstructed chain wrapping
 * HooksAggregator.
 *
 * Ancestors with no resolvable import source (locally declared in the user's
 * file) are skipped with a comment — the wrapper is omitted rather than
 * generating broken code.
 */
export function renderEntry(opts: RenderEntryOptions): string {
  const { provider, ancestors, aggregatorModule, outDir } = opts;

  const lines: string[] = [
    "/* @generated by packages/vscode-extension/src/extension/playground/codegen. Do not edit. */",
    'import * as React from "react";',
    `import { HooksAggregator } from ${JSON.stringify(aggregatorModule)};`,
    `import { ${provider.importedName} } from ${JSON.stringify(
      provider.importSource,
    )};`,
  ];

  // Emit per-ancestor imports using the user's real import specifier.
  // Ancestors we can't resolve (locally declared, not exported) are skipped
  // with a comment — render falls through as if the wrapper was omitted.
  interface Renderable {
    ancestor: ProviderChainEntry;
    /** Local identifier used inside the generated JSX. */
    localName: string;
  }
  const renderables: Renderable[] = [];
  const skipped: ProviderChainEntry[] = [];
  const usedNames = new Set<string>([
    "HooksAggregator",
    "React",
    provider.importedName,
  ]);

  for (const a of ancestors) {
    // Lowercased tag names are HTML elements (<div>, <span>) — not providers.
    if (!/^[A-Z]/.test(a.tagName)) continue;
    if (a.importSource == null || a.importedName == null) {
      skipped.push(a);
      continue;
    }

    // Dedupe local name against imports already in scope.
    let local = a.tagName;
    let suffix = 2;
    while (usedNames.has(local)) {
      local = `${a.tagName}_${suffix++}`;
    }
    usedNames.add(local);

    const specifier = rewriteImportSpecifier(
      a.importSource,
      a.filePath,
      outDir,
    );
    if (a.isDefaultImport) {
      lines.push(`import ${local} from ${JSON.stringify(specifier)};`);
    } else if (a.importedName === a.tagName) {
      lines.push(
        `import { ${a.tagName}${
          local !== a.tagName ? ` as ${local}` : ""
        } } from ${JSON.stringify(specifier)};`,
      );
    } else {
      // User wrote `import { X as Y }` — reproduce the alias.
      lines.push(
        `import { ${a.importedName} as ${local} } from ${JSON.stringify(
          specifier,
        )};`,
      );
    }

    renderables.push({ ancestor: a, localName: local });
  }

  lines.push("");
  lines.push("export function PlaygroundEntry(): React.ReactElement {");
  lines.push("  return (");

  const closeTags: string[] = [];
  let indent = "    ";

  for (const s of skipped) {
    lines.push(
      `${indent}{/* skipped ancestor: ${s.tagName} (locally declared in ${
        s.filePath
      }, not exported) */}`,
    );
  }

  for (const { ancestor, localName } of renderables) {
    const props = renderProps(ancestor.props);
    lines.push(`${indent}<${localName}${props}>`);
    closeTags.push(`</${localName}>`);
    indent += "  ";
  }

  const providerProps = renderProps(provider.props);
  lines.push(`${indent}<${provider.importedName}${providerProps}>`);
  indent += "  ";
  lines.push(`${indent}<HooksAggregator />`);
  indent = indent.slice(2);
  lines.push(`${indent}</${provider.importedName}>`);

  for (let i = closeTags.length - 1; i >= 0; i--) {
    indent = indent.slice(2);
    lines.push(`${indent}${closeTags[i]}`);
  }

  lines.push("  );");
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

/**
 * Resolves the user's import specifier into something valid from outDir.
 * - Non-relative specifiers (npm packages, scoped packages) pass through.
 * - Relative specifiers are resolved against the importer's directory and
 *   re-expressed relative to outDir via toImportSpecifier.
 */
function rewriteImportSpecifier(
  userSpecifier: string,
  importerFilePath: string,
  outDir: string,
): string {
  if (!userSpecifier.startsWith(".")) return userSpecifier;
  const absolute = path.resolve(path.dirname(importerFilePath), userSpecifier);
  return toImportSpecifier(outDir, absolute);
}

function renderProps(props: CopilotKitProps): string {
  const parts: string[] = [];
  for (const [name, value] of Object.entries(props)) {
    if (name === "__spread") continue; // skip: spread captured as unserializable
    if (name === "children") continue; // JSX element wraps its own children
    parts.push(" " + renderProp(name, value));
  }
  return parts.join("");
}

function renderProp(
  name: string,
  value:
    | string
    | number
    | boolean
    | null
    | CopilotKitProps
    | CopilotKitProps[]
    | UnserializableRef,
): string {
  if (isUnserializable(value)) {
    return `${name}={${value.source}}`;
  }
  if (value === null) return `${name}={null}`;
  if (typeof value === "string") return `${name}=${JSON.stringify(value)}`;
  if (typeof value === "number" || typeof value === "boolean") {
    return `${name}={${JSON.stringify(value)}}`;
  }
  // Object or array — stringify as-is. JSX expression slot accepts any
  // valid JS expression; JSON is a valid JS literal for primitives + objects.
  return `${name}={${JSON.stringify(value)}}`;
}

function isUnserializable(v: unknown): v is UnserializableRef {
  return (
    typeof v === "object" &&
    v !== null &&
    "__unserializable" in v &&
    (v as { __unserializable: unknown }).__unserializable === true
  );
}

/**
 * Produces an ES-module-valid specifier (forward slashes, drops the .tsx/.ts
 * extension — rolldown resolves both forms).
 *
 * On Windows, `path.relative()` cannot express a cross-drive path as a
 * relative specifier (e.g. from C:\Temp to F:\project). In that case we fall
 * back to an absolute POSIX-style specifier so rolldown can still resolve the
 * file by its on-disk location.
 */
function toImportSpecifier(fromDir: string, toFile: string): string {
  const rel = path.relative(fromDir, toFile);
  // path.relative returns the absolute toFile unchanged when it cannot be
  // expressed as a relative path (cross-drive on Windows). Detect this by
  // checking whether the result is still absolute.
  if (path.isAbsolute(rel)) {
    // Use the absolute path directly, normalised to forward slashes.
    return rel.replace(/\\/g, "/").replace(/\.tsx?$/, "");
  }
  const noExt = rel.replace(/\\/g, "/").replace(/\.tsx?$/, "");
  return noExt.startsWith(".") ? noExt : `./${noExt}`;
}
