"""LangGraph agent backing the Agentic Generative UI demo.

This agent demonstrates **agent-state-driven Generative UI**: the agent plans
and executes a multi-step task, publishing a structured `steps` list to its
LangGraph state as it progresses. The frontend subscribes to that state via
`useCoAgentStateRender` and renders an inline steps tracker that updates in
real time as each step flips from `pending` -> `running` -> `completed`.

Why a custom StateGraph (not `create_agent`):
  LangGraph only publishes state on node boundaries. To drive an inline
  progress tracker from a single node, we use `copilotkit_emit_state` which
  forces an interim state broadcast to the UI between steps. The step plan
  is generated by an LLM so the tracker reflects the user's actual request.
"""

from __future__ import annotations

import asyncio
import json
from typing import Any, List, Literal, TypedDict

from langchain_core.messages import AIMessage, HumanMessage, SystemMessage
from langchain_core.runnables import RunnableConfig
from langchain_openai import ChatOpenAI
from langgraph.graph import END, START, StateGraph

from copilotkit import CopilotKitState
from copilotkit.langgraph import copilotkit_customize_config, copilotkit_emit_state


class Step(TypedDict):
    description: str
    status: Literal["pending", "running", "completed"]


class AgentState(CopilotKitState):
    # Agent-driven step plan rendered in-chat by `useCoAgentStateRender`.
    steps: List[Step]


PLANNER_SYSTEM_PROMPT = """You are a planning assistant. Given a user's request, return a JSON array
of 3-5 short, actionable step descriptions (imperative, present tense, under 8 words each)
that together accomplish the request. Return ONLY the JSON array, no prose, no code fences.

Example output for "Plan a product launch":
["Define launch goals and KPIs", "Prepare marketing materials", "Coordinate with engineering team", "Schedule press briefings", "Publish announcement"]"""


SUMMARY_SYSTEM_PROMPT = """You are a helpful assistant. You have just finished executing a multi-step plan
for the user. Write a friendly 1-2 sentence summary confirming what was done, referencing the
completed steps. Do NOT re-enumerate the steps -- the UI already shows them."""


async def run_plan_node(state: AgentState, config: RunnableConfig) -> dict:
    """Plan -> execute -> summarize, emitting step-by-step state updates."""
    planner = ChatOpenAI(model="gpt-4o-mini", temperature=0)

    # Pull the last user message out of the conversation.
    last_user_msg = ""
    for m in reversed(state.get("messages", [])):
        if isinstance(m, HumanMessage):
            last_user_msg = m.content if isinstance(m.content, str) else str(m.content)
            break
    if not last_user_msg:
        last_user_msg = "Describe a simple multi-step task."

    # 1. Ask the LLM to plan 3-5 steps. Suppress message + tool-call streaming
    #    on this call so the planner's raw JSON never leaks into the chat.
    silent_config = copilotkit_customize_config(
        config, emit_messages=False, emit_tool_calls=False
    )
    plan_resp = await planner.ainvoke(
        [
            SystemMessage(content=PLANNER_SYSTEM_PROMPT),
            HumanMessage(content=last_user_msg),
        ],
        silent_config,
    )
    raw = plan_resp.content if isinstance(plan_resp.content, str) else str(plan_resp.content)
    try:
        descriptions = json.loads(raw.strip())
        if not isinstance(descriptions, list):
            raise ValueError("plan not a list")
        descriptions = [str(d) for d in descriptions][:5]
    except Exception:
        # Fallback plan so the UI still has something to render.
        descriptions = [
            "Understand the request",
            "Gather relevant information",
            "Execute the core action",
            "Summarize the result",
        ]

    # 2. Publish the initial plan (all pending) so the UI shows the skeleton.
    steps: List[Step] = [
        {"description": d, "status": "pending"} for d in descriptions
    ]
    await copilotkit_emit_state(config, {"steps": steps})

    # 3. Walk the steps one at a time, flipping status and re-emitting.
    for idx in range(len(steps)):
        steps[idx]["status"] = "running"
        await copilotkit_emit_state(config, {"steps": steps})
        # Visible pacing so the UI transitions are clearly observable.
        await asyncio.sleep(1.2)
        steps[idx]["status"] = "completed"
        await copilotkit_emit_state(config, {"steps": steps})

    # 4. Ask the LLM for a short wrap-up that goes into the chat transcript.
    summarizer = ChatOpenAI(model="gpt-4o-mini", temperature=0.3)
    step_list = ", ".join(f"{i + 1}) {s['description']}" for i, s in enumerate(steps))
    summary_resp = await summarizer.ainvoke(
        [
            SystemMessage(content=SUMMARY_SYSTEM_PROMPT),
            HumanMessage(
                content=(
                    f'Original request: "{last_user_msg}".\n'
                    f"Completed steps: {step_list}."
                )
            ),
        ]
    )
    summary_text = (
        summary_resp.content
        if isinstance(summary_resp.content, str)
        else str(summary_resp.content)
    )

    return {
        "steps": steps,
        "messages": [AIMessage(content=summary_text)],
    }


workflow = StateGraph(AgentState)
workflow.add_node("plan", run_plan_node)
workflow.add_edge(START, "plan")
workflow.add_edge("plan", END)
graph = workflow.compile()
