import type { Metadata } from "next";

import { CopilotKit } from "@copilotkit/react-core/v2";
import "./globals.css";
import "@copilotkit/react-core/v2/styles.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"antialiased"}>
        {/* Force REST (path-based) transport so runtime-info and the threads
            REST API both hit the multi-route endpoint. Auto-detect probes
            GET /info first, which races the lazily-compiled API route in
            `next dev` and can fall back to single-route (no threads support). */}
        <CopilotKit
          runtimeUrl="/api/copilotkit"
          useSingleEndpoint={false}
        >
          {children}
        </CopilotKit>
      </body>
    </html>
  );
}
