import { test, expect } from "@playwright/test";

/**
 * Regression coverage for the byoc-hashbrown demo's three pre-seeded
 * suggestion pills. The user-reported regression that motivated this
 * suite: clicking the "Sales dashboard" pill produced no DOM at all
 * while the other two pills rendered their respective charts. We click
 * each pill in turn and assert the catalog components surface in the
 * structured-output area within the streaming budget. If the hashbrown
 * renderer drops a component (or the agent stops emitting one of the
 * tag families) the matching test fails immediately.
 *
 * Generated by showcase/scripts/generate-byoc-regression-tests.sh —
 * edit the template there, not the per-integration copies.
 */
const SUGGESTION_TIMEOUT_MS = 60_000;

test.describe("BYOC Hashbrown — pill suggestion regression", () => {
  test.beforeEach(async ({ page }) => {
    await page.goto("/demos/byoc-hashbrown");
  });

  test("page loads with header and all three suggestion pills", async ({
    page,
  }) => {
    await expect(
      page.getByRole("heading", { name: "BYOC: Hashbrown" }),
    ).toBeVisible();
    await expect(
      page.getByRole("button", { name: "Sales dashboard" }),
    ).toBeVisible();
    await expect(
      page.getByRole("button", { name: "Revenue by category" }),
    ).toBeVisible();
    await expect(
      page.getByRole("button", { name: "Expense trend" }),
    ).toBeVisible();
  });

  test("Sales dashboard pill renders metric card + pie + bar", async ({
    page,
  }) => {
    await page.getByRole("button", { name: "Sales dashboard" }).click();

    // The fixture-backed Sales dashboard response includes a metric
    // card, a pie chart, and a bar chart. Assert all three so a
    // regression that drops any one of them is caught — the original
    // bug dropped all three at once.
    await expect(
      page.locator('[data-testid="metric-card"]').first(),
    ).toBeVisible({ timeout: SUGGESTION_TIMEOUT_MS });
    await expect(page.locator('[data-testid="pie-chart"]').first()).toBeVisible(
      { timeout: SUGGESTION_TIMEOUT_MS },
    );
    await expect(page.locator('[data-testid="bar-chart"]').first()).toBeVisible(
      { timeout: SUGGESTION_TIMEOUT_MS },
    );
  });

  test("Revenue by category pill renders a pie chart", async ({ page }) => {
    await page.getByRole("button", { name: "Revenue by category" }).click();
    await expect(page.locator('[data-testid="pie-chart"]').first()).toBeVisible(
      { timeout: SUGGESTION_TIMEOUT_MS },
    );
  });

  test("Expense trend pill renders a bar chart", async ({ page }) => {
    await page.getByRole("button", { name: "Expense trend" }).click();
    await expect(page.locator('[data-testid="bar-chart"]').first()).toBeVisible(
      { timeout: SUGGESTION_TIMEOUT_MS },
    );
  });
});
