// const getRandomDate = (start: Date, end: Date) => {
//     return new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()));
// };

// const now = new Date();
// const thirtyDaysAgo = new Date(now.getTime() - 29 * 24 * 60 * 60 * 1000);

const prData = [
    {
        id: 'PR01',
        title: 'Implement user authentication flow',
        status: 'approved',
        assignedReviewer: 'john.doe@got.com',
        assignedTester: 'jane.smith@got.com',
        daysSinceStatusChange: 2,
        createdAt: '2025-04-28T14:06:36.848Z',
        updatedAt: '2025-04-29T00:46:50.492Z',
        userId: 1,
        author: 'Jon.snow@got.com',
        repository: 'frontend',
        branch: 'feature/auth-flow'
    },
    {
        id: 'PR02',
        title: 'Fix navigation menu responsiveness',
        status: 'approved',
        assignedReviewer: 'mike.johnson@got.com',
        assignedTester: 'sarah.wilson@got.com',
        daysSinceStatusChange: 1,
        createdAt: '2025-05-18T18:07:28.478Z',
        updatedAt: '2025-05-20T09:54:20.222Z',
        userId: 2,
        author: 'robert.baratheon@got.com',
        repository: 'frontend',
        branch: 'fix/nav-responsive'
    },
    {
        id: 'PR03',
        title: 'Add unit tests for payment module',
        status: 'needs_revision',
        assignedReviewer: 'emma.davis@got.com',
        assignedTester: 'tom.brown@got.com',
        daysSinceStatusChange: 3,
        createdAt: '2025-05-06T08:03:40.531Z',
        updatedAt: '2025-05-09T00:56:28.382Z',
        userId: 3,
        author: 'ned.stark@got.com',
        repository: 'backend',
        branch: 'feature/payment-tests'
    },
    {
        id: 'PR04',
        title: 'Update API documentation',
        status: 'merged',
        assignedReviewer: 'lisa.martin@got.com',
        assignedTester: 'chris.taylor@got.com',
        daysSinceStatusChange: 0,
        createdAt: '2025-05-20T10:26:36.824Z',
        updatedAt: '2025-05-20T10:38:58.474Z',
        userId: 4,
        author: 'cersei.lannister@got.com',
        repository: 'docs',
        branch: 'update/api-docs'
    },
    {
        id: 'PR05',
        title: 'Implement dark mode toggle',
        status: 'in_review',
        assignedReviewer: 'alex.wright@got.com',
        assignedTester: 'olivia.parker@got.com',
        daysSinceStatusChange: 1,
        createdAt: '2025-05-16T13:08:26.105Z',
        updatedAt: '2025-05-20T01:59:51.260Z',
        userId: 5,
        author: 'tyrion.lannister@got.com',
        repository: 'frontend',
        branch: 'feature/dark-mode'
    },
    {
        id: 'PR06',
        title: 'Implement dragon animation effects',
        status: 'needs_revision',
        assignedReviewer: 'mike.johnson@got.com',
        assignedTester: 'sarah.wilson@got.com',
        daysSinceStatusChange: 2,
        createdAt: '2025-05-06T00:53:38.487Z',
        updatedAt: '2025-05-20T07:03:01.211Z',
        userId: 1,
        author: 'Jon.snow@got.com',
        repository: 'frontend',
        branch: 'feature/dragon-animations'
    },
    {
        id: 'PR07',
        title: 'Add winter theme to UI components',
        status: 'needs_revision',
        assignedReviewer: 'emma.davis@got.com',
        assignedTester: 'tom.brown@got.com',
        daysSinceStatusChange: 1,
        createdAt: '2025-05-17T06:09:50.460Z',
        updatedAt: '2025-05-20T08:24:49.044Z',
        userId: 2,
        author: 'robert.baratheon@got.com',
        repository: 'frontend',
        branch: 'feature/winter-theme'
    },
    {
        id: 'PR08',
        title: 'Implement castle defense system',
        status: 'approved',
        assignedReviewer: 'lisa.martin@got.com',
        assignedTester: 'chris.taylor@got.com',
        daysSinceStatusChange: 0,
        createdAt: '2025-05-13T01:51:21.363Z',
        updatedAt: '2025-05-20T09:43:41.235Z',
        userId: 3,
        author: 'ned.stark@got.com',
        repository: 'backend',
        branch: 'feature/castle-defense'
    },
    {
        id: 'PR09',
        title: 'Add wildfire explosion effects',
        status: 'in_review',
        assignedReviewer: 'alex.wright@got.com',
        assignedTester: 'olivia.parker@got.com',
        daysSinceStatusChange: 3,
        createdAt: '2025-04-23T04:03:19.518Z',
        updatedAt: '2025-05-17T01:50:20.516Z',
        userId: 4,
        author: 'cersei.lannister@got.com',
        repository: 'frontend',
        branch: 'feature/wildfire-effects'
    },
    {
        id: 'PR10',
        title: 'Implement faceless man disguise system',
        status: 'merged',
        assignedReviewer: 'john.doe@got.com',
        assignedTester: 'jane.smith@got.com',
        daysSinceStatusChange: 0,
        createdAt: '2025-05-12T12:45:09.329Z',
        updatedAt: '2025-05-16T19:39:11.870Z',
        userId: 5,
        author: 'tyrion.lannister@got.com',
        repository: 'backend',
        branch: 'feature/faceless-man'
    },
    {
        id: 'PR11',
        title: 'Add night watch notification system',
        status: 'in_review',
        assignedReviewer: 'mike.johnson@got.com',
        assignedTester: 'sarah.wilson@got.com',
        daysSinceStatusChange: 1,
        createdAt: '2025-04-29T20:48:56.285Z',
        updatedAt: '2025-05-19T15:20:47.345Z',
        userId: 1,
        author: 'Jon.snow@got.com',
        repository: 'backend',
        branch: 'feature/night-watch'
    },
    {
        id: 'PR12',
        title: 'Implement tournament bracket system',
        status: 'needs_revision',
        assignedReviewer: 'emma.davis@got.com',
        assignedTester: 'tom.brown@got.com',
        daysSinceStatusChange: 2,
        createdAt: '2025-05-08T07:38:22.869Z',
        updatedAt: '2025-05-14T22:10:09.651Z',
        userId: 2,
        author: 'robert.baratheon@got.com',
        repository: 'backend',
        branch: 'feature/tournament'
    },
    {
        id: 'PR13',
        title: 'Add direwolf companion feature',
        status: 'approved',
        assignedReviewer: 'lisa.martin@got.com',
        assignedTester: 'chris.taylor@got.com',
        daysSinceStatusChange: 0,
        createdAt: '2025-04-22T09:10:30.873Z',
        updatedAt: '2025-05-08T03:47:55.292Z',
        userId: 3,
        author: 'ned.stark@got.com',
        repository: 'frontend',
        branch: 'feature/direwolf'
    },
    {
        id: 'PR14',
        title: 'Implement iron bank transaction system',
        status: 'in_review',
        assignedReviewer: 'alex.wright@got.com',
        assignedTester: 'olivia.parker@got.com',
        daysSinceStatusChange: 1,
        createdAt: '2025-05-04T20:51:45.581Z',
        updatedAt: '2025-05-05T16:42:48.045Z',
        userId: 4,
        author: 'cersei.lannister@got.com',
        repository: 'backend',
        branch: 'feature/iron-bank'
    },
    {
        id: 'PR15',
        title: 'Add wine cellar management system',
        status: 'merged',
        assignedReviewer: 'john.doe@got.com',
        assignedTester: 'jane.smith@got.com',
        daysSinceStatusChange: 0,
        createdAt: '2025-05-19T21:18:36.223Z',
        updatedAt: '2025-05-20T09:21:57.688Z',
        userId: 5,
        author: 'tyrion.lannister@got.com',
        repository: 'backend',
        branch: 'feature/wine-cellar'
    },
    {
        id: 'PR16',
        title: 'Implement raven messaging system',
        status: 'merged',
        assignedReviewer: 'mike.johnson@got.com',
        assignedTester: 'sarah.wilson@got.com',
        daysSinceStatusChange: 1,
        createdAt: '2025-05-10T21:05:25.331Z',
        updatedAt: '2025-05-11T12:43:30.458Z',
        userId: 1,
        author: 'Jon.snow@got.com',
        repository: 'backend',
        branch: 'feature/raven-messaging'
    },
    {
        id: 'PR17',
        title: 'Add battle strategy planning interface',
        status: 'needs_revision',
        assignedReviewer: 'emma.davis@got.com',
        assignedTester: 'tom.brown@got.com',
        daysSinceStatusChange: 2,
        createdAt: '2025-05-17T15:07:45.416Z',
        updatedAt: '2025-05-20T06:25:16.080Z',
        userId: 2,
        author: 'robert.baratheon@got.com',
        repository: 'frontend',
        branch: 'feature/battle-strategy'
    },
    {
        id: 'PR18',
        title: 'Implement weirwood tree visualization',
        status: 'approved',
        assignedReviewer: 'lisa.martin@got.com',
        assignedTester: 'chris.taylor@got.com',
        daysSinceStatusChange: 0,
        createdAt: '2025-04-24T10:33:18.184Z',
        updatedAt: '2025-05-08T04:49:40.810Z',
        userId: 3,
        author: 'ned.stark@got.com',
        repository: 'frontend',
        branch: 'feature/weirwood-viz'
    },
    {
        id: 'PR19',
        title: 'Add wildfire safety protocols',
        status: 'in_review',
        assignedReviewer: 'alex.wright@got.com',
        assignedTester: 'olivia.parker@got.com',
        daysSinceStatusChange: 1,
        createdAt: '2025-05-09T21:00:32.630Z',
        updatedAt: '2025-05-13T14:59:52.092Z',
        userId: 4,
        author: 'cersei.lannister@got.com',
        repository: 'backend',
        branch: 'feature/wildfire-safety'
    },
    {
        id: 'PR20',
        title: 'Implement hand of the king dashboard',
        status: 'merged',
        assignedReviewer: 'john.doe@got.com',
        assignedTester: 'jane.smith@got.com',
        daysSinceStatusChange: 0,
        createdAt: '2025-04-23T15:12:29.420Z',
        updatedAt: '2025-05-07T08:42:28.465Z',
        userId: 5,
        author: 'tyrion.lannister@got.com',
        repository: 'frontend',
        branch: 'feature/hand-dashboard'
    },
    {
        id: 'PR21',
        title: 'Implement White Walker detection system',
        status: 'in_review',
        assignedReviewer: 'emma.davis@got.com',
        assignedTester: 'jane.smith@got.com',
        daysSinceStatusChange: 1,
        createdAt: '2025-05-16T03:30:43.409Z',
        updatedAt: '2025-05-18T10:03:07.670Z',
        userId: 1,
        author: 'Jon.snow@got.com',
        repository: 'backend',
        branch: 'feature/white-walker-detection'
    },
    {
        id: 'PR22',
        title: 'Add Longclaw sword animation effects',
        status: 'needs_revision',
        assignedReviewer: 'lisa.martin@got.com',
        assignedTester: 'sarah.wilson@got.com',
        daysSinceStatusChange: 2,
        createdAt: '2025-04-22T18:41:32.868Z',
        updatedAt: '2025-05-18T04:36:14.176Z',
        userId: 1,
        author: 'Jon.snow@got.com',
        repository: 'frontend',
        branch: 'feature/longclaw-animations'
    },
    {
        id: 'PR23',
        title: "Implement Night's Watch oath system",
        status: 'approved',
        assignedReviewer: 'alex.wright@got.com',
        assignedTester: 'tom.brown@got.com',
        daysSinceStatusChange: 0,
        createdAt: '2025-04-28T23:05:34.603Z',
        updatedAt: '2025-05-13T01:31:53.776Z',
        userId: 1,
        author: 'Jon.snow@got.com',
        repository: 'backend',
        branch: 'feature/nights-watch-oath'
    },
    {
        id: 'PR24',
        title: 'Add Wall defense monitoring system',
        status: 'in_review',
        assignedReviewer: 'john.doe@got.com',
        assignedTester: 'chris.taylor@got.com',
        daysSinceStatusChange: 1,
        createdAt: '2025-05-17T03:43:15.630Z',
        updatedAt: '2025-05-17T08:18:44.916Z',
        userId: 1,
        author: 'Jon.snow@got.com',
        repository: 'backend',
        branch: 'feature/wall-defense'
    },
    {
        id: 'PR25',
        title: 'Implement wildling tracking system',
        status: 'needs_revision',
        assignedReviewer: 'mike.johnson@got.com',
        assignedTester: 'olivia.parker@got.com',
        daysSinceStatusChange: 2,
        createdAt: '2025-04-30T01:18:12.225Z',
        updatedAt: '2025-05-06T14:40:45.532Z',
        userId: 1,
        author: 'Jon.snow@got.com',
        repository: 'backend',
        branch: 'feature/wildling-tracking'
    },
    {
        id: 'PR26',
        title: 'Add Ghost companion interface',
        status: 'merged',
        assignedReviewer: 'emma.davis@got.com',
        assignedTester: 'jane.smith@got.com',
        daysSinceStatusChange: 0,
        createdAt: '2025-05-05T23:21:48.140Z',
        updatedAt: '2025-05-17T18:28:06.801Z',
        userId: 1,
        author: 'Jon.snow@got.com',
        repository: 'frontend',
        branch: 'feature/ghost-interface'
    },
    {
        id: 'PR27',
        title: 'Implement dragonglass inventory system',
        status: 'in_review',
        assignedReviewer: 'lisa.martin@got.com',
        assignedTester: 'sarah.wilson@got.com',
        daysSinceStatusChange: 1,
        createdAt: '2025-05-16T20:24:21.380Z',
        updatedAt: '2025-05-17T23:23:34.659Z',
        userId: 1,
        author: 'Jon.snow@got.com',
        repository: 'backend',
        branch: 'feature/dragonglass-inventory'
    },
    {
        id: 'PR28',
        title: 'Add Castle Black weather monitoring',
        status: 'needs_revision',
        assignedReviewer: 'alex.wright@got.com',
        assignedTester: 'tom.brown@got.com',
        daysSinceStatusChange: 2,
        createdAt: '2025-05-09T15:42:22.687Z',
        updatedAt: '2025-05-13T02:28:53.353Z',
        userId: 1,
        author: 'Jon.snow@got.com',
        repository: 'frontend',
        branch: 'feature/castle-black-weather'
    },
    {
        id: 'PR29',
        title: 'Implement warg connection system',
        status: 'approved',
        assignedReviewer: 'john.doe@got.com',
        assignedTester: 'chris.taylor@got.com',
        daysSinceStatusChange: 0,
        createdAt: '2025-04-23T08:22:24.456Z',
        updatedAt: '2025-05-04T10:07:40.466Z',
        userId: 1,
        author: 'Jon.snow@got.com',
        repository: 'backend',
        branch: 'feature/warg-connection'
    },
    {
        id: 'PR30',
        title: 'Add Valyrian steel tracking system',
        status: 'in_review',
        assignedReviewer: 'mike.johnson@got.com',
        assignedTester: 'olivia.parker@got.com',
        daysSinceStatusChange: 1,
        createdAt: '2025-05-07T22:46:41.720Z',
        updatedAt: '2025-05-19T00:30:19.530Z',
        userId: 1,
        author: 'Jon.snow@got.com',
        repository: 'backend',
        branch: 'feature/valyrian-steel-tracking'
    },
    {
        id: 'PR31',
        title: 'Implement Night King detection algorithm',
        status: 'needs_revision',
        assignedReviewer: 'emma.davis@got.com',
        assignedTester: 'jane.smith@got.com',
        daysSinceStatusChange: 2,
        createdAt: '2025-05-01T03:38:23.701Z',
        updatedAt: '2025-05-03T18:21:02.544Z',
        userId: 1,
        author: 'Jon.snow@got.com',
        repository: 'backend',
        branch: 'feature/night-king-detection'
    },
    {
        id: 'PR32',
        title: 'Add Winterfell defense protocols',
        status: 'merged',
        assignedReviewer: 'lisa.martin@got.com',
        assignedTester: 'sarah.wilson@got.com',
        daysSinceStatusChange: 0,
        createdAt: '2025-04-22T04:35:07.999Z',
        updatedAt: '2025-05-15T15:06:51.091Z',
        userId: 1,
        author: 'Jon.snow@got.com',
        repository: 'frontend',
        branch: 'feature/winterfell-defense'
    },
    {
        id: 'PR33',
        title: 'Implement dragon riding controls',
        status: 'in_review',
        assignedReviewer: 'alex.wright@got.com',
        assignedTester: 'tom.brown@got.com',
        daysSinceStatusChange: 1,
        createdAt: '2025-04-24T21:14:36.134Z',
        updatedAt: '2025-05-15T15:20:56.046Z',
        userId: 1,
        author: 'Jon.snow@got.com',
        repository: 'frontend',
        branch: 'feature/dragon-riding'
    },
    {
        id: 'PR34',
        title: 'Add Stark family tree visualization',
        status: 'needs_revision',
        assignedReviewer: 'john.doe@got.com',
        assignedTester: 'chris.taylor@got.com',
        daysSinceStatusChange: 2,
        createdAt: '2025-05-10T22:07:41.636Z',
        updatedAt: '2025-05-17T10:06:14.974Z',
        userId: 1,
        author: 'Jon.snow@got.com',
        repository: 'frontend',
        branch: 'feature/stark-family-tree'
    },
    {
        id: 'PR35',
        title: 'Implement Northern alliance management',
        status: 'approved',
        assignedReviewer: 'mike.johnson@got.com',
        assignedTester: 'olivia.parker@got.com',
        daysSinceStatusChange: 0,
        createdAt: '2025-05-17T06:41:12.294Z',
        updatedAt: '2025-05-18T00:23:34.264Z',
        userId: 1,
        author: 'Jon.snow@got.com',
        repository: 'backend',
        branch: 'feature/northern-alliance'
    }
]

export { prData };

console.log(prData);



