import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Lora } from 'next/font/google'
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });
const lora = Lora({ subsets: ["latin"], variable: "--font-lora" });

export const metadata: Metadata = {
  title: "Storytale AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, lora.variable)}>{children}</body>
    </html>
  );
}
