// Standalone dataset for the Charges page. Kept independent of the seeded
// transaction store (which drives the teach/memory arc) so this richer list can
// grow without touching those fixtures. ~45 charges across categories, vendors,
// teams and statuses, with a wide amount spread so "the 10 most expensive"
// (and the filter/stack-rank flow) is meaningful.

export const CHARGE_CATEGORIES = [
  "Cloud Infrastructure",
  "Advertising",
  "SaaS & Software",
  "Travel",
  "Payroll & Benefits",
  "Office & Facilities",
  "Professional Services",
  "Marketing Events",
  "Hardware",
  "Meals & Entertainment",
] as const;
export type ChargeCategory = (typeof CHARGE_CATEGORIES)[number];

export const CHARGE_TEAMS = [
  "Engineering",
  "Marketing",
  "Sales",
  "Executive",
  "Operations",
  "Finance",
  "People",
] as const;
export type ChargeTeam = (typeof CHARGE_TEAMS)[number];

export const CHARGE_STATUSES = [
  "approved",
  "pending",
  "flagged",
  "over-limit",
] as const;
export type ChargeStatus = (typeof CHARGE_STATUSES)[number];

export interface Charge {
  id: string;
  merchant: string;
  category: ChargeCategory;
  team: ChargeTeam;
  amount: number; // USD, positive = spend
  date: string; // ISO yyyy-mm-dd (2026 Q2)
  status: ChargeStatus;
}

export const CHARGES: Charge[] = [
  // ── Big-ticket (the top of a "most expensive" sort) ──────────────────────
  {
    id: "chg-001",
    merchant: "Amazon Web Services",
    category: "Cloud Infrastructure",
    team: "Engineering",
    amount: 91800,
    date: "2026-06-01",
    status: "over-limit",
  },
  {
    id: "chg-002",
    merchant: "ADP Payroll",
    category: "Payroll & Benefits",
    team: "People",
    amount: 74200,
    date: "2026-06-15",
    status: "approved",
  },
  {
    id: "chg-003",
    merchant: "Wilson Sonsini",
    category: "Professional Services",
    team: "Executive",
    amount: 58400,
    date: "2026-05-22",
    status: "flagged",
  },
  {
    id: "chg-004",
    merchant: "Snowflake",
    category: "Cloud Infrastructure",
    team: "Engineering",
    amount: 43250,
    date: "2026-05-04",
    status: "approved",
  },
  {
    id: "chg-005",
    merchant: "Google Ads",
    category: "Advertising",
    team: "Marketing",
    amount: 38600,
    date: "2026-06-09",
    status: "over-limit",
  },
  {
    id: "chg-006",
    merchant: "Deloitte",
    category: "Professional Services",
    team: "Finance",
    amount: 34900,
    date: "2026-04-28",
    status: "approved",
  },
  {
    id: "chg-007",
    merchant: "Salesforce",
    category: "SaaS & Software",
    team: "Sales",
    amount: 31200,
    date: "2026-05-18",
    status: "approved",
  },
  {
    id: "chg-008",
    merchant: "Meta Ads",
    category: "Advertising",
    team: "Marketing",
    amount: 27450,
    date: "2026-06-11",
    status: "pending",
  },
  {
    id: "chg-009",
    merchant: "Cvent",
    category: "Marketing Events",
    team: "Marketing",
    amount: 24800,
    date: "2026-05-30",
    status: "flagged",
  },
  {
    id: "chg-010",
    merchant: "Microsoft Azure",
    category: "Cloud Infrastructure",
    team: "Engineering",
    amount: 22100,
    date: "2026-04-12",
    status: "approved",
  },
  // ── Mid-tier ─────────────────────────────────────────────────────────────
  {
    id: "chg-011",
    merchant: "Dell Technologies",
    category: "Hardware",
    team: "Operations",
    amount: 18750,
    date: "2026-05-07",
    status: "pending",
  },
  {
    id: "chg-012",
    merchant: "Google Cloud",
    category: "Cloud Infrastructure",
    team: "Engineering",
    amount: 17300,
    date: "2026-06-02",
    status: "approved",
  },
  {
    id: "chg-013",
    merchant: "HubSpot",
    category: "SaaS & Software",
    team: "Marketing",
    amount: 15900,
    date: "2026-04-19",
    status: "approved",
  },
  {
    id: "chg-014",
    merchant: "WeWork",
    category: "Office & Facilities",
    team: "Operations",
    amount: 14200,
    date: "2026-06-01",
    status: "approved",
  },
  {
    id: "chg-015",
    merchant: "LinkedIn Ads",
    category: "Advertising",
    team: "Marketing",
    amount: 12650,
    date: "2026-05-14",
    status: "over-limit",
  },
  {
    id: "chg-016",
    merchant: "Apple",
    category: "Hardware",
    team: "Engineering",
    amount: 11480,
    date: "2026-04-25",
    status: "approved",
  },
  {
    id: "chg-017",
    merchant: "Marriott",
    category: "Travel",
    team: "Sales",
    amount: 9820,
    date: "2026-06-06",
    status: "flagged",
  },
  {
    id: "chg-018",
    merchant: "Datadog",
    category: "Cloud Infrastructure",
    team: "Engineering",
    amount: 8760,
    date: "2026-05-11",
    status: "approved",
  },
  {
    id: "chg-019",
    merchant: "Gusto",
    category: "Payroll & Benefits",
    team: "People",
    amount: 8100,
    date: "2026-04-15",
    status: "approved",
  },
  {
    id: "chg-020",
    merchant: "Delta Air Lines",
    category: "Travel",
    team: "Executive",
    amount: 7450,
    date: "2026-05-27",
    status: "pending",
  },
  {
    id: "chg-021",
    merchant: "Cloudflare",
    category: "Cloud Infrastructure",
    team: "Engineering",
    amount: 6900,
    date: "2026-06-03",
    status: "approved",
  },
  {
    id: "chg-022",
    merchant: "CDW",
    category: "Hardware",
    team: "Operations",
    amount: 6320,
    date: "2026-04-30",
    status: "approved",
  },
  {
    id: "chg-023",
    merchant: "United Airlines",
    category: "Travel",
    team: "Sales",
    amount: 5980,
    date: "2026-06-08",
    status: "flagged",
  },
  {
    id: "chg-024",
    merchant: "Reddit Ads",
    category: "Advertising",
    team: "Marketing",
    amount: 5400,
    date: "2026-05-19",
    status: "approved",
  },
  {
    id: "chg-025",
    merchant: "Hopin",
    category: "Marketing Events",
    team: "Marketing",
    amount: 4950,
    date: "2026-04-22",
    status: "approved",
  },
  {
    id: "chg-026",
    merchant: "Hilton",
    category: "Travel",
    team: "Executive",
    amount: 4380,
    date: "2026-05-25",
    status: "approved",
  },
  {
    id: "chg-027",
    merchant: "GitHub",
    category: "SaaS & Software",
    team: "Engineering",
    amount: 3900,
    date: "2026-06-01",
    status: "approved",
  },
  {
    id: "chg-028",
    merchant: "TikTok Ads",
    category: "Advertising",
    team: "Marketing",
    amount: 3610,
    date: "2026-05-16",
    status: "pending",
  },
  {
    id: "chg-029",
    merchant: "Vercel",
    category: "SaaS & Software",
    team: "Engineering",
    amount: 3200,
    date: "2026-04-18",
    status: "approved",
  },
  {
    id: "chg-030",
    merchant: "Airbnb",
    category: "Travel",
    team: "Sales",
    amount: 2870,
    date: "2026-06-05",
    status: "approved",
  },
  // ── Long tail ────────────────────────────────────────────────────────────
  {
    id: "chg-031",
    merchant: "Notion",
    category: "SaaS & Software",
    team: "Operations",
    amount: 2450,
    date: "2026-05-02",
    status: "approved",
  },
  {
    id: "chg-032",
    merchant: "Figma",
    category: "SaaS & Software",
    team: "Engineering",
    amount: 2180,
    date: "2026-04-11",
    status: "approved",
  },
  {
    id: "chg-033",
    merchant: "Eventbrite",
    category: "Marketing Events",
    team: "Marketing",
    amount: 1990,
    date: "2026-06-07",
    status: "approved",
  },
  {
    id: "chg-034",
    merchant: "Slack",
    category: "SaaS & Software",
    team: "Operations",
    amount: 1720,
    date: "2026-05-09",
    status: "approved",
  },
  {
    id: "chg-035",
    merchant: "Staples",
    category: "Office & Facilities",
    team: "Operations",
    amount: 1440,
    date: "2026-04-16",
    status: "approved",
  },
  {
    id: "chg-036",
    merchant: "Linear",
    category: "SaaS & Software",
    team: "Engineering",
    amount: 1180,
    date: "2026-06-04",
    status: "approved",
  },
  {
    id: "chg-037",
    merchant: "Amazon Business",
    category: "Office & Facilities",
    team: "Operations",
    amount: 960,
    date: "2026-05-13",
    status: "approved",
  },
  {
    id: "chg-038",
    merchant: "Uber",
    category: "Travel",
    team: "Sales",
    amount: 740,
    date: "2026-06-10",
    status: "approved",
  },
  {
    id: "chg-039",
    merchant: "DoorDash",
    category: "Meals & Entertainment",
    team: "Engineering",
    amount: 520,
    date: "2026-05-21",
    status: "approved",
  },
  {
    id: "chg-040",
    merchant: "Sweetgreen",
    category: "Meals & Entertainment",
    team: "People",
    amount: 380,
    date: "2026-04-23",
    status: "approved",
  },
  {
    id: "chg-041",
    merchant: "Uber",
    category: "Travel",
    team: "Executive",
    amount: 290,
    date: "2026-06-12",
    status: "approved",
  },
  {
    id: "chg-042",
    merchant: "Blue Bottle Coffee",
    category: "Meals & Entertainment",
    team: "Marketing",
    amount: 148,
    date: "2026-05-06",
    status: "approved",
  },
  {
    id: "chg-043",
    merchant: "DoorDash",
    category: "Meals & Entertainment",
    team: "Sales",
    amount: 96,
    date: "2026-06-13",
    status: "approved",
  },
  {
    id: "chg-044",
    merchant: "Sweetgreen",
    category: "Meals & Entertainment",
    team: "Engineering",
    amount: 64,
    date: "2026-04-27",
    status: "approved",
  },
  {
    id: "chg-045",
    merchant: "Blue Bottle Coffee",
    category: "Meals & Entertainment",
    team: "Operations",
    amount: 28,
    date: "2026-05-29",
    status: "approved",
  },
];
