// STUB — replaced by B2 merge
/**
 * TypeScript types for catalog.json, generated by generate-registry.ts.
 */

export interface CatalogCell {
  id: string;
  manifestation: "integrated" | "starter";
  integration: string;
  integration_name: string;
  feature: string | null;
  feature_name: string | null;
  status: "wired" | "stub" | "unshipped";
  parity_tier: "reference" | "at_parity" | "partial" | "minimal" | "not_wired";
  max_depth: number;
  category: string | null;
  category_name: string | null;
}

export interface CatalogMetadata {
  reference: string;
  total_cells: number;
  wired: number;
  stub: number;
  unshipped: number;
  generated_at: string;
}

export interface CatalogData {
  metadata: CatalogMetadata;
  cells: CatalogCell[];
}
