import type { z } from "zod";
import {
  appendLearningRunChunkV1Schema,
  commitLearningRunResultV1Schema,
  createLearningRunV1Schema,
  createRegistryRevisionV1Schema,
  evaluateCandidateGatesV1Schema,
  prepareLearningRunV1Schema,
  prepareRegistryCandidateV1Schema,
  publishCandidateV1Schema,
  requestThreadSnapshotBackfillV1Schema,
  startLearningContainerRunV1Schema,
} from "./commands.js";
import {
  blobLocatorV1Schema,
  candidateGateResultV1Schema,
  evidenceLocatorV1Schema,
  evidenceRefV1Schema,
  frozenAvailableSkillV1Schema,
  generatedInsightV1Schema,
  generatedSkillCandidateV1Schema,
  insightAnnotationV1Schema,
  insightArchiveEventV1Schema,
  insightFeedbackV1Schema,
  insightV1Schema,
  learningChunkV1Schema,
  learningContainerV1Schema,
  learningRunExecutionResultV1Schema,
  learningRunJobV1Schema,
  learningRunV1Schema,
  learningWorkflowInputV1Schema,
  learningWorkflowOutputV1Schema,
  normalizedMessageV1Schema,
  normalizedToolCallV1Schema,
  normalizedToolResultV1Schema,
  runSnapshotV1Schema,
  selectedHumanAnnotationV1Schema,
  skillArtifactFileV1Schema,
  skillArtifactManifestV1Schema,
  skillBundleV1Schema,
  skillCandidateV1Schema,
  skillSetProjectionEntryV1Schema,
  skillSetProjectionV1Schema,
  snapshotIdentityV1Schema,
  sourceEventManifestEntryV1Schema,
  threadAssignmentPatchV1Schema,
  threadAssignmentV1Schema,
  toLearningContractJsonSchema,
  workflowThreadV1Schema,
} from "./contracts.js";
import { learningPlatformErrorResponseV1Schema } from "./errors.js";

/** Canonical registry for every public Learning Platform V1 contract. */
export const learningContractSchemas = {
  AppendLearningRunChunkV1: appendLearningRunChunkV1Schema,
  BlobLocatorV1: blobLocatorV1Schema,
  CandidateGateResultV1: candidateGateResultV1Schema,
  CommitLearningRunResultV1: commitLearningRunResultV1Schema,
  CreateLearningRunV1: createLearningRunV1Schema,
  CreateRegistryRevisionV1: createRegistryRevisionV1Schema,
  EvaluateCandidateGatesV1: evaluateCandidateGatesV1Schema,
  EvidenceLocatorV1: evidenceLocatorV1Schema,
  EvidenceRefV1: evidenceRefV1Schema,
  FrozenAvailableSkillV1: frozenAvailableSkillV1Schema,
  GeneratedInsightV1: generatedInsightV1Schema,
  GeneratedSkillCandidateV1: generatedSkillCandidateV1Schema,
  InsightAnnotationV1: insightAnnotationV1Schema,
  InsightArchiveEventV1: insightArchiveEventV1Schema,
  InsightFeedbackV1: insightFeedbackV1Schema,
  InsightV1: insightV1Schema,
  LearningChunkV1: learningChunkV1Schema,
  LearningContainerV1: learningContainerV1Schema,
  LearningPlatformErrorResponseV1: learningPlatformErrorResponseV1Schema,
  LearningRunV1: learningRunV1Schema,
  LearningRunExecutionResultV1: learningRunExecutionResultV1Schema,
  LearningRunJobV1: learningRunJobV1Schema,
  LearningWorkflowInputV1: learningWorkflowInputV1Schema,
  LearningWorkflowOutputV1: learningWorkflowOutputV1Schema,
  NormalizedMessageV1: normalizedMessageV1Schema,
  NormalizedToolCallV1: normalizedToolCallV1Schema,
  NormalizedToolResultV1: normalizedToolResultV1Schema,
  PrepareLearningRunV1: prepareLearningRunV1Schema,
  PrepareRegistryCandidateV1: prepareRegistryCandidateV1Schema,
  PublishCandidateV1: publishCandidateV1Schema,
  RequestThreadSnapshotBackfillV1: requestThreadSnapshotBackfillV1Schema,
  RunSnapshotV1: runSnapshotV1Schema,
  SelectedHumanAnnotationV1: selectedHumanAnnotationV1Schema,
  SkillArtifactFileV1: skillArtifactFileV1Schema,
  SkillArtifactManifestV1: skillArtifactManifestV1Schema,
  SkillBundleV1: skillBundleV1Schema,
  SkillCandidateV1: skillCandidateV1Schema,
  SkillSetProjectionEntryV1: skillSetProjectionEntryV1Schema,
  SkillSetProjectionV1: skillSetProjectionV1Schema,
  SnapshotIdentityV1: snapshotIdentityV1Schema,
  SourceEventManifestEntryV1: sourceEventManifestEntryV1Schema,
  StartLearningContainerRunV1: startLearningContainerRunV1Schema,
  ThreadAssignmentPatchV1: threadAssignmentPatchV1Schema,
  ThreadAssignmentV1: threadAssignmentV1Schema,
  WorkflowThreadV1: workflowThreadV1Schema,
} as const satisfies Readonly<Record<string, z.ZodType>>;

type LearningContractJsonSchemaRegistry = {
  readonly [Name in keyof typeof learningContractSchemas]: ReturnType<
    typeof toLearningContractJsonSchema
  >;
};

/** Language-neutral schemas derived from the complete canonical registry. */
export const learningContractJsonSchemas = Object.fromEntries(
  Object.entries(learningContractSchemas).map(([name, schema]) => [
    name,
    toLearningContractJsonSchema(schema),
  ]),
) as LearningContractJsonSchemaRegistry;
