// @generated by scripts/extract-framework-overviews.ts — do not edit by hand.
import type { FrameworkOverviewData } from "./types";

const data: FrameworkOverviewData = {
  slug: "agent-spec",
  frameworkName: "Open Agent Spec",
  iconKey: "agentspecMark",
  header: "Bring your Open Agent Spec agents to your users",
  subheader:
    "Give your Open Agent Spec agents real user-interactivity using CopilotKit and AG-UI. Build rich, interactive, portable agent-powered applications.",
  bannerVideo:
    "https://cdn.copilotkit.ai/blog/oracle/demo-oracle-spec-dojo.mp4",
  guideLink: "/agent-spec/quickstart",
  initCommand: "npx copilotkit@latest init",
  featuresLink:
    "https://feature-viewer.copilotkit.ai/agent-spec-wayflow/feature/agentic_chat",
  supportedFeatures: [
    {
      title: "Generative UI",
      description:
        "Render your agent's state, progress, outputs, and tool calls with custom UI components in real-time. Bridges the gap between AI agents and user interfaces.",
      documentationLink: "/agent-spec/generative-ui",
      demoLink:
        "https://feature-viewer.copilotkit.ai/agent-spec-wayflow/feature/tool_based_generative_ui",
      videoUrl:
        "https://cdn.copilotkit.ai/docs/copilotkit/videos/coagents/haiku.mp4",
    },
    {
      title: "Human in the Loop",
      description:
        "Empower users to guide agents at key checkpoints. Combine the best of AI and human judgment for more reliable and controllable agent behavior.",
      documentationLink: "/agent-spec/human-in-the-loop",
      demoLink: "https://examples-coagents-ai-travel-app.vercel.app/",
      videoUrl:
        "https://cdn.copilotkit.ai/docs/copilotkit/images/coagents/human-in-the-loop-example.mp4",
    },
  ],
  architectureImage:
    "https://cdn.copilotkit.ai/docs/copilotkit/images/agent-spec/agent-spec-ag-ui-arch.png",
  liveDemos: [],
  hasAfterFeaturesMdx: true,
};

export default data;
