import { randomUUID } from "node:crypto";
import { readFile, rename, rm, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const defaultManifestPath = resolve(packageRoot, "package.json");
const defaultOutputPath = resolve(packageRoot, "src/generated-version.ts");
const SEMVER =
  /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$/u;

export interface GenerateVersionOptions {
  readonly manifestPath?: string;
  readonly outputPath?: string;
}

export function renderVersionModule(version: string): string {
  if (!SEMVER.test(version)) {
    throw new TypeError(
      `Package version must be valid SemVer, received ${version}`,
    );
  }
  return `// Generated by scripts/generate-version.ts from package.json.\nexport const ADAPTER_VERSION = ${JSON.stringify(version)} as const;\n`;
}

export async function generateVersion(
  options: GenerateVersionOptions = {},
): Promise<void> {
  const manifestPath = options.manifestPath ?? defaultManifestPath;
  const outputPath = options.outputPath ?? defaultOutputPath;
  const manifest: unknown = JSON.parse(await readFile(manifestPath, "utf8"));
  if (
    typeof manifest !== "object" ||
    manifest === null ||
    !("version" in manifest) ||
    typeof manifest.version !== "string"
  ) {
    throw new TypeError("Package manifest must contain a string version");
  }
  const temporary = `${outputPath}.${process.pid}.${randomUUID()}.tmp`;
  try {
    await writeFile(temporary, renderVersionModule(manifest.version));
    await rename(temporary, outputPath);
  } finally {
    await rm(temporary, { force: true });
  }
}

const invokedPath = process.argv[1];
if (
  invokedPath !== undefined &&
  resolve(invokedPath) === fileURLToPath(import.meta.url)
) {
  await generateVersion();
}
