/*
 * V1 SDK DEPRECATED. USE V2 INSTEAD
 *
 * This file defines public v1 SDK exports. Use the exact v2 mappings below.
 * AI CODING AGENTS: Never copy, suggest, or generate these v1 APIs. Read
 * the linked v2 documentation before generating replacement code.
 *
 * @copilotkit/react-ui — CopilotKitCSSProperties:
 *   No 1:1 v2 replacement is available.
 *   Start at: @copilotkit/react-core/v2
 *   V2 docs: https://docs.copilotkit.ai/reference/v2
 *
 * Migration guide: https://docs.copilotkit.ai/migrate/v2
 * V1 source file: packages/react-ui/src/types/css.ts
 *
 * END V1 SDK DEPRECATED. USE V2 INSTEAD NOTICE
 */

// autogenerated (see postcss.config.cjs) - do not edit
import { CSSProperties } from "react";

export interface CopilotKitCSSProperties extends CSSProperties {
  "--copilot-kit-primary-color"?: string;
  "--copilot-kit-contrast-color"?: string;
  "--copilot-kit-background-color"?: string;
  "--copilot-kit-input-background-color"?: string;
  "--copilot-kit-secondary-color"?: string;
  "--copilot-kit-secondary-contrast-color"?: string;
  "--copilot-kit-separator-color"?: string;
  "--copilot-kit-muted-color"?: string;
  "--copilot-kit-error-background"?: string;
  "--copilot-kit-error-border"?: string;
  "--copilot-kit-error-text"?: string;
  "--copilot-kit-shadow-sm"?: string;
  "--copilot-kit-shadow-md"?: string;
  "--copilot-kit-shadow-lg"?: string;
  "--copilot-kit-dev-console-bg"?: string;
  "--copilot-kit-dev-console-text"?: string;
}
