export * from "./props";
export { CopilotPopup } from "./Popup";
export { CopilotSidebar } from "./Sidebar";
export { CopilotChat } from "./Chat";
export { CopilotModal } from "./Modal";
export type { CopilotModalProps } from "./Modal";
export { Markdown } from "./Markdown";
export { AssistantMessage } from "./messages/AssistantMessage";
export { UserMessage } from "./messages/UserMessage";
export { ImageRenderer } from "./messages/ImageRenderer";
export { useChatContext } from "./ChatContext";
export { Suggestions as RenderSuggestionsList } from "./Suggestions";
export { Suggestion as RenderSuggestion } from "./Suggestion";
export { suppressDeprecationWarnings } from "./attachment-utils";
