export type {
  FunctionDefinition,
  ToolDefinition,
  FunctionCallHandlerArguments,
  FunctionCallHandler,
  CoAgentStateRenderHandlerArguments,
  CoAgentStateRenderHandler,
  AssistantMessage,
  JSONValue,
  Parameter,
  MappedParameterTypes,
  Action,
  CopilotCloudConfig,
  PartialBy,
  RequiredBy,
  CopilotErrorEvent,
  CopilotRequestContext,
  CopilotErrorHandler,
  ImageData,
  Role,
  SystemMessage,
  DeveloperMessage,
  ToolCall,
  ActivityMessage,
  ReasoningMessage,
  ToolResult,
  AIMessage,
  UserMessage,
  Message,
} from "./types";

export type {
  ComparisonRule,
  LogicalRule,
  ExistenceRule,
  Rule,
  BaseCondition,
  ComparisonCondition,
  LogicalCondition,
  ExistenceCondition,
  Condition,
  JSONSchemaString,
  JSONSchemaNumber,
  JSONSchemaBoolean,
  JSONSchemaObject,
  JSONSchemaArray,
  JSONSchema,
  MaybePromise,
  NonEmptyRecord,
  AgentDescription,
  RuntimeInfo,
} from "./utils";
export {
  executeConditions,
  ConsoleColors,
  ConsoleStyles,
  logCopilotKitPlatformMessage,
  publicApiKeyRequired,
  logStyled,
  styledConsole,
  Severity,
  ErrorVisibility,
  ERROR_NAMES,
  BANNER_ERROR_NAMES,
  COPILOT_CLOUD_ERROR_NAMES,
  CopilotKitErrorCode,
  ERROR_CONFIG,
  CopilotKitError,
  CopilotKitMisuseError,
  CopilotKitVersionMismatchError,
  CopilotKitApiDiscoveryError,
  CopilotKitRemoteEndpointDiscoveryError,
  CopilotKitAgentDiscoveryError,
  CopilotKitLowLevelError,
  ResolvedCopilotKitError,
  ConfigurationError,
  MissingPublicApiKeyError,
  UpgradeRequiredError,
  isStructuredCopilotKitError,
  ensureStructuredError,
  getPossibleVersionMismatch,
  actionParametersToJsonSchema,
  jsonSchemaToActionParameters,
  convertJsonSchemaToZodSchema,
  getZodParameters,
  randomId,
  randomUUID,
  dataToUUID,
  isValidUUID,
  readBody,
  parseJson,
  tryMap,
  isMacOS,
} from "./utils";

export {
  COPILOT_CLOUD_API_URL,
  COPILOT_CLOUD_VERSION,
  COPILOT_CLOUD_CHAT_URL,
  COPILOT_CLOUD_PUBLIC_API_KEY_HEADER,
} from "./constants";

export { isTelemetryDisabled, TelemetryClient } from "./telemetry";

import * as packageJson from "../package.json";
export const COPILOTKIT_VERSION = packageJson.version;
