{{- if and .Values.serviceAccount (and .Values.serviceAccount.create true) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "example-app.serviceAccountName" . }}
  labels:
    {{- include "example-app.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
