"use client";

import Link from "next/link";
import { useAgentContext } from "@copilotkit/react-core/v2";
import { Sparkles, Pin } from "lucide-react";
import { revalidateVantage, useBoards } from "../data/hooks";
import { useVantageHref } from "../href";

export function BoardsPage() {
  const { boards } = useBoards();
  const vantageHref = useVantageHref();

  const pin = async (id: string) => {
    await fetch(`/api/vantage/v1/boards/${id}`, {
      method: "PATCH",
      body: JSON.stringify({ pinned: true }),
    });
    revalidateVantage();
  };

  useAgentContext({
    description:
      "What is visibly on the Boards page: every saved board, which were " +
      "generated by you rather than seeded, and which one is pinned to the " +
      "Boardroom.",
    value: JSON.stringify({
      page: "Boards",
      boards: boards.map((b) => ({
        title: b.title,
        url: vantageHref(`boards/${b.slug}`),
        tiles: b.tiles.length,
        generated: b.origin === "generated",
        pinned: b.pinned,
        fromDocument: b.sourceDocument ?? null,
      })),
    }),
  });

  return (
    <div className="mx-auto max-w-5xl space-y-5">
      <header className="space-y-1">
        <h1 className="text-xl font-semibold tracking-tight text-ink">
          Boards
        </h1>
        <p className="text-sm text-ink-muted">
          Saved boards. Generated ones are ordinary pages with their own URL —
          they outlive the conversation that made them.
        </p>
      </header>

      <div className="grid gap-3 sm:grid-cols-2">
        {boards.map((board) => (
          <div
            key={board.id}
            className="flex flex-col gap-2 rounded-[var(--radius)] border border-hairline bg-surface p-4"
          >
            <div className="flex items-start justify-between gap-2">
              <Link
                href={vantageHref(`boards/${board.slug}`)}
                className="text-sm font-semibold text-ink hover:text-brand"
              >
                {board.title}
              </Link>
              {board.origin === "generated" && (
                <span className="flex shrink-0 items-center gap-1 rounded bg-brand-soft px-1.5 py-0.5 text-[10px] font-bold uppercase tracking-wide text-brand">
                  <Sparkles className="h-3 w-3" />
                  Generated
                </span>
              )}
            </div>
            <p className="line-clamp-2 text-xs text-ink-muted">
              {board.summary}
            </p>
            <div className="mt-auto flex items-center justify-between pt-1">
              <span className="nw-figure text-[11px] text-ink-muted">
                {board.tiles.length} tiles
              </span>
              {board.pinned ? (
                <span className="flex items-center gap-1 text-[11px] font-semibold text-brand">
                  <Pin className="h-3 w-3" /> Pinned
                </span>
              ) : (
                <button
                  type="button"
                  onClick={() => void pin(board.id)}
                  className="text-[11px] text-ink-muted transition-colors hover:text-brand"
                >
                  Pin to Boardroom
                </button>
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

export default BoardsPage;
