// Auto-generated by scripts/generate-integration-features.mjs
// Do not edit manually - run: node scripts/generate-integration-features.mjs

import { IntegrationId } from './integrations';

/**
 * Maps feature names to the list of integration IDs that have that feature.
 * This is auto-generated at build time by scanning the content/docs/integrations directory.
 */
export const INTEGRATION_FEATURES: Record<string, IntegrationId[]> = {
  "shared-state": [
    "adk",
    "ag2",
    "agent-spec",
    "aws-strands",
    "claude-agent-sdk",
    "crewai-flows",
    "langgraph",
    "llamaindex",
    "mastra",
    "microsoft-agent-framework",
    "pydantic-ai"
  ],
  "generative-ui": [
    "a2a",
    "adk",
    "ag2",
    "agent-spec",
    "agno",
    "aws-strands",
    "claude-agent-sdk",
    "crewai-flows",
    "langgraph",
    "llamaindex",
    "mastra",
    "microsoft-agent-framework",
    "pydantic-ai"
  ],
  "generative-ui/render-only": [],
  "generative-ui/tool-rendering": [
    "adk",
    "ag2",
    "agent-spec",
    "agno",
    "aws-strands",
    "claude-agent-sdk",
    "crewai-flows",
    "langgraph",
    "llamaindex",
    "mastra",
    "microsoft-agent-framework",
    "pydantic-ai"
  ],
  "generative-ui/state-rendering": [
    "adk",
    "ag2",
    "aws-strands",
    "claude-agent-sdk",
    "crewai-flows",
    "langgraph",
    "llamaindex",
    "mastra",
    "microsoft-agent-framework",
    "pydantic-ai"
  ],
  "generative-ui/mcp-apps": [
    "adk",
    "ag2",
    "agent-spec",
    "agno",
    "aws-strands",
    "claude-agent-sdk",
    "crewai-flows",
    "langgraph",
    "llamaindex",
    "mastra",
    "microsoft-agent-framework",
    "pydantic-ai"
  ],
  "generative-ui/a2ui": [
    "adk",
    "ag2",
    "agent-spec",
    "agno",
    "aws-strands",
    "claude-agent-sdk",
    "crewai-flows",
    "langgraph",
    "llamaindex",
    "mastra",
    "microsoft-agent-framework",
    "pydantic-ai"
  ],
  "frontend-actions": [],
  "human-in-the-loop": [
    "adk",
    "ag2",
    "agent-spec",
    "agno",
    "claude-agent-sdk",
    "crewai-flows",
    "langgraph",
    "llamaindex",
    "mastra",
    "microsoft-agent-framework",
    "pydantic-ai"
  ],
  "agentic-chat-ui": [],
  "custom-look-and-feel": [
    "a2a",
    "adk",
    "ag2",
    "agent-spec",
    "agno",
    "aws-strands",
    "claude-agent-sdk",
    "crewai-flows",
    "langgraph",
    "llamaindex",
    "mastra",
    "microsoft-agent-framework",
    "pydantic-ai"
  ]
};

/**
 * Check if an integration has a specific feature page.
 */
export function hasIntegrationFeature(integrationId: IntegrationId, feature: string): boolean {
  return INTEGRATION_FEATURES[feature]?.includes(integrationId) ?? false;
}
