/**
 * Single source of truth for integration ordering and metadata.
 * 
 * This file controls the canonical order and metadata for all integrations
 * across the documentation site. All UI components import from here to ensure
 * consistency.
 * 
 * Used by:
 * - Sidebar integration list (components/ui/sidebar/integration-link.tsx)
 * - Integration dropdown selector (components/ui/integrations-sidebar/integration-selector.tsx)
 * - Integration button grid (components/react/integration-link-button/integration-button-group.tsx)
 * - Integrations grid (components/react/integrations.tsx)
 * - Content structure (content/docs/integrations/meta.json should match this order)
 *
 * To add a new integration:
 * 1. Add the ID to INTEGRATION_ORDER (in desired position)
 * 2. Add metadata to INTEGRATION_METADATA
 * 3. Update content/docs/integrations/meta.json to match
 * 4. Create the icon component and register it in UI components
 * 
 * Feature availability (which integrations appear on which feature pages) is
 * auto-generated by scripts/generate-integration-features.mjs - see README.md
 */

// Integration IDs - order matters!
export const INTEGRATION_ORDER = [
  'adk',
  'a2a',
  'microsoft-agent-framework',
  'aws-strands',
  'direct-to-llm',
  'langgraph',
  'ag2',
  'agno',
  'crewai-crews',
  'crewai-flows',
  'llamaindex',
  'mastra',
  'pydantic-ai',
] as const;

export type IntegrationId = typeof INTEGRATION_ORDER[number];

// Integration metadata
export interface IntegrationMeta {
  id: IntegrationId;
  label: string;
  href: string;
}

export const INTEGRATION_METADATA: Record<IntegrationId, Omit<IntegrationMeta, 'id'>> = {
  'adk': { label: 'ADK', href: '/adk' },
  'a2a': { label: 'A2A', href: '/a2a' },
  'microsoft-agent-framework': { label: 'Microsoft Agent Framework', href: '/microsoft-agent-framework' },
  'aws-strands': { label: 'AWS Strands', href: '/aws-strands' },
  'direct-to-llm': { label: 'Direct to LLM', href: '/direct-to-llm' },
  'langgraph': { label: 'LangGraph', href: '/langgraph' },
  'ag2': { label: 'AG2', href: '/ag2' },
  'agno': { label: 'Agno', href: '/agno' },
  'crewai-crews': { label: 'CrewAI Crews', href: '/crewai-crews' },
  'crewai-flows': { label: 'CrewAI Flows', href: '/crewai-flows' },
  'llamaindex': { label: 'LlamaIndex', href: '/llamaindex' },
  'mastra': { label: 'Mastra', href: '/mastra' },
  'pydantic-ai': { label: 'Pydantic AI', href: '/pydantic-ai' },
};

/**
 * Get all integrations in the canonical order
 */
export function getIntegrations(): IntegrationMeta[] {
  return INTEGRATION_ORDER.map(id => ({
    id,
    ...INTEGRATION_METADATA[id],
  }));
}

/**
 * Get integration metadata by ID
 */
export function getIntegration(id: IntegrationId): IntegrationMeta {
  return {
    id,
    ...INTEGRATION_METADATA[id],
  };
}
