// Auto-generated by scripts/generate-integration-features.mjs
// Do not edit manually - run: node scripts/generate-integration-features.mjs

import { IntegrationId } from "./integrations";

/**
 * Maps feature names to the list of integration IDs that have that feature.
 * This is auto-generated at build time by scanning the content/docs/integrations directory.
 */
export const INTEGRATION_FEATURES: Record<string, IntegrationId[]> = {
  "shared-state": [
    "adk",
    "ag2",
    "agent-spec",
    "aws-strands",
    "crewai-crews",
    "crewai-flows",
    "langgraph",
    "llamaindex",
    "mastra",
    "microsoft-agent-framework",
    "pydantic-ai",
  ],
  "generative-ui": [
    "a2a",
    "adk",
    "ag2",
    "agent-spec",
    "agno",
    "aws-strands",
    "crewai-crews",
    "crewai-flows",
    "langgraph",
    "llamaindex",
    "mastra",
    "microsoft-agent-framework",
    "pydantic-ai",
  ],
  "frontend-actions": [
    "adk",
    "ag2",
    "aws-strands",
    "crewai-crews",
    "crewai-flows",
    "langgraph",
    "llamaindex",
    "mastra",
    "microsoft-agent-framework",
    "pydantic-ai",
  ],
  "human-in-the-loop": [
    "adk",
    "ag2",
    "agent-spec",
    "agno",
    "crewai-crews",
    "crewai-flows",
    "langgraph",
    "llamaindex",
    "mastra",
    "microsoft-agent-framework",
    "pydantic-ai",
  ],
  "agentic-chat-ui": [
    "adk",
    "ag2",
    "agent-spec",
    "agno",
    "aws-strands",
    "crewai-crews",
    "crewai-flows",
    "langgraph",
    "llamaindex",
    "mastra",
    "microsoft-agent-framework",
    "pydantic-ai",
  ],
  "custom-look-and-feel": [
    "adk",
    "ag2",
    "agent-spec",
    "agno",
    "aws-strands",
    "crewai-crews",
    "crewai-flows",
    "langgraph",
    "llamaindex",
    "mastra",
    "microsoft-agent-framework",
    "pydantic-ai",
  ],
};

/**
 * Check if an integration has a specific feature page.
 */
export function hasIntegrationFeature(
  integrationId: IntegrationId,
  feature: string,
): boolean {
  return INTEGRATION_FEATURES[feature]?.includes(integrationId) ?? false;
}
