#!/usr/bin/env bash
# Generate identical byoc-hashbrown.spec.ts and byoc-json-render.spec.ts
# regression tests across every integration that ships the byoc demos.
#
# These specs cover the user-flow that previously regressed (clicking a
# suggestion pill rendered nothing): page-load smoke + click-each-of-the
# -three-pills, asserting the catalog components materialize.
#
# Re-run after editing the templates below; outputs are deterministic and
# safe to overwrite.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INTEGRATIONS_DIR="$ROOT/integrations"

HASHBROWN_TEMPLATE='import { test, expect } from "@playwright/test";

/**
 * Regression coverage for the byoc-hashbrown demo'"'"'s three pre-seeded
 * suggestion pills. The user-reported regression that motivated this
 * suite: clicking the "Sales dashboard" pill produced no DOM at all
 * while the other two pills rendered their respective charts. We click
 * each pill in turn and assert the catalog components surface in the
 * structured-output area within the streaming budget. If the hashbrown
 * renderer drops a component (or the agent stops emitting one of the
 * tag families) the matching test fails immediately.
 *
 * Generated by showcase/scripts/generate-byoc-regression-tests.sh —
 * edit the template there, not the per-integration copies.
 */
const SUGGESTION_TIMEOUT_MS = 60_000;

test.describe("BYOC Hashbrown — pill suggestion regression", () => {
  test.beforeEach(async ({ page }) => {
    await page.goto("/demos/byoc-hashbrown");
  });

  test("page loads with header and all three suggestion pills", async ({
    page,
  }) => {
    await expect(
      page.getByRole("heading", { name: "BYOC: Hashbrown" }),
    ).toBeVisible();
    await expect(
      page.getByRole("button", { name: "Sales dashboard" }),
    ).toBeVisible();
    await expect(
      page.getByRole("button", { name: "Revenue by category" }),
    ).toBeVisible();
    await expect(
      page.getByRole("button", { name: "Expense trend" }),
    ).toBeVisible();
  });

  test("Sales dashboard pill renders metric card + pie + bar", async ({
    page,
  }) => {
    await page.getByRole("button", { name: "Sales dashboard" }).click();

    // The fixture-backed Sales dashboard response includes a metric
    // card, a pie chart, and a bar chart. Assert all three so a
    // regression that drops any one of them is caught — the original
    // bug dropped all three at once.
    await expect(
      page.locator('"'"'[data-testid="metric-card"]'"'"').first(),
    ).toBeVisible({ timeout: SUGGESTION_TIMEOUT_MS });
    await expect(
      page.locator('"'"'[data-testid="pie-chart"]'"'"').first(),
    ).toBeVisible({ timeout: SUGGESTION_TIMEOUT_MS });
    await expect(
      page.locator('"'"'[data-testid="bar-chart"]'"'"').first(),
    ).toBeVisible({ timeout: SUGGESTION_TIMEOUT_MS });
  });

  test("Revenue by category pill renders a pie chart", async ({ page }) => {
    await page.getByRole("button", { name: "Revenue by category" }).click();
    await expect(
      page.locator('"'"'[data-testid="pie-chart"]'"'"').first(),
    ).toBeVisible({ timeout: SUGGESTION_TIMEOUT_MS });
  });

  test("Expense trend pill renders a bar chart", async ({ page }) => {
    await page.getByRole("button", { name: "Expense trend" }).click();
    await expect(
      page.locator('"'"'[data-testid="bar-chart"]'"'"').first(),
    ).toBeVisible({ timeout: SUGGESTION_TIMEOUT_MS });
  });
});
'

JSON_RENDER_TEMPLATE='import { test, expect } from "@playwright/test";

/**
 * Regression coverage for the byoc-json-render demo'"'"'s three
 * pre-seeded suggestion pills. Mirrors the byoc-hashbrown regression
 * suite so any fan-out drift between the two BYOC demos is caught
 * symmetrically. The shared user-reported failure mode is: pill click
 * produced no structured output. We click each pill and assert the
 * catalog component(s) the json-render fixture is expected to emit.
 *
 * Generated by showcase/scripts/generate-byoc-regression-tests.sh —
 * edit the template there, not the per-integration copies.
 */
const SUGGESTION_TIMEOUT_MS = 60_000;

test.describe("BYOC json-render — pill suggestion regression", () => {
  test.beforeEach(async ({ page }) => {
    await page.goto("/demos/byoc-json-render");
  });

  test("page loads with all three suggestion pills", async ({ page }) => {
    await expect(
      page.getByRole("button", { name: "Sales dashboard" }),
    ).toBeVisible();
    await expect(
      page.getByRole("button", { name: "Revenue by category" }),
    ).toBeVisible();
    await expect(
      page.getByRole("button", { name: "Expense trend" }),
    ).toBeVisible();
  });

  test("Sales dashboard pill renders metric card + bar chart", async ({
    page,
  }) => {
    await page.getByRole("button", { name: "Sales dashboard" }).click();

    // The json-render Sales dashboard fixture renders a MetricCard plus
    // a BarChart (no pie chart). Both should appear inside the
    // json-render-root wrapper.
    await expect(
      page.locator('"'"'[data-testid="json-render-root"]'"'"').first(),
    ).toBeVisible({ timeout: SUGGESTION_TIMEOUT_MS });
    await expect(
      page.locator('"'"'[data-testid="metric-card"]'"'"').first(),
    ).toBeVisible({ timeout: SUGGESTION_TIMEOUT_MS });
    await expect(
      page.locator('"'"'[data-testid="bar-chart"]'"'"').first(),
    ).toBeVisible({ timeout: SUGGESTION_TIMEOUT_MS });
  });

  test("Revenue by category pill renders a pie chart", async ({ page }) => {
    await page.getByRole("button", { name: "Revenue by category" }).click();
    await expect(
      page.locator('"'"'[data-testid="pie-chart"]'"'"').first(),
    ).toBeVisible({ timeout: SUGGESTION_TIMEOUT_MS });
  });

  test("Expense trend pill renders a bar chart", async ({ page }) => {
    await page.getByRole("button", { name: "Expense trend" }).click();
    await expect(
      page.locator('"'"'[data-testid="bar-chart"]'"'"').first(),
    ).toBeVisible({ timeout: SUGGESTION_TIMEOUT_MS });
  });
});
'

count_hash=0
count_json=0

for integration_dir in "$INTEGRATIONS_DIR"/*/; do
  slug="$(basename "$integration_dir")"
  e2e_dir="$integration_dir/tests/e2e"

  if [ -d "$integration_dir/src/app/demos/byoc-hashbrown" ]; then
    mkdir -p "$e2e_dir"
    printf '%s' "$HASHBROWN_TEMPLATE" > "$e2e_dir/byoc-hashbrown.spec.ts"
    count_hash=$((count_hash + 1))
    echo "  wrote $slug/tests/e2e/byoc-hashbrown.spec.ts"
  fi

  if [ -d "$integration_dir/src/app/demos/byoc-json-render" ]; then
    mkdir -p "$e2e_dir"
    printf '%s' "$JSON_RENDER_TEMPLATE" > "$e2e_dir/byoc-json-render.spec.ts"
    count_json=$((count_json + 1))
    echo "  wrote $slug/tests/e2e/byoc-json-render.spec.ts"
  fi
done

echo
echo "Done: $count_hash hashbrown specs, $count_json json-render specs."
