# syntax=docker/dockerfile:1-labs

FROM node:23-slim AS production
COPY --from=public.ecr.aws/awsguru/aws-lambda-adapter:0.9.0 /lambda-adapter /opt/extensions/lambda-adapter

ENV HOME="/tmp"
ENV PNPM_HOME="/tmp/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
ENV COREPACK_HOME="/tmp/corepack"
RUN corepack enable
RUN corepack prepare pnpm@9.5.0 --activate
# RUN apt-get update && apt-get install curl -y

ARG APP_DIR

WORKDIR /tmp/app

# Copy only poetry files first
COPY ${APP_DIR}/package.json ${APP_DIR}/pnpm-lock.yaml ./
RUN pnpm i --frozen-lockfile

# Copy SDK and install dependencies in a single layer
COPY ${APP_DIR}/ ./

RUN touch .env
RUN mkdir .langgraph_api

ENV NODE_ENV=production
ENV HOME=/tmp
EXPOSE 8000

CMD ["node", "./node_modules/@langchain/langgraph-cli/dist/cli/cli.mjs", "dev", "--config=langgraph.json", "--no-browser", "--port", "8000", "--host", "0.0.0.0"]