FROM public.ecr.aws/docker/library/python:3.12-bookworm
COPY --from=public.ecr.aws/awsguru/aws-lambda-adapter:0.8.4 /lambda-adapter /opt/extensions/lambda-adapter

ARG APP_DIR
ARG WITH_LOCAL_DEPS

ENV POETRY_VIRTUALENVS_CREATE=false

# Install poetry and configure it
RUN pip install poetry==1.7.1 && \
    poetry config virtualenvs.create false

# Copy only poetry files first
COPY ${APP_DIR}/pyproject.toml ${APP_DIR}/poetry.lock ./

# Copy SDK and install dependencies
COPY sdk-python/ /opt/sdk-python
WORKDIR /asset

# Create a symlink from /sdk-python to /opt/sdk-python
# This is to handle the case where the code is looking for /sdk-python
RUN ln -sf /opt/sdk-python /sdk-python

RUN poetry install --no-interaction --no-ansi
RUN if [ "$WITH_LOCAL_DEPS" = "true" ]; then poetry add /opt/sdk-python; fi

# Copy application code last
COPY ${APP_DIR}/ ./

# Use this if you want to use the langgraph
# RUN mkdir .langgraph_api

CMD ["poetry", "run", "demo"] 