# syntax=docker/dockerfile:1-labs

FROM node:22-slim AS production
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
ENV COREPACK_HOME="/tmp/corepack"
RUN corepack enable
RUN corepack prepare pnpm@9.15.0 --activate
RUN pnpm i -g turbo
# RUN apt-get update && apt-get install curl -y

ARG APP_DIR
COPY --from=public.ecr.aws/awsguru/aws-lambda-adapter:0.9.0 /lambda-adapter /opt/extensions/lambda-adapter

# First install via pnpx
RUN pnpx @langchain/langgraph-cli --help

# Copy only poetry files first
COPY ${APP_DIR}/package.json ${APP_DIR}/pnpm-lock.yaml ./
RUN pnpm i --frozen-lockfile

# Copy SDK and install dependencies in a single layer
COPY ${APP_DIR}/ ./

RUN touch .env
RUN mkdir .langgraph_api

ENV NODE_ENV=production
EXPOSE 8000

CMD ["/bin/sh", "-c", "pnpx @langchain/langgraph-cli dev --config=langgraph.json --no-browser --port 8000 --host 0.0.0.0"]