apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-placeholder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-placeholder
  template:
    metadata:
      labels:
        app: nginx-placeholder
    spec:
      containers:
      - name: nginx-placeholder
        image: nginx:latest
        ports:
        - containerPort: 80
