"""Shared helpers for dedicated-crew demos.

Background
----------
`ag_ui_crewai.endpoint.add_crewai_crew_fastapi_endpoint` composes its system
prompt via CrewAI's `build_system_message(crew_chat_inputs)`,
where `crew_chat_inputs` is generated by `generate_crew_chat_inputs` (which
itself runs secondary AI calls to describe the crew and its inputs).

For per-demo crews in this showcase we want **full control** over the system
prompt — e.g. the BYOC demos need pure-JSON output, while the A2UI demos need
tool-selection guidance. We also want to skip the startup secondary AI calls
so that boot stays fast and the first request is not gated on an LLM probe.

Strategy
--------
We register a hand-built `ChatInputs(crew_description=<our prompt>, inputs=[])`
with the bridge's chat-input generator BEFORE deferred Flow construction runs.
`build_system_message` then embeds our description verbatim (surrounded by the
fixed CrewAI platform boilerplate).

The pre-seed also skips the secondary AI calls in
`generate_crew_chat_inputs`, so crew construction is synchronous and cheap.

The CrewAI bridge owns an identity-safe weakref cache, so showcase code must not
write cache entries directly. Intercepting the generator preserves that cache's
invariants while keeping us on `add_crewai_crew_fastapi_endpoint`.
"""

from __future__ import annotations

from typing import Any


def preseed_system_prompt(crew_name: str, description: str) -> None:
    """Install `description` as `crew_description` for `crew_name`.

    Subsequent `ChatWithCrewFlow(crew=<our crew>)` construction receives the
    registered schema and skips the secondary AI description calls entirely.

    Safe to call before OR after `add_crewai_crew_fastapi_endpoint` — the
    endpoint construction is deferred to first request, so as long as we
    preseed before the first POST we are fine.
    """
    import ag_ui_crewai.crews as crews_module
    from crewai.types.crew_chat import ChatInputs

    prompts = getattr(crews_module, "_SHOWCASE_SYSTEM_PROMPTS", None)
    if prompts is None:
        prompts = {}
        crews_module._SHOWCASE_SYSTEM_PROMPTS = prompts

        original_generator = crews_module.crew_chat_generate_crew_chat_inputs

        def generate_chat_inputs(crew: Any, name: str, chat_llm: Any) -> Any:
            prompt = crews_module._SHOWCASE_SYSTEM_PROMPTS.get(name)
            if prompt is not None:
                return ChatInputs(
                    crew_name=name,
                    crew_description=prompt,
                    inputs=[],
                )
            return original_generator(crew, name, chat_llm)

        crews_module.crew_chat_generate_crew_chat_inputs = generate_chat_inputs

    prompts[crew_name] = description


def install_custom_system_message(crew_name: str, full_system_message: str) -> None:
    """Hard-override the system message for a specific crew.

    Some demos (notably BYOC) need the chat LLM to emit a very specific output
    shape that the stock `build_system_message` boilerplate actively fights
    (it tells the LLM to introduce itself, to ask clarifying questions, etc.).
    For those demos we patch `ChatWithCrewFlow.__init__` to stash our custom
    system message on the instance right after construction, overriding the
    one the upstream code assembled.

    Implementation: subclass `Flow` isn't exposed cleanly, so we monkey-patch
    at the module level. The hook is keyed by `crew_name`, so crews that
    don't register a custom message fall through to the stock behaviour.
    """
    import ag_ui_crewai.crews as _crews_module

    if not getattr(_crews_module, "_CUSTOM_SYSTEM_MESSAGES", None):
        _crews_module._CUSTOM_SYSTEM_MESSAGES = {}

        original_init = _crews_module.ChatWithCrewFlow.__init__

        def patched_init(self: Any, *, crew: Any) -> None:
            original_init(self, crew=crew)
            override = _crews_module._CUSTOM_SYSTEM_MESSAGES.get(
                getattr(self, "crew_name", None)
            )
            if override:
                self.system_message = override

        _crews_module.ChatWithCrewFlow.__init__ = patched_init  # type: ignore[method-assign]

    _crews_module._CUSTOM_SYSTEM_MESSAGES[crew_name] = full_system_message
