# syntax=docker/dockerfile:1-labs

FROM node:22-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
RUN corepack prepare pnpm@9.15.0 --activate
RUN pnpm i -g turbo

COPY --from=public.ecr.aws/awsguru/aws-lambda-adapter:0.8.4 /lambda-adapter /opt/extensions/lambda-adapter

WORKDIR /app/
COPY maxtest/agui/typescript-sdk/apps/dojo/.next/standalone ./
COPY maxtest/agui/typescript-sdk/apps/dojo/.next/static ./.next/static

# Set the environment variables (if needed)
ENV NODE_ENV=production
EXPOSE 3000
CMD ["node", "server.js"]