/**
 * cvdiag-emitter.ts — co-located CVDIAG emitter barrel for a STANDALONE TS
 * integration build context. GENERATED by `showcase cvdiag-stage-ts` — do NOT
 * edit by hand; edit the canonical sources under
 * `showcase/harness/src/cvdiag/` and re-run the stage command.
 *
 * This is the FLATTENED form of `showcase/integrations/_shared/ts/cvdiag-emitter.ts`:
 * the shared barrel re-exports from `../../../harness/src/cvdiag/*`, which has
 * no resolution inside a standalone integration's Docker build context. The
 * stage command copies the L0-A sources (scrub.ts, schema.ts, edge-headers.ts,
 * emit.ts, pb-writer-fetch.ts) next to this file and rewrites the re-export
 * specifiers to the co-located `./*.js` copies so `next build` bundles a
 * self-contained emitter + concrete writer-role PB writer.
 */

// ── Schema (types, enums, validators, UUIDv7 regex) ─────────────────────────
export {
  SCHEMA_VERSION,
  CVDIAG_LAYERS,
  CVDIAG_OUTCOMES,
  PROBE_BOUNDARIES,
  BACKEND_BOUNDARIES,
  AIMOCK_BOUNDARIES,
  CVDIAG_DATA_PLANE_BOUNDARIES,
  CVDIAG_ACCOUNTING_BOUNDARIES,
  CVDIAG_BOUNDARIES,
  EDGE_HEADER_KEYS,
  TERMINATION_KINDS,
  TEST_ID_REGEX,
  ENVELOPE_KEYS,
  BOUNDARY_METADATA_KEYS,
  isValidTestId,
  validateEnvelope,
  validateMetadata,
} from "./schema.js";

export type {
  CvdiagLayer,
  CvdiagOutcome,
  CvdiagDataPlaneBoundary,
  CvdiagAccountingBoundary,
  CvdiagBoundary,
  EdgeHeaders,
  EdgeHeaderKey,
  TerminationKind,
  CvdiagEnvelope,
  EnvelopeValidationResult,
  MetadataValidationResult,
} from "./schema.js";

// ── Edge-header allow/deny filter + PII scrub ───────────────────────────────
export {
  EDGE_HEADER_ALLOWLIST,
  EDGE_HEADER_DENYLIST,
  BEARER_TOKEN_REGEX,
  SK_KEY_REGEX,
  URL_USERINFO_REGEX,
  SCRUB_REPLACEMENT,
  scrubSecrets,
  filterEdgeHeaders,
} from "./edge-headers.js";

// ── Emitter (tier resolution, fail-closed DEBUG, byte caps, span/id minters) ─
export {
  CvdiagEmitter,
  BYTE_CAP_BY_TIER,
  QUEUE_CAP,
  DEBUG_MAX_WALLCLOCK_MS,
  DEBUG_MAX_EVENTS,
  FLUSH_WINDOW_MS,
  resolveEnvLabel,
  mintTestId,
  mintSpanId,
} from "./emit.js";

export type {
  CvdiagTier,
  CvdiagPbWriter,
  CvdiagEnv,
  CvdiagEmitterOptions,
  CvdiagEmitArgs,
} from "./emit.js";

// ── Concrete writer-role PB writer (plain fetch; auth-with-password→Bearer) ──
export {
  CvdiagFetchPbWriter,
  createCvdiagFetchPbWriterFromEnv,
} from "./pb-writer-fetch.js";

export type {
  FetchLike,
  CvdiagFetchPbWriterOptions,
} from "./pb-writer-fetch.js";
