import type { RuntimeInfo, AgentDescription } from "@copilotkit/shared";
import chalk from "chalk";
import {
  applyEdits,
  modify,
  parse as parseJsonc,
  parseTree,
} from "jsonc-parser";
import type { Node } from "jsonc-parser";
import * as fs from "node:fs";
import * as path from "node:path";

interface CollectedAgent {
  name: string;
  description: string;
  className: string;
}

// ── Pretty-print helpers ─────────────────────────────────────────────

const icons = {
  fetch: chalk.cyan("~"),
  ok: chalk.green("*"),
  warn: chalk.yellow("!"),
  err: chalk.red("x"),
  file: chalk.green("+"),
  skip: chalk.dim("-"),
  agent: chalk.magenta(">"),
} as const;

function header(text: string) {
  const line = chalk.dim("─".repeat(48));
  console.log(`\n  ${line}`);
  console.log(`  ${chalk.bold(text)}`);
  console.log(`  ${line}\n`);
}

// ── Network ──────────────────────────────────────────────────────────

/**
 * Fetch runtime info from a URL.
 * Tries multi-endpoint GET /info first, then falls back to single-endpoint
 * POST {url} with body { method: "info" } (the CopilotKit single-endpoint
 * protocol — see packages/runtime/src/v2/runtime/core/fetch-handler.ts).
 *
 * When the GET attempt fails by exception OR returns a non-OK status, we
 * fall through to the POST. The original failure is preserved and surfaced
 * with the final error so a misconfigured /info doesn't masquerade as a
 * POST 4xx.
 */
async function fetchRuntimeInfo(url: string): Promise<RuntimeInfo> {
  const baseUrl = url.replace(/\/+$/, "");
  const infoUrl = `${baseUrl}/info`;

  let getFailure: string | null = null;
  try {
    const response = await fetch(infoUrl, {
      method: "GET",
      headers: { Accept: "application/json" },
    });
    if (response.ok) {
      return (await response.json()) as RuntimeInfo;
    }
    getFailure = `GET ${infoUrl} → ${response.status} ${response.statusText}`;
  } catch (error) {
    getFailure = `GET ${infoUrl} → ${error instanceof Error ? error.message : String(error)}`;
  }

  // Fallback: single-endpoint POST
  try {
    const response = await fetch(baseUrl, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Accept: "application/json",
      },
      body: JSON.stringify({ method: "info" }),
    });

    if (!response.ok) {
      throw new Error(
        `POST ${baseUrl} → ${response.status} ${response.statusText} (after ${getFailure})`,
      );
    }

    return (await response.json()) as RuntimeInfo;
  } catch (error) {
    if (
      error instanceof Error &&
      getFailure &&
      !error.message.includes(getFailure)
    ) {
      throw new Error(`${error.message} (after ${getFailure})`, {
        cause: error,
      });
    }
    throw error;
  }
}

// ── Runtime info validation ──────────────────────────────────────────

function isAgentDescription(value: unknown): value is AgentDescription {
  if (value === null || typeof value !== "object") return false;
  const v = value as Record<string, unknown>;
  return (
    typeof v.name === "string" &&
    typeof v.className === "string" &&
    typeof v.description === "string"
  );
}

export function validateRuntimeInfo(value: unknown, url: string): RuntimeInfo {
  if (value === null || typeof value !== "object") {
    throw new Error(`Runtime at ${url} returned a non-object response`);
  }
  const v = value as Record<string, unknown>;
  if (typeof v.version !== "string") {
    throw new Error(`Runtime at ${url} returned no \`version\` string`);
  }
  if (v.agents === null || typeof v.agents !== "object") {
    throw new Error(
      `Runtime at ${url} returned a malformed \`agents\` field (expected an object, got ${v.agents === null ? "null" : typeof v.agents})`,
    );
  }
  for (const [agentId, agent] of Object.entries(v.agents)) {
    if (!isAgentDescription(agent)) {
      throw new Error(
        `Runtime at ${url} returned a malformed agent entry for "${agentId}" (expected { name, className, description }).`,
      );
    }
  }
  return value as RuntimeInfo;
}

// ── Code generation ──────────────────────────────────────────────────

export function generateTypesFile(agents: Map<string, CollectedAgent>): string {
  const lines: string[] = [];
  lines.push("// Auto-generated by @copilotkit/cli typegen");
  lines.push("// Do not edit manually\n");

  lines.push("export type Agents = {");
  for (const [agentId, agent] of agents) {
    lines.push(`  ${JSON.stringify(agentId)}: {`);
    lines.push(`    description: ${JSON.stringify(agent.description ?? "")};`);
    lines.push("  };");
  }
  lines.push("};");

  return lines.join("\n") + "\n";
}

function generateRegisterFile(): string {
  return `// Auto-generated by @copilotkit/cli typegen
// Do not edit manually

import type { Agents } from "./types";

declare module "@copilotkit/react-core/v2" {
  interface Register {
    agents: Agents;
  }
}
`;
}

// ── Project-root detection ───────────────────────────────────────────

/**
 * Walk up from `start` one level at a time, looking for the nearest directory
 * containing a `package.json`. A `package.json` whose IMMEDIATE parent is
 * `node_modules` belongs to a dependency, not the project — those are skipped
 * and the walk continues upward. Any other ancestor segment named
 * `node_modules` on the way up is left alone: a legitimate workspace package
 * that happens to live at `/repo/node_modules/.../packages/my-app` is still
 * the right answer for the CLI invoked from inside it.
 *
 * Returns `null` if no eligible package.json is found before hitting the
 * filesystem root — typegen has no sensible place to write in that case.
 */
export function findProjectRoot(start: string): string | null {
  let current = path.resolve(start);
  while (true) {
    if (fs.existsSync(path.join(current, "package.json"))) {
      // Skip dependency package.jsons (those sit directly inside
      // node_modules) but accept anything else, even paths that traverse
      // node_modules higher up the tree.
      const parentDirName = path.basename(path.dirname(current));
      if (parentDirName !== "node_modules") {
        return current;
      }
    }
    const parent = path.dirname(current);
    if (parent === current) return null; // filesystem root
    current = parent;
  }
}

// ── Project config updates ───────────────────────────────────────────

function ensureGitignore(projectDir: string, pattern: string): boolean {
  const gitignorePath = path.join(projectDir, ".gitignore");

  let content = "";
  if (fs.existsSync(gitignorePath)) {
    content = fs.readFileSync(gitignorePath, "utf-8");
  }

  const lines = content.split("\n");
  if (lines.some((line) => line.trim() === pattern)) {
    return false;
  }

  const newContent = content.endsWith("\n")
    ? `${content}${pattern}\n`
    : `${content}\n${pattern}\n`;
  fs.writeFileSync(gitignorePath, newContent, "utf-8");
  return true;
}

type TsconfigUpdateResult =
  | { kind: "added" }
  | { kind: "already-present" }
  | { kind: "not-found" }
  | { kind: "unparseable"; reason: string }
  | { kind: "extends-without-include"; reason: string }
  | { kind: "invalid-include-type"; reason: string };

/**
 * Add `.copilotkit/register.d.ts` to the project's tsconfig.json `include`
 * array, preserving the existing comments, formatting, and key order via
 * jsonc-parser. The official tsconfig format is JSONC — `JSON.parse` would
 * reject the comments and trailing commas most real tsconfigs contain, and
 * `JSON.stringify` would erase user formatting.
 *
 * Returns one of:
 *   - "added": pattern inserted
 *   - "already-present": pattern was already in `include`
 *   - "not-found": no tsconfig.json at projectDir
 *   - "unparseable": jsonc-parser failed to parse — file untouched
 *   - "extends-without-include": tsconfig has `extends` and no own `include`.
 *     Adding our own `include` would override the base config's include and
 *     break the project's type resolution; file untouched and surfaced to
 *     the user with guidance to add the include to the extending config.
 */
export function ensureTsconfigInclude(
  projectDir: string,
): TsconfigUpdateResult {
  const tsconfigPath = path.join(projectDir, "tsconfig.json");
  if (!fs.existsSync(tsconfigPath)) {
    return { kind: "not-found" };
  }

  const raw = fs.readFileSync(tsconfigPath, "utf-8");
  const errors: { error: number; offset: number; length: number }[] = [];
  const parsed = parseJsonc(raw, errors, {
    allowTrailingComma: true,
    disallowComments: false,
  });
  // parseJsonc is best-effort: on syntax errors it returns a partial value
  // AND populates the errors array. Modifying a partially-parsed tsconfig
  // could produce malformed output, so refuse to touch the file if there's
  // any parse error — the user is told to fix it (or add the include line
  // manually).
  if (parsed === undefined || errors.length > 0) {
    return {
      kind: "unparseable",
      reason: errors.length
        ? `jsonc-parser reported ${errors.length} error(s) — refusing to modify`
        : "could not parse tsconfig.json",
    };
  }

  const tsconfig = parsed as Record<string, unknown>;
  const pattern = ".copilotkit/register.d.ts";

  const ownIncludeRaw = tsconfig.include;
  const hasOwnIncludeKey = Object.prototype.hasOwnProperty.call(
    tsconfig,
    "include",
  );

  // `include` must be either absent or an array of strings. If a user has
  // anything else here (a bare string, an object, null), refuse to touch
  // the file — silently overwriting their value with our pattern would
  // destroy whatever they meant. TypeScript itself rejects non-arrays in
  // `include`, so this catches typos rather than legitimate config shapes.
  if (hasOwnIncludeKey && !Array.isArray(ownIncludeRaw)) {
    return {
      kind: "invalid-include-type",
      reason: `tsconfig.json has \`include\` set to ${describeIncludeValue(ownIncludeRaw)} — expected an array; refusing to modify`,
    };
  }
  const existingInclude = Array.isArray(ownIncludeRaw) ? ownIncludeRaw : null;

  if (existingInclude?.includes(pattern)) {
    return { kind: "already-present" };
  }

  // Adding our pattern to an empty-or-missing `include` when the tsconfig
  // extends a base is dangerous: an explicit `include: []` is the canonical
  // way to clear the base's include, and a missing `include` lets the base
  // contribute its own. In both cases, writing `[".copilotkit/register.d.ts"]`
  // here narrows the project's compilation scope to just our register file,
  // silently breaking the user's build. Refuse to modify and surface guidance.
  //
  // TS 5.0+ also supports `extends` as an array of base configs — treat both
  // forms equivalently.
  const extendsValue = tsconfig.extends;
  const hasExtends =
    typeof extendsValue === "string" ||
    (Array.isArray(extendsValue) && extendsValue.length > 0);
  const includeIsAbsentOrEmpty =
    !hasOwnIncludeKey || (existingInclude?.length ?? 0) === 0;
  if (hasExtends && includeIsAbsentOrEmpty) {
    const extendsDescription = Array.isArray(extendsValue)
      ? `extends [${extendsValue.map((v) => JSON.stringify(v)).join(", ")}]`
      : `extends ${JSON.stringify(extendsValue)}`;
    const includeDescription = !hasOwnIncludeKey
      ? "no own `include`"
      : "an explicit empty `include: []`";
    return {
      kind: "extends-without-include",
      reason: `tsconfig.json ${extendsDescription} and has ${includeDescription} — adding one here would override the base's include array`,
    };
  }

  // Use jsonc-parser to compute a minimal edit that preserves all other
  // formatting and comments. The `appendTo` path tells modify() to push
  // onto the existing array; for missing arrays it creates one.
  const newInclude = existingInclude
    ? [...existingInclude, pattern]
    : [pattern];

  const tree = parseTree(raw) as Node | undefined;
  const indent = detectIndent(tree, raw);

  const edits = modify(raw, ["include"], newInclude, {
    formattingOptions: {
      tabSize: indent.size,
      insertSpaces: indent.insertSpaces,
      eol: detectEol(raw),
    },
  });
  const next = applyEdits(raw, edits);
  fs.writeFileSync(tsconfigPath, next, "utf-8");
  return { kind: "added" };
}

function detectIndent(
  tree: Node | undefined,
  raw: string,
): { size: number; insertSpaces: boolean } {
  // Find the first property of the top-level object and inspect the
  // whitespace preceding it. Falls back to 2-space indent.
  if (tree?.type === "object" && tree.children?.length) {
    const firstProp = tree.children[0];
    if (firstProp) {
      const before = raw.slice(0, firstProp.offset);
      const lastNewline = before.lastIndexOf("\n");
      const lead = before.slice(lastNewline + 1);
      if (lead.startsWith("\t")) {
        return { size: 1, insertSpaces: false };
      }
      const spaces = lead.match(/^ +/);
      if (spaces) {
        return { size: spaces[0].length, insertSpaces: true };
      }
    }
  }
  return { size: 2, insertSpaces: true };
}

function detectEol(raw: string): "\n" | "\r\n" {
  return raw.includes("\r\n") ? "\r\n" : "\n";
}

function describeIncludeValue(value: unknown): string {
  if (value === null) return "null";
  if (typeof value === "string") return `a string (${JSON.stringify(value)})`;
  if (typeof value === "object") return "an object";
  return `a ${typeof value}`;
}

// ── Main ─────────────────────────────────────────────────────────────

export async function typegen(urls: string[]): Promise<void> {
  const agents = new Map<string, CollectedAgent>();
  let failureCount = 0;

  header("Fetching runtime info");

  for (let i = 0; i < urls.length; i++) {
    const url = urls[i]!;
    const label = urls.length > 1 ? `[${i + 1}/${urls.length}] ` : "";

    console.log(`  ${icons.fetch} ${label}${chalk.underline(url)}`);

    try {
      const rawInfo = await fetchRuntimeInfo(url);
      const info = validateRuntimeInfo(rawInfo, url);
      console.log(`    ${chalk.dim("version")} ${chalk.white(info.version)}`);

      const agentNames = Object.keys(info.agents);
      if (agentNames.length === 0) {
        console.log(`    ${icons.warn} ${chalk.yellow("No agents found")}`);
        continue;
      }

      for (const [agentId, agentDesc] of Object.entries(info.agents)) {
        if (agents.has(agentId)) {
          console.log(
            `    ${icons.warn} ${chalk.yellow(`Agent "${agentId}" reported by an earlier URL too — keeping latest (multi-runtime merge: last wins)`)}`,
          );
        }

        agents.set(agentId, {
          name: agentDesc.name,
          description: agentDesc.description,
          className: agentDesc.className,
        });

        console.log(
          `    ${icons.agent} ${chalk.magenta(agentId)} ${chalk.dim("·")} ${agentDesc.className}`,
        );
      }
    } catch (error) {
      failureCount++;
      console.log(
        `    ${icons.err} ${chalk.red(`Failed: ${error instanceof Error ? error.message : String(error)}`)}`,
      );
    }

    if (i < urls.length - 1) console.log();
  }

  if (agents.size === 0) {
    console.log();
    console.error(
      `  ${icons.err} ${chalk.red.bold("No agents discovered. Nothing to generate.")}`,
    );
    console.log();
    process.exit(1);
  }

  header("Generating types");

  const projectRoot = findProjectRoot(process.cwd());
  if (!projectRoot) {
    console.error(
      `  ${icons.err} ${chalk.red.bold("No package.json found at or above current directory — cannot locate project root.")}`,
    );
    process.exit(1);
  }
  if (projectRoot !== process.cwd()) {
    console.log(
      `  ${icons.skip} ${chalk.dim(`Project root: ${path.relative(process.cwd(), projectRoot) || "."}`)}`,
    );
  }

  const outDir = path.join(projectRoot, ".copilotkit");

  try {
    if (!fs.existsSync(outDir)) {
      fs.mkdirSync(outDir, { recursive: true });
    }
  } catch (error) {
    console.error(
      `  ${icons.err} ${chalk.red(`Failed to create ${outDir}: ${error instanceof Error ? error.message : String(error)}`)}`,
    );
    process.exit(1);
  }

  const typesPath = path.join(outDir, "types.ts");
  const registerPath = path.join(outDir, "register.d.ts");
  try {
    fs.writeFileSync(typesPath, generateTypesFile(agents), "utf-8");
    fs.writeFileSync(registerPath, generateRegisterFile(), "utf-8");
  } catch (error) {
    console.error(
      `  ${icons.err} ${chalk.red(`Failed to write generated files: ${error instanceof Error ? error.message : String(error)}`)}`,
    );
    process.exit(1);
  }

  console.log(
    `  ${icons.file} ${chalk.green(path.relative(projectRoot, typesPath))}`,
  );
  console.log(
    `  ${icons.file} ${chalk.green(path.relative(projectRoot, registerPath))}`,
  );

  const gitignoreUpdated = ensureGitignore(projectRoot, ".copilotkit/");
  const tsconfigResult = ensureTsconfigInclude(projectRoot);

  const hasConfigOutput =
    gitignoreUpdated || tsconfigResult.kind !== "already-present";

  if (hasConfigOutput) {
    header("Updating project config");

    if (gitignoreUpdated) {
      console.log(
        `  ${icons.file} ${chalk.white(".gitignore")} ${chalk.dim("— added .copilotkit/")}`,
      );
    }

    switch (tsconfigResult.kind) {
      case "added":
        console.log(
          `  ${icons.file} ${chalk.white("tsconfig.json")} ${chalk.dim("— added .copilotkit/register.d.ts to include")}`,
        );
        break;
      case "not-found":
        console.log(
          `  ${icons.warn} ${chalk.yellow("tsconfig.json")} ${chalk.dim("— not found, skipped")}`,
        );
        break;
      case "unparseable":
        console.log(
          `  ${icons.err} ${chalk.red("tsconfig.json")} ${chalk.dim(`— ${tsconfigResult.reason}, skipped`)}`,
        );
        console.log(
          `    ${chalk.dim("Add ")}${chalk.cyan('"include": [".copilotkit/register.d.ts"]')}${chalk.dim(" manually to enable type-safe agent IDs.")}`,
        );
        break;
      case "extends-without-include":
        console.log(
          `  ${icons.warn} ${chalk.yellow("tsconfig.json")} ${chalk.dim(`— ${tsconfigResult.reason}, skipped`)}`,
        );
        console.log(
          `    ${chalk.dim("Add ")}${chalk.cyan('".copilotkit/register.d.ts"')}${chalk.dim(" to the ")}${chalk.cyan('"include"')}${chalk.dim(" array of the tsconfig that extends your base config.")}`,
        );
        break;
      case "invalid-include-type":
        console.log(
          `  ${icons.err} ${chalk.red("tsconfig.json")} ${chalk.dim(`— ${tsconfigResult.reason}, skipped`)}`,
        );
        console.log(
          `    ${chalk.dim("Fix your ")}${chalk.cyan('"include"')}${chalk.dim(" to be an array of strings, then re-run.")}`,
        );
        break;
      case "already-present":
        // No output needed
        break;
    }
  }

  console.log();

  if (failureCount > 0) {
    console.error(
      `  ${icons.err} ${chalk.red.bold(`Generated types for ${agents.size} agent${agents.size === 1 ? "" : "s"}, but ${failureCount} runtime URL${failureCount === 1 ? "" : "s"} failed.`)} ${chalk.dim("Exiting non-zero — generated types may be incomplete.")}`,
    );
    console.log();
    process.exit(1);
  }

  console.log(
    `  ${chalk.green.bold("Done!")} ${chalk.dim("Discovered")} ${chalk.bold(String(agents.size))} ${chalk.dim(`agent${agents.size === 1 ? "" : "s"}`)}${chalk.dim(".")}`,
  );
  console.log(`  ${chalk.dim("Your agent IDs are now type-safe.")}`);
  console.log();
}
