import type { RuntimeInfo } from "@copilotkit/shared";
import chalk from "chalk";
import * as fs from "node:fs";
import * as path from "node:path";

interface CollectedAgent {
  name: string;
  description: string;
  className: string;
}

// ── Pretty-print helpers ─────────────────────────────────────────────

const icons = {
  fetch: chalk.cyan("~"),
  ok: chalk.green("*"),
  warn: chalk.yellow("!"),
  err: chalk.red("x"),
  file: chalk.green("+"),
  skip: chalk.dim("-"),
  agent: chalk.magenta(">"),
} as const;

function header(text: string) {
  const line = chalk.dim("─".repeat(48));
  console.log(`\n  ${line}`);
  console.log(`  ${chalk.bold(text)}`);
  console.log(`  ${line}\n`);
}

// ── Network ──────────────────────────────────────────────────────────

/**
 * Fetch runtime info from a URL.
 * Tries multi-endpoint GET /info first, then falls back to single-endpoint POST.
 */
async function fetchRuntimeInfo(url: string): Promise<RuntimeInfo> {
  const baseUrl = url.replace(/\/+$/, "");

  try {
    const infoUrl = `${baseUrl}/info`;
    const response = await fetch(infoUrl, {
      method: "GET",
      headers: { Accept: "application/json" },
    });
    if (response.ok) {
      return (await response.json()) as RuntimeInfo;
    }
  } catch {
    // Ignore — try single-endpoint fallback
  }

  const response = await fetch(baseUrl, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Accept: "application/json",
    },
    body: JSON.stringify({ method: "info" }),
  });

  if (!response.ok) {
    throw new Error(`${response.status} ${response.statusText}`);
  }

  return (await response.json()) as RuntimeInfo;
}

// ── Code generation ──────────────────────────────────────────────────

function generateTypesFile(agents: Map<string, CollectedAgent>): string {
  const lines: string[] = [];
  lines.push("// Auto-generated by @copilotkit/cli typegen");
  lines.push("// Do not edit manually\n");

  lines.push("export type Agents = {");
  for (const [agentId, agent] of agents) {
    const desc = agent.description ? ` // ${agent.description}` : "";
    lines.push(`  "${agentId}": {${desc}`);
    lines.push(`    description: ${JSON.stringify(agent.description ?? "")};`);
    lines.push("  };");
  }
  lines.push("};");

  return lines.join("\n") + "\n";
}

function generateRegisterFile(): string {
  return `// Auto-generated by @copilotkit/cli typegen
// Do not edit manually

import type { Agents } from "./types";

declare module "@copilotkit/react-core/v2" {
  interface Register {
    agents: Agents;
  }
}
`;
}

// ── Project config updates ───────────────────────────────────────────

function ensureGitignore(projectDir: string, pattern: string): boolean {
  const gitignorePath = path.join(projectDir, ".gitignore");

  let content = "";
  if (fs.existsSync(gitignorePath)) {
    content = fs.readFileSync(gitignorePath, "utf-8");
  }

  const lines = content.split("\n");
  if (lines.some((line) => line.trim() === pattern)) {
    return false;
  }

  const newContent = content.endsWith("\n")
    ? `${content}${pattern}\n`
    : `${content}\n${pattern}\n`;
  fs.writeFileSync(gitignorePath, newContent, "utf-8");
  return true;
}

function ensureTsconfigInclude(projectDir: string): boolean | null {
  const tsconfigPath = path.join(projectDir, "tsconfig.json");
  if (!fs.existsSync(tsconfigPath)) {
    return null;
  }

  const raw = fs.readFileSync(tsconfigPath, "utf-8");
  let tsconfig: Record<string, unknown>;
  try {
    tsconfig = JSON.parse(raw);
  } catch {
    return null;
  }

  const include = (tsconfig.include as string[]) ?? [];
  const pattern = ".copilotkit/register.d.ts";

  if (include.includes(pattern)) {
    return false;
  }

  include.push(pattern);
  tsconfig.include = include;
  fs.writeFileSync(
    tsconfigPath,
    JSON.stringify(tsconfig, null, 2) + "\n",
    "utf-8",
  );
  return true;
}

// ── Main ─────────────────────────────────────────────────────────────

export async function typegen(urls: string[]): Promise<void> {
  const agents = new Map<string, CollectedAgent>();

  header("Fetching runtime info");

  for (let i = 0; i < urls.length; i++) {
    const url = urls[i]!;
    const label = urls.length > 1 ? `[${i + 1}/${urls.length}] ` : "";

    console.log(`  ${icons.fetch} ${label}${chalk.underline(url)}`);

    try {
      const info = await fetchRuntimeInfo(url);
      console.log(`    ${chalk.dim("version")} ${chalk.white(info.version)}`);

      const agentNames = Object.keys(info.agents);
      if (agentNames.length === 0) {
        console.log(`    ${icons.warn} ${chalk.yellow("No agents found")}`);
        continue;
      }

      for (const [agentId, agentDesc] of Object.entries(info.agents)) {
        if (agents.has(agentId)) {
          console.log(
            `    ${icons.warn} ${chalk.yellow(`Agent "${agentId}" already discovered — overwriting (last wins)`)}`,
          );
        }

        agents.set(agentId, {
          name: agentDesc.name,
          description: agentDesc.description,
          className: agentDesc.className,
        });

        console.log(
          `    ${icons.agent} ${chalk.magenta(agentId)} ${chalk.dim("·")} ${agentDesc.className}`,
        );
      }
    } catch (error) {
      console.log(
        `    ${icons.err} ${chalk.red(`Failed: ${error instanceof Error ? error.message : String(error)}`)}`,
      );
    }

    if (i < urls.length - 1) console.log();
  }

  if (agents.size === 0) {
    console.log();
    console.error(
      `  ${icons.err} ${chalk.red.bold("No agents discovered. Nothing to generate.")}`,
    );
    console.log();
    process.exit(1);
  }

  header("Generating types");

  const cwd = process.cwd();
  const outDir = path.join(cwd, ".copilotkit");

  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
  }

  const typesContent = generateTypesFile(agents);
  const typesPath = path.join(outDir, "types.ts");
  fs.writeFileSync(typesPath, typesContent, "utf-8");
  console.log(`  ${icons.file} ${chalk.green(path.relative(cwd, typesPath))}`);

  const registerContent = generateRegisterFile();
  const registerPath = path.join(outDir, "register.d.ts");
  fs.writeFileSync(registerPath, registerContent, "utf-8");
  console.log(
    `  ${icons.file} ${chalk.green(path.relative(cwd, registerPath))}`,
  );

  const gitignoreUpdated = ensureGitignore(cwd, ".copilotkit/");
  const tsconfigResult = ensureTsconfigInclude(cwd);

  const hasConfigChanges =
    gitignoreUpdated || tsconfigResult === true || tsconfigResult === null;

  if (hasConfigChanges) {
    header("Updating project config");

    if (gitignoreUpdated) {
      console.log(
        `  ${icons.file} ${chalk.white(".gitignore")} ${chalk.dim("— added .copilotkit/")}`,
      );
    }

    if (tsconfigResult === true) {
      console.log(
        `  ${icons.file} ${chalk.white("tsconfig.json")} ${chalk.dim("— added .copilotkit/register.d.ts to include")}`,
      );
    } else if (tsconfigResult === null) {
      console.log(
        `  ${icons.warn} ${chalk.yellow("tsconfig.json")} ${chalk.dim("— not found or unparseable, skipped")}`,
      );
    }
  }

  console.log();
  console.log(
    `  ${chalk.green.bold("Done!")} ${chalk.dim("Discovered")} ${chalk.bold(String(agents.size))} ${chalk.dim(`agent${agents.size === 1 ? "" : "s"}`)}${chalk.dim(".")}`,
  );
  console.log(`  ${chalk.dim("Your agent IDs are now type-safe.")}`);
  console.log();
}
