import { test, expect } from "@playwright/test";

/**
 * Regression coverage for the byoc-json-render demo's three
 * pre-seeded suggestion pills. Mirrors the byoc-hashbrown regression
 * suite so any fan-out drift between the two BYOC demos is caught
 * symmetrically. The shared user-reported failure mode is: pill click
 * produced no structured output. We click each pill and assert the
 * catalog component(s) the json-render fixture is expected to emit.
 *
 * Generated by showcase/scripts/generate-byoc-regression-tests.sh —
 * edit the template there, not the per-integration copies.
 */
const SUGGESTION_TIMEOUT_MS = 60_000;

test.describe("BYOC json-render — pill suggestion regression", () => {
  test.beforeEach(async ({ page }) => {
    await page.goto("/demos/byoc-json-render");
  });

  test("page loads with all three suggestion pills", async ({ page }) => {
    await expect(
      page.getByRole("button", { name: "Sales dashboard" }),
    ).toBeVisible();
    await expect(
      page.getByRole("button", { name: "Revenue by category" }),
    ).toBeVisible();
    await expect(
      page.getByRole("button", { name: "Expense trend" }),
    ).toBeVisible();
  });

  test("Sales dashboard pill renders metric card + bar chart", async ({
    page,
  }) => {
    await page.getByRole("button", { name: "Sales dashboard" }).click();

    // The json-render Sales dashboard fixture renders a MetricCard plus
    // a BarChart (no pie chart). Both should appear inside the
    // json-render-root wrapper.
    await expect(
      page.locator('[data-testid="json-render-root"]').first(),
    ).toBeVisible({ timeout: SUGGESTION_TIMEOUT_MS });
    await expect(
      page.locator('[data-testid="metric-card"]').first(),
    ).toBeVisible({ timeout: SUGGESTION_TIMEOUT_MS });
    await expect(page.locator('[data-testid="bar-chart"]').first()).toBeVisible(
      { timeout: SUGGESTION_TIMEOUT_MS },
    );
  });

  test("Revenue by category pill renders a pie chart", async ({ page }) => {
    await page.getByRole("button", { name: "Revenue by category" }).click();
    await expect(page.locator('[data-testid="pie-chart"]').first()).toBeVisible(
      { timeout: SUGGESTION_TIMEOUT_MS },
    );
  });

  test("Expense trend pill renders a bar chart", async ({ page }) => {
    await page.getByRole("button", { name: "Expense trend" }).click();
    await expect(page.locator('[data-testid="bar-chart"]').first()).toBeVisible(
      { timeout: SUGGESTION_TIMEOUT_MS },
    );
  });
});
