import { Signal, inject } from "@angular/core";
import type { StandardSchemaV1 } from "@copilotkit/shared";
import { z } from "zod";
import { CopilotKit } from "./copilotkit";

/**
 * A function exposed to sandboxed UI generated by the LLM via
 * `openGenerativeUI`. Each function is described to the LLM via agent
 * context and exposed to the iframe via `Websandbox.connection.remote.<fn>`.
 */
export type SandboxFunction<
  TParams extends StandardSchemaV1 = StandardSchemaV1,
> = {
  name: string;
  description: string;
  parameters: TParams;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  handler: (args: any) => Promise<unknown>;
};

/**
 * Activity-message type emitted by the runtime when the LLM is generating
 * sandboxed UI via the built-in `generateSandboxedUi` tool.
 */
export const OpenGenerativeUIActivityType = "open-generative-ui";

/**
 * Schema for the activity-message content streamed while sandboxed UI is
 * being generated. Each field arrives in stages — the renderer reacts to
 * the `*Complete` flags to flip between placeholder, preview, and final.
 */
export const OpenGenerativeUIContentSchema = z.object({
  initialHeight: z.number().optional(),
  generating: z.boolean().optional(),
  css: z.string().optional(),
  cssComplete: z.boolean().optional(),
  html: z.array(z.string()).optional(),
  htmlComplete: z.boolean().optional(),
  jsFunctions: z.string().optional(),
  jsFunctionsComplete: z.boolean().optional(),
  jsExpressions: z.array(z.string()).optional(),
  jsExpressionsComplete: z.boolean().optional(),
});

export type OpenGenerativeUIContent = z.infer<
  typeof OpenGenerativeUIContentSchema
>;

/**
 * Schema for the `generateSandboxedUi` tool-call arguments. Used by the
 * tool renderer to display placeholder messages while generation is in
 * progress.
 */
export const GenerateSandboxedUiArgsSchema = z.object({
  initialHeight: z.number().optional(),
  placeholderMessages: z.array(z.string()).optional(),
  css: z.string().optional(),
  html: z.string().optional(),
  jsFunctions: z.string().optional(),
  jsExpressions: z.array(z.string()).optional(),
});

export type GenerateSandboxedUiArgs = z.infer<
  typeof GenerateSandboxedUiArgsSchema
>;

/**
 * Default agent-context content describing how the LLM should style
 * sandboxed UI when no `designSkill` override is provided. Mirrors the
 * React provider's default verbatim so generated UI looks identical
 * across SDKs.
 */
export const DEFAULT_DESIGN_SKILL = `When generating UI with generateSandboxedUi, follow these design principles inspired by shadcn/ui:

- Use a minimal, flat aesthetic. Avoid drop shadows and gradients — rely on subtle borders (1px solid, light gray like #e5e7eb) to define surfaces.
- Neutral base palette: white backgrounds, zinc/slate gray text (#09090b for headings, #71717a for secondary text). One accent color for interactive elements.
- Use system font stacks (system-ui, -apple-system, sans-serif) at readable sizes (14px body, 600 weight for headings). Tight line-heights.
- Small, consistent border-radius (6–8px). Cards and containers use border, not shadow, for separation.
- Buttons: solid fill for primary (dark bg, white text), outline for secondary (border + transparent bg). Subtle hover state (slight opacity or background shift).
- Use CSS Grid or Flexbox for layout. Ensure the UI looks good at any width.
- Minimal transitions (150ms) for hover/focus states only. No decorative animations.
- Keep the UI focused and dense — avoid excessive padding. Use compact spacing (8–12px gaps, 10–14px padding in controls).`;

/**
 * Description sent to the LLM for the auto-registered `generateSandboxedUi`
 * frontend tool. Mirrors the React provider's description verbatim.
 */
export const GENERATE_SANDBOXED_UI_DESCRIPTION =
  "Generate sandboxed UI. " +
  "IMPORTANT: The generated code runs in a sandboxed iframe WITHOUT same-origin access. " +
  "Do NOT use localStorage, sessionStorage, document.cookie, IndexedDB, or fetch/XMLHttpRequest to same-origin URLs. " +
  "To communicate with the host application, use Websandbox.connection.remote.<functionName>(args) which returns a Promise.\n\n" +
  "You CAN use external libraries from CDNs by including <script> or <link> tags in the HTML <head> (e.g., Chart.js, D3, Three.js, x-data-spreadsheet, etc.). " +
  "CDN resources load normally inside the sandbox.\n\n" +
  "PARAMETER ORDER IS CRITICAL — generate parameters in exactly this order:\n" +
  "1. initialHeight + placeholderMessages (shown to user while generating)\n" +
  "2. css (all styles FIRST — the user sees a placeholder until CSS is complete)\n" +
  "3. html (streams in live — the user watches the UI build as HTML is generated)\n" +
  "4. jsFunctions (reusable helper functions)\n" +
  "5. jsExpressions (applied one-by-one — the user sees each expression take effect)";

/**
 * Configuration for OpenGenerativeUI — sandboxed UI generated by the LLM.
 *
 * Mirrors React's `openGenerativeUI` prop on `CopilotKitProvider`.
 */
export interface OpenGenerativeUIConfig {
  /**
   * Functions made available inside sandboxed iframes.
   * Each function is described to the LLM via agent context and exposed
   * via websandbox's `localApi`.
   */
  sandboxFunctions?: SandboxFunction[];
  /**
   * Design guidelines injected as agent context for the `generateSandboxedUi`
   * tool. Override to control the visual style of generated UIs.
   *
   * A sensible default is provided if omitted.
   */
  designSkill?: string;
}

/**
 * Angular equivalent of React's `useSandboxFunctions`.
 *
 * Returns the list of sandbox functions configured via
 * `provideCopilotKit({ openGenerativeUI: { sandboxFunctions: [...] } })`
 * as a readonly signal. When no functions are configured, the signal
 * resolves to an empty array.
 *
 * Must be invoked in an Angular DI / injection context.
 */
export function injectSandboxFunctions(): Signal<readonly SandboxFunction[]> {
  return inject(CopilotKit).sandboxFunctions;
}
