import { Signal, inject } from "@angular/core";
import type { StandardSchemaV1 } from "@copilotkit/shared";
import { CopilotKit } from "./copilotkit";

/**
 * A function exposed to sandboxed UI generated by the LLM via
 * `openGenerativeUI`. Each function is described to the LLM via agent
 * context and exposed to the iframe via `Websandbox.connection.remote.<fn>`.
 */
export type SandboxFunction<
  TParams extends StandardSchemaV1 = StandardSchemaV1,
> = {
  name: string;
  description: string;
  parameters: TParams;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  handler: (args: any) => Promise<unknown>;
};

/**
 * Configuration for OpenGenerativeUI — sandboxed UI generated by the LLM.
 *
 * Mirrors React's `openGenerativeUI` prop on `CopilotKitProvider`.
 */
export interface OpenGenerativeUIConfig {
  /**
   * Functions made available inside sandboxed iframes.
   * Each function is described to the LLM via agent context and exposed
   * via websandbox's `localApi`.
   */
  sandboxFunctions?: SandboxFunction[];
  /**
   * Design guidelines injected as agent context for the `generateSandboxedUi`
   * tool. Override to control the visual style of generated UIs.
   *
   * A sensible default is provided if omitted.
   */
  designSkill?: string;
}

/**
 * Angular equivalent of React's `useSandboxFunctions`.
 *
 * Returns the list of sandbox functions configured via
 * `provideCopilotKit({ openGenerativeUI: { sandboxFunctions: [...] } })`
 * as a readonly signal. When no functions are configured, the signal
 * resolves to an empty array.
 *
 * Must be invoked in an Angular DI / injection context.
 */
export function injectSandboxFunctions(): Signal<readonly SandboxFunction[]> {
  return inject(CopilotKit).sandboxFunctions;
}
