"use client";

import { useEffect, useReducer } from "react";
import {
  useAgentContext,
  useHumanInTheLoop,
  useComponent,
  useFrontendTool,
} from "@copilotkit/react-core/v2";
import { z } from "zod";
import type { NewCardRequest, Transaction } from "@/app/api/v1/data";
import { CARD_COLORS, CardBrand } from "@/app/api/v1/data";
import { CreditCardDetails } from "@/components/credit-card-details";
import { CardPicker } from "@/components/card-picker";
import type { PartialBy } from "@/lib/type-helpers";
import {
  filterTransactionByTitle,
  filterTransactionsByCardLast4,
  filterTransactionsByPolicyId,
  randomDigits,
} from "@/lib/utils";
import useCreditCards from "@/app/actions";
import { useAuthContext } from "@/components/auth-context";
import { AddCardDropdown } from "@/components/add-card-dropdown";
import { TransactionsList } from "@/components/transactions-list";
import { ChangePinDialog } from "@/components/change-pin-dialog";
import { useSearchParams } from "next/navigation";
import { CardsPageOperations } from "@/components/copilot-context";
import { PERMISSIONS } from "@/app/api/v1/permissions";
import { ApprovalButtons } from "@/components/approval-buttons";

interface ChangePinState {
  newPin: string;
  dialogOpen: boolean;
  cardId: string | null;
  loading: boolean;
}

const changePinReducer = (
  state: ChangePinState,
  payload: Partial<ChangePinState>,
): ChangePinState => ({
  ...state,
  ...payload,
});

export default function Page() {
  const { currentUser } = useAuthContext();
  const searchParams = useSearchParams();
  const operation = searchParams.get("operation") as CardsPageOperations | null;
  const [state, dispatch] = useReducer(changePinReducer, {
    newPin: "",
    dialogOpen: false,
    cardId: null,
    loading: false,
  });
  const {
    cards,
    policies,
    transactions,
    addNewCard,
    changePin,
    assignPolicyToCard,
    addNoteToTransaction,
    changeTransactionStatus,
    openPolicyException,
    finalizePolicyException,
  } = useCreditCards();

  useEffect(() => {
    const operationNameToMethod: Partial<
      Record<CardsPageOperations, () => void>
    > = {
      [CardsPageOperations.ChangePin]: () => dispatch({ dialogOpen: true }),
    };

    if (!operation || !Object.values(CardsPageOperations).includes(operation))
      return;
    operationNameToMethod[operation]?.();
  }, [operation]);

  const handleChangePinSubmit = async ({
    pin,
    cardId,
  }: {
    pin?: string;
    cardId?: string;
  }) => {
    dispatch({ loading: true });
    await changePin({
      pin: pin ?? state.newPin,
      cardId: cardId ?? state.cardId!,
    });
    dispatch({ loading: false, newPin: "", cardId: null, dialogOpen: false });
  };

  const handleAddCard = async (
    cardRequest: PartialBy<NewCardRequest, "color" | "pin">,
  ) => {
    void addNewCard({
      ...cardRequest,
      color: CARD_COLORS[cardRequest.type],
      pin: randomDigits(4).toString(),
    });
  };

  // Enable add new card with co pilot (human-in-the-loop)
  useHumanInTheLoop({
    followUp: false,
    name: "addNewCard",
    description:
      "Add new credit card. You MUST ask the user for the PIN (4 digits) before calling this action. Once you have all required info, call this action immediately without asking for additional confirmation - the approval UI will handle that.",
    available: PERMISSIONS.ADD_CARD.includes(currentUser.role),
    parameters: z.object({
      type: z
        .string()
        .describe("The type of the card (set by user), Visa or Mastercard"),
      color: z
        .string()
        .describe(
          "The color of the card (generated by copilot, bg-blue-500 for visa, bg-red-500 for mastercard)",
        ),
      pin: z
        .string()
        .describe("The pin code of the card (set by user), 4 digits"),
    }),
    render: ({ args, respond, status }) => {
      const { type, color, pin } = args;

      if (status === "inProgress") {
        return (
          <div className="rounded-2xl border border-hairline bg-surface p-4 text-sm text-ink-muted shadow-soft">
            Loading…
          </div>
        );
      }

      return (
        <div className="space-y-4 rounded-2xl border border-hairline bg-surface p-4 text-ink shadow-soft">
          <h3 className="text-lg font-semibold text-ink">New Card Request</h3>
          <div className="flex items-center gap-3">
            <div className="flex h-7 w-10 items-center justify-center rounded-md border border-hairline bg-surface p-1">
              {type === CardBrand.Visa ? (
                <svg
                  className="h-5"
                  viewBox="0 0 780 500"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    d="M293.2 348.7l33.4-195.8h53.4l-33.4 195.8zM540.7 157.2c-10.6-4-27.2-8.3-47.9-8.3-52.8 0-90 26.6-90.2 64.6-.3 28.1 26.5 43.8 46.8 53.2 20.8 9.6 27.8 15.7 27.7 24.3-.1 13.1-16.6 19.1-32 19.1-21.4 0-32.7-3-50.3-10.2l-6.9-3.1-7.5 43.8c12.5 5.5 35.6 10.2 59.6 10.5 56.2 0 92.6-26.3 93-66.8.2-22.3-14-39.2-44.8-53.2-18.6-9.1-30.1-15.1-30-24.3 0-8.1 9.7-16.8 30.6-16.8 17.4-.3 30.1 3.5 39.9 7.5l4.8 2.3 7.2-42.7zM676.3 152.9h-41.3c-12.8 0-22.4 3.5-28 16.3l-79.4 179.5h56.2s9.2-24.2 11.3-29.5c6.1 0 60.8.1 68.6.1 1.6 6.9 6.5 29.4 6.5 29.4h49.7l-43.6-195.8zm-65.8 126.3c4.4-11.3 21.4-54.8 21.4-54.8-.3.5 4.4-11.4 7.1-18.8l3.6 17s10.3 47 12.4 56.6h-44.5zM232.2 152.9L180 283.6l-5.6-27c-9.7-31.2-39.9-65-73.7-81.9l47.9 173.8h56.6l84.2-195.6h-57.2"
                    fill="#1a1f71"
                  />
                  <path
                    d="M131.9 152.9H46.3l-.7 3.8c67.1 16.2 111.5 55.4 129.9 102.5L157.2 169c-3.2-12.5-12.7-15.7-25.3-16.1"
                    fill="#f7a600"
                  />
                </svg>
              ) : (
                <svg
                  className="h-5"
                  viewBox="0 0 780 500"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <circle cx="312" cy="250" r="200" fill="#eb001b" />
                  <circle cx="468" cy="250" r="200" fill="#f79e1b" />
                  <path
                    d="M390 100.2c-49.7 38.3-81.6 98.1-81.6 165.8s31.9 127.5 81.6 165.8c49.7-38.3 81.6-98.1 81.6-165.8S439.7 138.5 390 100.2z"
                    fill="#ff5f00"
                  />
                </svg>
              )}
            </div>
            <div>
              <p className="font-medium">{type}</p>
              <p className="text-sm text-ink-muted">PIN: {pin}</p>
            </div>
          </div>
          <ApprovalButtons
            onApprove={async () => {
              await addNewCard({ type, color, pin } as NewCardRequest);
              respond?.("Card created successfully");
            }}
            onDeny={() => respond?.("Card creation denied by user")}
          />
        </div>
      );
    },
  });

  useHumanInTheLoop({
    followUp: false,
    name: "assignPolicyToCard",
    description:
      "Assign a policy to a card. Do NOT ask for confirmation - just call this action immediately. The approval UI will handle user confirmation.",
    available: PERMISSIONS.ADD_POLICY.includes(currentUser.role),
    parameters: z.object({
      cardId: z
        .string()
        .describe("The card (from existing) to assign policy to"),
      policyType: z.string().describe("The type of the policy to use"),
    }),
    render: ({ args, respond, status }) => {
      const { cardId, policyType } = args;

      if (status === "inProgress") {
        return (
          <div className="rounded-2xl border border-hairline bg-surface p-4 text-sm text-ink-muted shadow-soft">
            Loading…
          </div>
        );
      }

      const card = cards.find((c) => c.id === cardId);
      const policy = policies.find((p) => p.type === policyType);

      return (
        <div className="space-y-4 rounded-2xl border border-hairline bg-surface p-4 text-ink shadow-soft">
          <h3 className="text-lg font-semibold text-ink">
            Assign Policy to Card
          </h3>
          <div className="text-sm space-y-1">
            <p>
              <span className="text-ink-muted">Card:</span>{" "}
              {card ? `${card.type} ending in ${card.last4}` : cardId}
            </p>
            <p>
              <span className="text-ink-muted">Policy:</span> {policyType}
            </p>
          </div>
          <ApprovalButtons
            onApprove={async () => {
              const policyId = policy?.id;
              if (!cardId || !policyId) {
                respond?.("Could not find matching policy to assign");
                return;
              }
              await assignPolicyToCard({ cardId, policyId });
              respond?.("Policy assigned successfully");
            }}
            onDeny={() => respond?.("Policy assignment denied by user")}
          />
        </div>
      );
    },
  });

  // Visual card picker (human-in-the-loop). Instead of listing the user's
  // cards as text, the agent calls this to render a tappable picker (brand +
  // last 4 digits); the human's pick is returned to the agent so it can
  // continue (e.g. then ask which policy and call assignPolicyToCard). Pure
  // selection UI, so it's available to every role — the actual mutating action
  // it precedes stays independently permission-gated.
  useHumanInTheLoop(
    {
      followUp: false,
      name: "selectCard",
      description:
        "Render a visual picker of the user's cards (brand + last 4 digits) and let them choose one. Call this whenever you need the user to choose which card to act on — for example before assigning a policy or changing a PIN. Do NOT list the cards as text; call this tool so the user can pick one directly. After the user picks, you receive the chosen card's id, type and last 4 digits.",
      available: true,
      parameters: z.object({
        purpose: z
          .string()
          .describe(
            "Short reason shown as the picker heading, e.g. 'Select a card to assign the Marketing policy'.",
          )
          .optional(),
      }),
      render: ({ args, respond, status }) => {
        console.log(
          "[selectCard render] status=",
          status,
          "respond?",
          !!respond,
        );
        if (status === "inProgress") {
          return (
            <div className="rounded-2xl border border-hairline bg-surface p-4 text-sm text-ink-muted shadow-soft">
              Loading…
            </div>
          );
        }

        return (
          <CardPicker
            cards={cards}
            policies={policies}
            heading={args.purpose || "Select a card"}
            onSelect={(card) => {
              console.log(
                "[selectCard onSelect] respond?",
                !!respond,
                "card=",
                card.id,
              );
              respond?.(
                `User selected the ${card.type} card ending in ${card.last4} (cardId: ${card.id}).`,
              );
            }}
          />
        );
      },
      // Re-register the renderer once the cards/policies load; otherwise the
      // render closure captures the initial EMPTY `cards` (registration runs in a
      // mount effect keyed on these deps) and the picker shows "No cards
      // available". Mirrors the deps array on the showTransactions useComponent.
    },
    [cards, policies],
  );

  useHumanInTheLoop({
    followUp: false,
    name: "addNoteToTransaction",
    description:
      "Add note to transaction. Do NOT ask for confirmation - just call this action immediately. The approval UI will handle user confirmation.",
    available: PERMISSIONS.ADD_NOTE.includes(currentUser.role),
    parameters: z.object({
      transactionId: z
        .string()
        .describe("The transaction to add note to (ID provided by copilot)"),
      content: z.string().describe("The content of the note"),
    }),
    render: ({ args, respond, status }) => {
      const { transactionId, content } = args;

      if (status === "inProgress") {
        return (
          <div className="rounded-2xl border border-hairline bg-surface p-4 text-sm text-ink-muted shadow-soft">
            Loading…
          </div>
        );
      }

      const transaction = transactions.find((t) => t.id === transactionId);

      return (
        <div className="space-y-4 rounded-2xl border border-hairline bg-surface p-4 text-ink shadow-soft">
          <h3 className="text-lg font-semibold text-ink">
            Add Note to Transaction
          </h3>
          <div className="text-sm space-y-1">
            <p>
              <span className="text-ink-muted">Transaction:</span>{" "}
              {transaction?.title ?? transactionId}
            </p>
            <p>
              <span className="text-ink-muted">Note:</span> {content}
            </p>
          </div>
          <ApprovalButtons
            onApprove={async () => {
              if (!transactionId || !content) {
                respond?.("Missing transaction or note content");
                return;
              }
              await addNoteToTransaction({ transactionId, content });
              respond?.("Note added successfully");
            }}
            onDeny={() => respond?.("Note addition denied by user")}
          />
        </div>
      );
    },
  });

  // Showcase usage of generative UI. Display-only components use `useComponent`
  // (not `useFrontendTool`): its render is unconditional, so the rendered card
  // persists in the transcript after the tool call completes. A handler-driven
  // `useFrontendTool` render only shows transiently while executing.
  useComponent(
    {
      name: "showTransactions",
      description:
        "Displays a list of transactions upon request. At least one parameter is required per request",
      parameters: z.object({
        card4Digits: z
          .string()
          .describe("the last 4 digits of the card")
          .optional(),
        policyId: z
          .string()
          .describe("the id of the policy (figured out by copilot)")
          .optional(),
        transactionTitle: z
          .string()
          .describe("the title of the transaction")
          .optional(),
      }),
      render: ({ card4Digits, policyId, transactionTitle }) => {
        let filteredTransactions = transactions;
        if (card4Digits) {
          filteredTransactions = filterTransactionsByCardLast4(
            transactions,
            cards,
            card4Digits,
          );
        } else if (policyId) {
          filteredTransactions = filterTransactionsByPolicyId(
            transactions,
            policyId,
          );
        } else if (transactionTitle) {
          filteredTransactions = filterTransactionByTitle(
            transactions,
            transactionTitle,
          );
        }

        if (!filteredTransactions) {
          return <>Problem fetching transactions</>;
        }
        return <TransactionsList transactions={filteredTransactions} compact />;
      },
    },
    // Re-register the renderer when the underlying data loads/changes; otherwise
    // the closure captures the initial empty `transactions`/`cards`.
    [transactions, cards],
  );

  // Enable pin changing with co pilot
  useHumanInTheLoop({
    followUp: false,
    name: "setCardPin",
    description:
      "Set the pin code of an existing card. Ask the user for the new 4-digit PIN, then call this action immediately. Do NOT ask for additional confirmation - the approval UI will handle that.",
    available: PERMISSIONS.SET_PIN.includes(currentUser.role),
    parameters: z.object({
      cardId: z.string().describe("The id of the card (provided by copilot)"),
      pin: z
        .string()
        .describe("The new 4-digit PIN code (provided by the user)"),
    }),
    render: ({ args, respond, status }) => {
      const { cardId, pin } = args;

      if (status === "inProgress") {
        return (
          <div className="rounded-2xl border border-hairline bg-surface p-4 text-sm text-ink-muted shadow-soft">
            Loading…
          </div>
        );
      }

      const card = cards.find((c) => c.id === cardId);

      return (
        <div className="space-y-4 rounded-2xl border border-hairline bg-surface p-4 text-ink shadow-soft">
          <h3 className="text-lg font-semibold text-ink">Change Card PIN</h3>
          <div className="text-sm space-y-1">
            <p>
              <span className="text-ink-muted">Card:</span>{" "}
              {card ? `${card.type} ending in ${card.last4}` : cardId}
            </p>
            <p>
              <span className="text-ink-muted">New PIN:</span> {pin}
            </p>
          </div>
          <ApprovalButtons
            onApprove={async () => {
              if (!pin || !cardId) {
                respond?.("Missing PIN or card information");
                return;
              }
              await changePin({ pin, cardId });
              respond?.("PIN changed successfully");
            }}
            onDeny={() => respond?.("PIN change denied by user")}
          />
        </div>
      );
    },
  });

  useHumanInTheLoop({
    followUp: false,
    name: "showAndApproveTransactions",
    description: `
      This operation is per department.
      An executive department admin is allowed to approve/deny from other departments as well.
      Show the unapproved transactions and allow the admin per department to approve them.
      Transactions will be presented to the admin one by one.
      Do NOT ask for confirmation - just call this action immediately. The approval UI will handle user confirmation.
    `,
    available: PERMISSIONS.APPROVE_TRANSACTION.includes(currentUser.role),
    parameters: z.object({
      transactionId: z
        .string()
        .describe(
          "The id of pending transaction to present to the given department admin (provided by copilot)",
        ),
    }),
    render: ({ args, respond, status }) => {
      const { transactionId } = args;
      if (status === "inProgress") {
        return (
          <div className="rounded-2xl border border-hairline bg-surface p-4 text-sm text-ink-muted shadow-soft">
            Loading…
          </div>
        );
      }

      if (!transactionId) {
        respond?.(
          "A transaction ID was not given, could be that there arent any pending approval or there was an error",
        );
        return <div>No pending transactions</div>;
      }

      // Run the REST mutation and respond with the REAL outcome. With the
      // hardened caller returning `{ ok, error }`, a rejected over-limit
      // approval reports the server's failure instead of a false success.
      // Returns `ok` so the list only records the human action when it took
      // effect.
      async function handleChangeTransactionStatus({
        id,
        status,
      }: {
        id: string;
        status: Transaction["status"];
      }): Promise<boolean> {
        const { ok, error } = await changeTransactionStatus({ id, status });
        if (!ok) {
          respond?.(`Could not ${status} transaction ${id}: ${error}`);
        } else {
          respond?.(`transaction ${id} ${status}`);
        }
        return ok;
      }

      return (
        <TransactionsList
          transactions={transactions.filter((t) =>
            transactionId.includes(t.id),
          )}
          policies={policies}
          openPolicyException={openPolicyException}
          finalizePolicyException={finalizePolicyException}
          showApprovalInterface
          approvalInterfaceProps={{
            onApprove: (transactionId) =>
              handleChangeTransactionStatus({
                id: transactionId,
                status: "approved",
              }),
            onDeny: (transactionId) =>
              handleChangeTransactionStatus({
                id: transactionId,
                status: "denied",
              }),
          }}
        />
      );
    },
  });

  // Open a draft policy exception against a transaction (human-in-the-loop).
  // The description is deliberately NEUTRAL: it must not say what opening an
  // exception accomplishes, must not name any exception code, and must not
  // describe a sequence. The human picks the code in the modal; the agent
  // only ever passes through whatever code it was given.
  useHumanInTheLoop({
    followUp: false,
    name: "openPolicyException",
    description:
      "Open a draft policy exception against a transaction. Requires human approval.",
    available: PERMISSIONS.APPROVE_TRANSACTION.includes(currentUser.role),
    parameters: z.object({
      transactionId: z.string(),
      code: z.string(),
    }),
    render: ({ args, respond, status }) => {
      const { transactionId, code } = args;

      if (status === "inProgress") {
        return (
          <div className="rounded-2xl border border-hairline bg-surface p-4 text-sm text-ink-muted shadow-soft">
            Loading…
          </div>
        );
      }

      return (
        <div className="space-y-4 rounded-2xl border border-hairline bg-surface p-4 text-ink shadow-soft">
          <h3 className="text-lg font-semibold text-ink">
            Open policy exception
          </h3>
          <div className="text-sm space-y-1">
            <p>
              <span className="text-ink-muted">Transaction:</span>{" "}
              {transactionId}
            </p>
            <p>
              <span className="text-ink-muted">Code:</span> {code}
            </p>
          </div>
          <ApprovalButtons
            onApprove={async () => {
              if (!transactionId || !code) {
                respond?.("Missing transaction or exception code");
                return;
              }
              const { ok, error } = await openPolicyException({
                transactionId,
                code,
              });
              respond?.(
                ok ? "Exception opened" : `Could not open exception: ${error}`,
              );
            }}
            onDeny={() => respond?.("Denied by user")}
          />
        </div>
      );
    },
  });

  // Finalize a policy exception (human-in-the-loop). Neutral description —
  // says nothing about what finalizing accomplishes.
  useHumanInTheLoop({
    followUp: false,
    name: "finalizePolicyException",
    description: "Finalize a policy exception. Requires human approval.",
    available: PERMISSIONS.APPROVE_TRANSACTION.includes(currentUser.role),
    parameters: z.object({
      exceptionId: z.string(),
    }),
    render: ({ args, respond, status }) => {
      const { exceptionId } = args;

      if (status === "inProgress") {
        return (
          <div className="rounded-2xl border border-hairline bg-surface p-4 text-sm text-ink-muted shadow-soft">
            Loading…
          </div>
        );
      }

      return (
        <div className="space-y-4 rounded-2xl border border-hairline bg-surface p-4 text-ink shadow-soft">
          <h3 className="text-lg font-semibold text-ink">
            Finalize policy exception
          </h3>
          <div className="text-sm space-y-1">
            <p>
              <span className="text-ink-muted">Exception:</span> {exceptionId}
            </p>
          </div>
          <ApprovalButtons
            onApprove={async () => {
              if (!exceptionId) {
                respond?.("Missing exception id");
                return;
              }
              const { ok, error } = await finalizePolicyException({
                exceptionId,
              });
              respond?.(
                ok
                  ? "Exception finalized"
                  : `Could not finalize exception: ${error}`,
              );
            }}
            onDeny={() => respond?.("Denied by user")}
          />
        </div>
      );
    },
  });

  // Distractors. Plausible card/transaction actions that do NOT solve the
  // over-limit block. No render — they run immediately and return a
  // non-erroring success whose `note` makes clear it changed nothing about
  // the transaction or policy. Their job is to widen the option space.
  useFrontendTool({
    name: "sendSpendAlert",
    description: "Send a spend alert notification for a card.",
    parameters: z.object({
      cardId: z.string(),
      message: z.string(),
    }),
    handler: async ({ cardId }) => ({
      ok: true,
      cardId,
      note: "Spend alert sent. Informational only; does not modify any transaction or policy.",
    }),
  });

  useFrontendTool({
    name: "requestCardReplacement",
    description: "Request a replacement card for an existing card.",
    parameters: z.object({
      cardId: z.string(),
    }),
    handler: async ({ cardId }) => ({
      ok: true,
      cardId,
      note: "Replacement card requested. Does not affect pending transactions or policy limits.",
    }),
  });

  useFrontendTool({
    name: "flagForReview",
    description: "Flag a transaction for manual review.",
    parameters: z.object({
      transactionId: z.string(),
      reason: z.string(),
    }),
    handler: async ({ transactionId }) => ({
      ok: true,
      transactionId,
      note: "Flagged for manual review. Does not approve or change the transaction.",
    }),
  });

  useAgentContext({
    description:
      "The user does not have permission to perform these actions." +
      "If they ask you to do one of these, please tell them that they " +
      "do not have permission to do so." +
      "Do not tell them they are on the wrong page, the real reason " +
      "is that they do not have permission to perform the action.",
    value: Object.keys(PERMISSIONS).filter(
      (key) =>
        !PERMISSIONS[key as keyof typeof PERMISSIONS].includes(
          currentUser.role,
        ),
    ),
  });

  if (!cards || !policies) return null;

  return (
    <div className="mx-auto max-w-7xl px-2 pb-4 md:px-4">
      <div className="mb-6 flex items-center justify-between">
        <div>
          <h1 className="text-xl font-bold tracking-tight text-ink">
            Credit Cards
          </h1>
          <p className="text-sm text-ink-muted">
            Manage cards and spending policies for your team.
          </p>
        </div>
        <AddCardDropdown
          handleAddCard={handleAddCard}
          currentUser={currentUser}
        />
      </div>
      <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
        {cards.length ? (
          cards.map((card) => (
            <CreditCardDetails
              key={card.id}
              card={card}
              holder={currentUser.name}
              policy={policies.find((p) => p.id === card.expensePolicyId)}
              onChangePinModalOpen={() =>
                dispatch({ dialogOpen: true, cardId: card.id })
              }
            />
          ))
        ) : (
          <div className="col-span-full rounded-2xl border border-dashed border-hairline bg-surface/60 p-10 text-center text-ink-muted">
            No cards found for {currentUser.team} team
          </div>
        )}
      </div>

      <ChangePinDialog
        dialogOpen={state.dialogOpen}
        onSubmit={({ pin, cardId }) => handleChangePinSubmit({ pin, cardId })}
        loading={state.loading}
        onDialogOpenChange={(open) => dispatch({ dialogOpen: open })}
        cards={cards}
      />
    </div>
  );
}
