[project]
name = "ai_researcher"
version = "0.1.0"
description = "AI Researcher Demo"
authors = [
    {name = "Markus Ecker", email = "markus.ecker@gmail.com"}
]
license = {text = "MIT"}
requires-python = ">=3.12,<3.13"
dependencies = [
    "langgraph",
    "langchain-core>=0.3.25",
    "langchain-openai==0.2.3",
    "langchain-google-genai==2.0.0",
    "langchain==0.3.4",
    "langchain-anthropic==0.2.3",
    "openai>=1.52.1",
    "langchain-community>=0.3.1",
    "tavily-python>=0.5.0",
    "python-dotenv>=1.0.1",
    "uvicorn>=0.31.0",
    "copilotkit==0.1.41",
    "langgraph-cli[inmem]>=0.1.64",
]

[project.scripts]
demo = "ai_researcher.demo:main"

[tool.hatch.build.targets.wheel]
packages = ["ai_researcher"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
