"use client";

// Re-export AG-UI runtime and types to provide a single import surface
// This helps avoid version mismatches by letting apps import everything from '@copilotkitnext/react'
// Note: @ag-ui/client already re-exports everything from @ag-ui/core, so we only export from client
// to avoid conflicting star exports during webpack builds
export {
  AbstractAgent,
  HttpAgent,
  type HttpAgentConfig,
  type AgentSubscriber,
  type RunAgentInput,
  RunAgentInputSchema,
  type RunAgentResult,
  type RunAgentParameters,
  type BaseEvent,
  EventType,
  type RunStartedEvent,
  type RunFinishedEvent,
  type RunErrorEvent,
  type StepStartedEvent,
  type StepFinishedEvent,
  type TextMessageStartEvent,
  type TextMessageContentEvent,
  type TextMessageEndEvent,
  type TextMessageChunkEvent,
  type ToolCallStartEvent,
  type ToolCallArgsEvent,
  type ToolCallEndEvent,
  type ToolCallResultEvent,
  type StateSnapshotEvent,
  type StateDeltaEvent,
  type MessagesSnapshotEvent,
  type ReasoningStartEvent,
  type ReasoningMessageStartEvent,
  type ReasoningMessageContentEvent,
  type ReasoningMessageEndEvent,
  type ReasoningEndEvent,
  type CustomEvent,
  type RawEvent,
  type Message,
  type UserMessage,
  type AssistantMessage,
  type ToolMessage,
  type ActivityMessage,
  type ReasoningMessage,
  type State,
  type Context,
  type ToolCall,
  type Tool,
  AGUIConnectNotImplementedError,
  compactEvents,
  runHttpRequest,
  transformHttpEventStream,
} from "@ag-ui/client";

// React components and hooks for CopilotKit2
export {
  // Chat components
  CopilotChatInput,
  type CopilotChatInputProps,
  type ToolsMenuItem,
  CopilotChatAssistantMessage,
  type CopilotChatAssistantMessageProps,
  CopilotChatUserMessage,
  type CopilotChatUserMessageProps,
  CopilotChatReasoningMessage,
  type CopilotChatReasoningMessageProps,
  CopilotChatAudioRecorder,
  type AudioRecorderState,
  AudioRecorderError,
  CopilotChatSuggestionPill,
  type CopilotChatSuggestionPillProps,
  CopilotChatSuggestionView,
  type CopilotChatSuggestionViewProps,
  CopilotChatMessageView,
  type CopilotChatMessageViewProps,
  CopilotChatToolCallsView,
  type CopilotChatToolCallsViewProps,
  CopilotChatView,
  type CopilotChatViewProps,
  CopilotChat,
  type CopilotChatProps,
  CopilotChatToggleButton,
  type CopilotChatToggleButtonProps,
  CopilotChatToggleButtonOpenIcon,
  CopilotChatToggleButtonCloseIcon,
  CopilotSidebarView,
  type CopilotSidebarViewProps,
  CopilotPopupView,
  type CopilotPopupViewProps,
  CopilotModalHeader,
  type CopilotModalHeaderProps,
  CopilotSidebar,
  type CopilotSidebarProps,
  CopilotPopup,
  type CopilotPopupProps,
  // Other components
  WildcardToolCallRender,
  CopilotKitInspector,
  type CopilotKitInspectorProps,
  MCPAppsActivityRenderer,
  MCPAppsActivityType,
  MCPAppsActivityContentSchema,
  type MCPAppsActivityContent,
} from "./components";

export {
  useRenderToolCall,
  useRenderCustomMessages,
  useRenderActivityMessage,
  useFrontendTool,
  useComponent,
  useRenderTool,
  useDefaultRenderTool,
  useHumanInTheLoop,
  useAgent,
  UseAgentUpdate,
  useAgentContext,
  type AgentContextInput,
  type JsonSerializable,
  useSuggestions,
  useConfigureSuggestions,
  useInterrupt,
  type UseInterruptConfig,
} from "./hooks";

export {
  CopilotChatConfigurationProvider,
  useCopilotChatConfiguration,
  type CopilotChatLabels,
  type CopilotChatConfigurationValue,
  type CopilotChatConfigurationProviderProps,
  CopilotKitProvider,
  useCopilotKit,
  type CopilotKitProviderProps,
  type CopilotKitContextValue,
} from "./providers";

export {
  type ReactToolCallRenderer,
  type ReactActivityMessageRenderer,
  type ReactCustomMessageRendererPosition,
  type ReactCustomMessageRenderer,
  type ReactFrontendTool,
  type ReactHumanInTheLoop,
  defineToolCallRenderer,
  type InterruptEvent,
  type InterruptHandlerProps,
  type InterruptRenderProps,
} from "./types";

export {
  CopilotKitCoreReact,
  type CopilotKitCoreReactConfig,
  type CopilotKitCoreReactSubscriber,
} from "./lib/react-core";
