import type { RuntimeInfo, AgentToolDescription } from "@copilotkitnext/shared";
import chalk from "chalk";
import * as fs from "node:fs";
import * as path from "node:path";

interface CollectedAgent {
  name: string;
  description: string;
  className: string;
  tools: AgentToolDescription[];
}

// ── Pretty-print helpers ─────────────────────────────────────────────

const icons = {
  fetch: chalk.cyan("~"),
  ok: chalk.green("*"),
  warn: chalk.yellow("!"),
  err: chalk.red("x"),
  file: chalk.green("+"),
  skip: chalk.dim("-"),
  agent: chalk.magenta(">"),
  tool: chalk.blue("."),
} as const;

function header(text: string) {
  const line = chalk.dim("─".repeat(48));
  console.log(`\n  ${line}`);
  console.log(`  ${chalk.bold(text)}`);
  console.log(`  ${line}\n`);
}

// ── Network ──────────────────────────────────────────────────────────

/**
 * Fetch runtime info from a URL.
 * Tries multi-endpoint GET /info first, then falls back to single-endpoint POST.
 */
async function fetchRuntimeInfo(url: string): Promise<RuntimeInfo> {
  const baseUrl = url.replace(/\/+$/, "");

  // Try multi-endpoint: GET {baseUrl}/info
  try {
    const infoUrl = `${baseUrl}/info`;
    const response = await fetch(infoUrl, {
      method: "GET",
      headers: { Accept: "application/json" },
    });
    if (response.ok) {
      return (await response.json()) as RuntimeInfo;
    }
  } catch {
    // Ignore — try single-endpoint fallback
  }

  // Try single-endpoint: POST to baseUrl with { method: "info" }
  const response = await fetch(baseUrl, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Accept: "application/json",
    },
    body: JSON.stringify({ method: "info" }),
  });

  if (!response.ok) {
    throw new Error(`${response.status} ${response.statusText}`);
  }

  return (await response.json()) as RuntimeInfo;
}

// ── Code generation helpers ──────────────────────────────────────────

function jsonSchemaToTypeString(
  schema: Record<string, unknown>,
  indent = 2,
): string {
  const type = schema.type as string | undefined;

  if (!type) return "unknown";
  if (type === "string") return "string";
  if (type === "number" || type === "integer") return "number";
  if (type === "boolean") return "boolean";
  if (type === "null") return "null";

  if (type === "array") {
    const items = schema.items as Record<string, unknown> | undefined;
    if (!items) return "unknown[]";
    return `${jsonSchemaToTypeString(items, indent)}[]`;
  }

  if (type === "object") {
    const properties = schema.properties as
      | Record<string, Record<string, unknown>>
      | undefined;
    if (!properties || Object.keys(properties).length === 0) {
      return "Record<string, unknown>";
    }

    const required = (schema.required as string[]) ?? [];
    const pad = " ".repeat(indent);
    const entries = Object.entries(properties).map(([key, propSchema]) => {
      const optional = required.includes(key) ? "" : "?";
      const propType = jsonSchemaToTypeString(propSchema, indent + 2);
      return `${pad}${key}${optional}: ${propType};`;
    });

    return `{\n${entries.join("\n")}\n${" ".repeat(indent - 2)}}`;
  }

  return "unknown";
}

function generateTypesFile(agents: Map<string, CollectedAgent>): string {
  const lines: string[] = [];
  lines.push("// Auto-generated by @copilotkitnext/cli typegen");
  lines.push("// Do not edit manually\n");

  // Per-agent tool maps inside Agents
  lines.push("export type Agents = {");
  for (const [agentId, agent] of agents) {
    const desc = agent.description ? ` // ${agent.description}` : "";
    lines.push(`  "${agentId}": {${desc}`);
    lines.push("    tools: {");
    if (agent.tools.length === 0) {
      lines.push("      // No tools");
    }
    for (const tool of agent.tools) {
      const paramType = tool.parameters
        ? jsonSchemaToTypeString(tool.parameters, 8)
        : "Record<string, unknown>";
      lines.push(`      "${tool.name}": ${paramType};`);
    }
    lines.push("    };");
    lines.push("  };");
  }
  lines.push("};\n");

  // Merged Tools type — conflicting names become param unions
  const toolsByName = new Map<string, string[]>();
  const toolOwners = new Map<string, string[]>();
  for (const [agentId, agent] of agents) {
    for (const tool of agent.tools) {
      const paramType = tool.parameters
        ? jsonSchemaToTypeString(tool.parameters, 4)
        : "Record<string, unknown>";
      const existing = toolsByName.get(tool.name) ?? [];
      // Only add if this param type string is not already present (dedup identical definitions)
      if (!existing.includes(paramType)) {
        existing.push(paramType);
      }
      toolsByName.set(tool.name, existing);

      const owners = toolOwners.get(tool.name) ?? [];
      owners.push(agentId);
      toolOwners.set(tool.name, owners);
    }
  }

  // Log info for tools shared across agents
  for (const [toolName, owners] of toolOwners) {
    if (owners.length > 1) {
      console.log(
        `  ${icons.tool} ${chalk.dim(`Tool "${toolName}" defined by ${owners.map((o) => `"${o}"`).join(", ")} — merged as union`)}`,
      );
    }
  }

  lines.push("export type Tools = {");
  if (toolsByName.size === 0) {
    lines.push("  // No tools discovered");
  }
  for (const [toolName, paramTypes] of toolsByName) {
    lines.push(`  "${toolName}": ${paramTypes.join(" | ")};`);
  }
  lines.push("};");

  return lines.join("\n") + "\n";
}

function generateRegisterFile(): string {
  return `// Auto-generated by @copilotkitnext/cli typegen
// Do not edit manually

import type { Agents, Tools } from "./types";

declare module "@copilotkitnext/react" {
  interface Register {
    agents: Agents;
    tools: Tools;
  }
}
`;
}

// ── Project config updates ───────────────────────────────────────────

function ensureGitignore(projectDir: string, pattern: string): boolean {
  const gitignorePath = path.join(projectDir, ".gitignore");

  let content = "";
  if (fs.existsSync(gitignorePath)) {
    content = fs.readFileSync(gitignorePath, "utf-8");
  }

  const lines = content.split("\n");
  if (lines.some((line) => line.trim() === pattern)) {
    return false; // already present
  }

  const newContent = content.endsWith("\n")
    ? `${content}${pattern}\n`
    : `${content}\n${pattern}\n`;
  fs.writeFileSync(gitignorePath, newContent, "utf-8");
  return true;
}

function ensureTsconfigInclude(projectDir: string): boolean | null {
  const tsconfigPath = path.join(projectDir, "tsconfig.json");
  if (!fs.existsSync(tsconfigPath)) {
    return null; // no tsconfig
  }

  const raw = fs.readFileSync(tsconfigPath, "utf-8");
  let tsconfig: Record<string, unknown>;
  try {
    tsconfig = JSON.parse(raw);
  } catch {
    return null; // unparseable
  }

  const include = (tsconfig.include as string[]) ?? [];
  const pattern = ".copilotkit/register.d.ts";

  if (include.includes(pattern)) {
    return false; // already present
  }

  include.push(pattern);
  tsconfig.include = include;
  fs.writeFileSync(
    tsconfigPath,
    JSON.stringify(tsconfig, null, 2) + "\n",
    "utf-8",
  );
  return true;
}

// ── Main ─────────────────────────────────────────────────────────────

export async function typegen(urls: string[]): Promise<void> {
  const agents = new Map<string, CollectedAgent>();

  header("Fetching runtime info");

  for (let i = 0; i < urls.length; i++) {
    const url = urls[i];
    const label = urls.length > 1 ? `[${i + 1}/${urls.length}] ` : "";

    console.log(`  ${icons.fetch} ${label}${chalk.underline(url)}`);

    try {
      const info = await fetchRuntimeInfo(url);
      console.log(`    ${chalk.dim("version")} ${chalk.white(info.version)}`);

      const agentNames = Object.keys(info.agents);
      if (agentNames.length === 0) {
        console.log(`    ${icons.warn} ${chalk.yellow("No agents found")}`);
        continue;
      }

      for (const [agentId, agentDesc] of Object.entries(info.agents)) {
        if (agents.has(agentId)) {
          console.log(
            `    ${icons.warn} ${chalk.yellow(`Agent "${agentId}" already discovered — overwriting (last wins)`)}`,
          );
        }

        agents.set(agentId, {
          name: agentDesc.name,
          description: agentDesc.description,
          className: agentDesc.className,
          tools: agentDesc.tools ?? [],
        });

        const toolCount = agentDesc.tools?.length ?? 0;
        const toolSuffix =
          toolCount > 0
            ? chalk.dim(` (${toolCount} tool${toolCount === 1 ? "" : "s"})`)
            : "";
        console.log(
          `    ${icons.agent} ${chalk.magenta(agentId)} ${chalk.dim("·")} ${agentDesc.className}${toolSuffix}`,
        );

        if (agentDesc.tools && agentDesc.tools.length > 0) {
          for (const tool of agentDesc.tools) {
            console.log(
              `      ${icons.tool} ${chalk.blue(tool.name)} ${chalk.dim("—")} ${chalk.dim(tool.description)}`,
            );
          }
        }
      }
    } catch (error) {
      console.log(
        `    ${icons.err} ${chalk.red(`Failed: ${error instanceof Error ? error.message : String(error)}`)}`,
      );
    }

    if (i < urls.length - 1) console.log();
  }

  if (agents.size === 0) {
    console.log();
    console.error(
      `  ${icons.err} ${chalk.red.bold("No agents discovered. Nothing to generate.")}`,
    );
    console.log();
    process.exit(1);
  }

  // ── Generate files ───────────────────────────────────────────────

  header("Generating types");

  const cwd = process.cwd();
  const outDir = path.join(cwd, ".copilotkit");

  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
  }

  const typesContent = generateTypesFile(agents);
  const typesPath = path.join(outDir, "types.ts");
  fs.writeFileSync(typesPath, typesContent, "utf-8");
  console.log(`  ${icons.file} ${chalk.green(path.relative(cwd, typesPath))}`);

  const registerContent = generateRegisterFile();
  const registerPath = path.join(outDir, "register.d.ts");
  fs.writeFileSync(registerPath, registerContent, "utf-8");
  console.log(
    `  ${icons.file} ${chalk.green(path.relative(cwd, registerPath))}`,
  );

  // ── Update project config ────────────────────────────────────────

  const gitignoreUpdated = ensureGitignore(cwd, ".copilotkit/");
  const tsconfigResult = ensureTsconfigInclude(cwd);

  // Only show the section if something actually changed or needs attention
  const hasConfigChanges =
    gitignoreUpdated || tsconfigResult === true || tsconfigResult === null;

  if (hasConfigChanges) {
    header("Updating project config");

    if (gitignoreUpdated) {
      console.log(
        `  ${icons.file} ${chalk.white(".gitignore")} ${chalk.dim("— added .copilotkit/")}`,
      );
    }

    if (tsconfigResult === true) {
      console.log(
        `  ${icons.file} ${chalk.white("tsconfig.json")} ${chalk.dim("— added .copilotkit/register.d.ts to include")}`,
      );
    } else if (tsconfigResult === null) {
      console.log(
        `  ${icons.warn} ${chalk.yellow("tsconfig.json")} ${chalk.dim("— not found or unparseable, skipped")}`,
      );
    }
  }

  // ── Summary ──────────────────────────────────────────────────────

  const uniqueToolNames = new Set<string>();
  for (const agent of agents.values()) {
    for (const tool of agent.tools) {
      uniqueToolNames.add(tool.name);
    }
  }
  const totalTools = uniqueToolNames.size;

  console.log();
  console.log(
    `  ${chalk.green.bold("Done!")} ${chalk.dim("Discovered")} ${chalk.bold(String(agents.size))} ${chalk.dim(`agent${agents.size === 1 ? "" : "s"}`)} ${chalk.dim("and")} ${chalk.bold(String(totalTools))} ${chalk.dim(`tool${totalTools === 1 ? "" : "s"}.`)}`,
  );
  console.log(`  ${chalk.dim("Your hooks are now type-safe. Happy coding!")}`);
  console.log();
}
