#!/usr/bin/env bash
# showcase cvdiag-stage-ts — stage the shared CVDIAG TypeScript emitter into
# each TS integration's own build context.
# Sourced by the main dispatcher; do not execute directly.
#
# The five TS-backed integrations (langgraph-typescript, claude-sdk-typescript,
# mastra, built-in-agent, strands-typescript) each build STANDALONE (their own
# Docker build context is the integration dir). They have no path alias back to
# `showcase/harness/src/cvdiag` and no workspace import, so the canonical L0-A
# CVDIAG sources cannot be reached across the monorepo at build time. This is
# the TS analogue of L0-C's Python `_shared` COPY-staging: copy the canonical
# sources into a co-located `src/cvdiag/` dir inside each integration so they
# are (a) inside the build context, (b) bundled into `.next` by `next build`
# (the route handler imports them in-process), and (c) resolvable via the
# `@/cvdiag/*` path alias that every TS integration already declares.
#
# NOTE on `tsc` target: the staged `emit.ts` uses BigInt literals (`40n`) in the
# UUIDv7 minter, which `tsc` flags as TS2737 under the integrations' `target:
# ES2017` tsconfig. The staged copies are kept VERBATIM (true single source) and
# this is non-fatal: every TS integration sets `typescript.ignoreBuildErrors:
# true` in next.config, `next build` transpiles BigInt literals via SWC to a
# Node-22-correct runtime, and the vitest suites pass via esbuild. The build gate
# is `next build`, not standalone `tsc`. Do NOT rewrite the staged sources to
# dodge TS2737 — that would diverge them from canonical and break --check drift.
#
# SINGLE SOURCE OF TRUTH: this command COPIES from the canonical L0-A sources
# (`showcase/harness/src/cvdiag/{schema,edge-headers,emit}.ts`) plus the shared
# barrel (`showcase/integrations/_shared/ts/cvdiag-emitter.ts`, FLATTENED so its
# re-exports point at the co-located copies instead of `../../../harness/...`).
# Re-run after any L0-A schema change and commit the staged copies. A `--check`
# mode verifies the staged copies are in sync (for CI / pre-commit).

CMD_CVDIAG_STAGE_TS_DESC="Stage the shared CVDIAG TS emitter into each TS integration build context"

# The five TS integrations that import the CVDIAG emitter (the first four
# in-process via their Next route; strands-typescript agent-side in its Express
# process — see integrations/strands-typescript/src/agent/cvdiag-backend-strands.ts).
_CVDIAG_TS_INTEGRATIONS=(
  "langgraph-typescript"
  "claude-sdk-typescript"
  "mastra"
  "built-in-agent"
  "strands-typescript"
)

# The canonical L0-A sources (relative to harness/src/cvdiag/). They are
# already self-referential via `./schema.js` etc., so copying them verbatim
# into a co-located dir keeps the relative imports resolving. `scrub.ts` is the
# leaf secret/PII scrub module that BOTH `schema.ts` (metadata-value scrub) and
# `edge-headers.ts` (which re-exports `scrubSecrets`/`scrubDeep` for back-compat)
# import via `./scrub.js`; it MUST be staged alongside them or those co-located
# imports dangle inside the standalone build context (and the stale legacy
# inline scrub — which leaks base64url `sk-ant-…` keys and colon-less URL
# userinfo — would ship instead).
_CVDIAG_L0A_SOURCES=(
  "scrub.ts"
  "schema.ts"
  "edge-headers.ts"
  "emit.ts"
  "pb-writer-fetch.ts"
)

usage_cvdiag_stage_ts() {
  cat <<'HELP'
Usage: showcase cvdiag-stage-ts [--check]

Stage the canonical CVDIAG TypeScript emitter into each TS integration's
co-located `src/cvdiag/` dir so the emitter is reachable inside each
integration's standalone Docker build context.

Options:
  --check    Verify the staged copies are in sync with the canonical sources
             WITHOUT writing (exit non-zero on drift). Intended for CI.

Staged into each of: langgraph-typescript, claude-sdk-typescript, mastra,
built-in-agent, strands-typescript (under src/cvdiag/):
  scrub.ts, schema.ts, edge-headers.ts, emit.ts, pb-writer-fetch.ts
                                        (verbatim from harness/src/cvdiag/)
  cvdiag-emitter.ts                     (flattened barrel: re-exports the
                                         co-located copies, not ../../../harness)
HELP
}

# Emit the FLATTENED barrel to stdout. Identical export surface to
# showcase/integrations/_shared/ts/cvdiag-emitter.ts, but the re-export
# specifiers point at the co-located `./{schema,edge-headers,emit}.js` copies
# rather than reaching back across the monorepo to `../../../harness/...`.
_cvdiag_emit_flattened_barrel() {
  cat <<'BARREL'
/**
 * cvdiag-emitter.ts — co-located CVDIAG emitter barrel for a STANDALONE TS
 * integration build context. GENERATED by `showcase cvdiag-stage-ts` — do NOT
 * edit by hand; edit the canonical sources under
 * `showcase/harness/src/cvdiag/` and re-run the stage command.
 *
 * This is the FLATTENED form of `showcase/integrations/_shared/ts/cvdiag-emitter.ts`:
 * the shared barrel re-exports from `../../../harness/src/cvdiag/*`, which has
 * no resolution inside a standalone integration's Docker build context. The
 * stage command copies the L0-A sources (scrub.ts, schema.ts, edge-headers.ts,
 * emit.ts, pb-writer-fetch.ts) next to this file and rewrites the re-export
 * specifiers to the co-located `./*.js` copies so `next build` bundles a
 * self-contained emitter + concrete writer-role PB writer.
 */

// ── Schema (types, enums, validators, UUIDv7 regex) ─────────────────────────
export {
  SCHEMA_VERSION,
  CVDIAG_LAYERS,
  CVDIAG_OUTCOMES,
  PROBE_BOUNDARIES,
  BACKEND_BOUNDARIES,
  AIMOCK_BOUNDARIES,
  CVDIAG_DATA_PLANE_BOUNDARIES,
  CVDIAG_ACCOUNTING_BOUNDARIES,
  CVDIAG_BOUNDARIES,
  EDGE_HEADER_KEYS,
  TERMINATION_KINDS,
  TEST_ID_REGEX,
  ENVELOPE_KEYS,
  BOUNDARY_METADATA_KEYS,
  isValidTestId,
  validateEnvelope,
  validateMetadata,
} from "./schema.js";

export type {
  CvdiagLayer,
  CvdiagOutcome,
  CvdiagDataPlaneBoundary,
  CvdiagAccountingBoundary,
  CvdiagBoundary,
  EdgeHeaders,
  EdgeHeaderKey,
  TerminationKind,
  CvdiagEnvelope,
  EnvelopeValidationResult,
  MetadataValidationResult,
} from "./schema.js";

// ── Edge-header allow/deny filter + PII scrub ───────────────────────────────
export {
  EDGE_HEADER_ALLOWLIST,
  EDGE_HEADER_DENYLIST,
  BEARER_TOKEN_REGEX,
  SK_KEY_REGEX,
  URL_USERINFO_REGEX,
  SCRUB_REPLACEMENT,
  scrubSecrets,
  filterEdgeHeaders,
} from "./edge-headers.js";

// ── Emitter (tier resolution, fail-closed DEBUG, byte caps, span/id minters) ─
export {
  CvdiagEmitter,
  BYTE_CAP_BY_TIER,
  QUEUE_CAP,
  DEBUG_MAX_WALLCLOCK_MS,
  DEBUG_MAX_EVENTS,
  FLUSH_WINDOW_MS,
  resolveEnvLabel,
  mintTestId,
  mintSpanId,
} from "./emit.js";

export type {
  CvdiagTier,
  CvdiagPbWriter,
  CvdiagEnv,
  CvdiagEmitterOptions,
  CvdiagEmitArgs,
} from "./emit.js";

// ── Concrete writer-role PB writer (plain fetch; auth-with-password→Bearer) ──
export {
  CvdiagFetchPbWriter,
  createCvdiagFetchPbWriterFromEnv,
} from "./pb-writer-fetch.js";

export type {
  FetchLike,
  CvdiagFetchPbWriterOptions,
} from "./pb-writer-fetch.js";
BARREL
}

cmd_cvdiag_stage_ts() {
  local check_only=0

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --check)
        check_only=1
        shift
        ;;
      -h|--help)
        usage_cvdiag_stage_ts
        return 0
        ;;
      *)
        die "Unknown argument: $1 (see showcase cvdiag-stage-ts --help)"
        ;;
    esac
  done

  local harness_cvdiag="$SHOWCASE_ROOT/harness/src/cvdiag"
  local integrations_dir="$SHOWCASE_ROOT/integrations"

  local src
  for src in "${_CVDIAG_L0A_SOURCES[@]}"; do
    [[ -f "$harness_cvdiag/$src" ]] \
      || die "Missing canonical source $harness_cvdiag/$src — is the cvdiag foundation (L0-A) present?"
  done

  # Build the flattened barrel once into a temp file for copy/compare.
  local tmp_barrel
  tmp_barrel="$(mktemp)"
  # shellcheck disable=SC2064
  trap "rm -f '$tmp_barrel'" RETURN
  _cvdiag_emit_flattened_barrel > "$tmp_barrel"

  local drift=0
  local integration
  for integration in "${_CVDIAG_TS_INTEGRATIONS[@]}"; do
    local dest_dir="$integrations_dir/$integration/src/cvdiag"

    if [[ "$check_only" -eq 1 ]]; then
      # Compare each staged file against its source; report drift, don't write.
      for src in "${_CVDIAG_L0A_SOURCES[@]}"; do
        if ! cmp -s "$harness_cvdiag/$src" "$dest_dir/$src"; then
          warn "DRIFT: $integration/src/cvdiag/$src differs from canonical"
          drift=1
        fi
      done
      if ! cmp -s "$tmp_barrel" "$dest_dir/cvdiag-emitter.ts"; then
        warn "DRIFT: $integration/src/cvdiag/cvdiag-emitter.ts differs from canonical barrel"
        drift=1
      fi
      continue
    fi

    info "Staging CVDIAG emitter into $integration/src/cvdiag/"
    mkdir -p "$dest_dir"
    for src in "${_CVDIAG_L0A_SOURCES[@]}"; do
      cp "$harness_cvdiag/$src" "$dest_dir/$src"
    done
    cp "$tmp_barrel" "$dest_dir/cvdiag-emitter.ts"
    # mktemp creates a 600 file; the staged copies are committed source, so
    # normalize to the repo's standard 644.
    chmod 644 "$dest_dir/cvdiag-emitter.ts"
  done

  if [[ "$check_only" -eq 1 ]]; then
    if [[ "$drift" -ne 0 ]]; then
      die "Staged CVDIAG TS sources are STALE — run 'showcase cvdiag-stage-ts' and commit."
    fi
    success "Staged CVDIAG TS sources are in sync with the canonical sources"
    return 0
  fi

  success "CVDIAG TS emitter staged into ${#_CVDIAG_TS_INTEGRATIONS[@]} integrations"
}
