export const samplePrompts = [
    "What is the capital of France?",
    "Who wrote 'Romeo and Juliet'?",
    "What is the boiling point of water?",
    "How many continents are there?",
    "Who was the first person on the moon?",
    "What is 5 + 7?",
    "Define photosynthesis.",
    "What is the tallest mountain in the world?",
    "What is the meaning of life?",
    "What is the currency of Japan?",
    "Name a mammal that can fly.",
    "What is the square root of 64?",
    "Translate 'hello' to Spanish.",
    "Who painted the Mona Lisa?",
    "What is gravity?",
    "How do you make scrambled eggs?",
    "What is the speed of light?",
    "What is the largest ocean on Earth?",
    "Who invented the telephone?",
    "What year did World War II end?",
    "What's the chemical symbol for gold?",
    "How many legs does a spider have?",
    "What is the freezing point of water?",
    "What is the opposite of 'happy'?",
    "Who discovered penicillin?",
    "What is a haiku?",
    "What language is spoken in Brazil?",
    "What's the population of Earth?",
    "What does DNA stand for?",
    "What is an antonym of 'fast'?",
    "How do you say 'thank you' in French?",
    "What is a synonym for 'beautiful'?",
    "How many days are in a year?",
    "Who is the current president of the USA?",
    "What is the largest planet in the solar system?",
    "What is 10 divided by 2?",
    "What color do you get when you mix red and blue?",
    "How do you convert Celsius to Fahrenheit?",
    "What is the smallest prime number?",
    "What is a noun?",
    "What is the capital of Canada?",
    "What is a black hole?",
    "Who wrote 'Harry Potter'?",
    "What is the meaning of 'AI'?",
    "Name a fruit that is yellow.",
    "What is 15% of 200?",
    "Define ecosystem.",
    "What causes rain?",
    "What is a palindrome?",
    "How many hours are in a day?",
    "What is electricity?",
    "What is a leap year?",
    "How many states are there in the USA?",
    "What is a verb?",
    "What is HTML used for?",
    "Who is Albert Einstein?",
    "Name a programming language.",
    "What is the internet?",
    "What is the value of Pi?",
    "What is a solar eclipse?",
    "What is the function of the heart?",
    "How do planes fly?",
    "What is a rainbow?",
    "What causes seasons?",
    "What is the moon made of?",
    "Who was Cleopatra?",
    "What is a desert?",
    "What is the capital of India?",
    "What is water made of?",
    "What is global warming?",
    "Who is Elon Musk?",
    "What is the Great Wall of China?",
    "What are the primary colors?",
    "What is the purpose of education?",
    "How do magnets work?",
    "Name a type of cloud.",
    "What is a virus?",
    "What is the difference between a cat and a dog?",
    "What are human rights?",
    "What is climate change?",
    "What is a galaxy?",
    "What is a democracy?",
    "What is a tsunami?",
    "How do you bake a cake?",
    "What is an adjective?",
    "What is a constellation?",
    "How many bones are in the human body?",
    "What is a fossil?",
    "What is the Pythagorean theorem?",
    "What is a volcano?",
    "What is 100 in Roman numerals?",
    "How does a plant grow?",
    "What is a hurricane?",
    "What is electricity used for?",
    "What is a magnet?",
    "What is the capital of Australia?",
    "How do fish breathe?",
    "What is a synonym for 'smart'?",
    "What is the internet made of?",
    "What is a robot?",
    "What is a planet?",
    "Who is the founder of Microsoft?",
    "What is AI used for?"
]

