name: publish / custom

on:
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  custom-pre:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Nx
        uses: ./.github/actions/setup-nx
        with:
          workflow-name: "publish-custom"
          frozen-lockfile: "false"
          install-uv: "true"

      - name: Setup Node for npm registry
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          registry-url: https://registry.npmjs.org
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build
        run: pnpm run build

      - name: Publish snapshot
        run: ./scripts/release/publish-snapshot-release.sh
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
