name: 🚀 pkg-pr-new
on: [push, pull_request]

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Nx
        uses: ./.github/actions/setup-nx
        with:
          workflow-name: "pkg-pr-new"
          frozen-lockfile: "false"

      - name: Build
        run: pnpm run build

      - run: npx pkg-pr-new publish  --pnpm --packageManager pnpm "./packages/v1/*" "./packages/v2/*"
