name: Sentinel
on:
  pull_request:
  push:
    branches: [main]
permissions:
  contents: read
jobs:
  scan:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: jpr5/sentinel@2972cd7183264739e615939cba51988885920c36 # v1.3.3
        with:
          severity: high
          fail-on-findings: true
